### ISSUE TITLE
Amplify does not recognize framework when using CDK

### ISSUE THREAD

**Issue by agscripter** [aws-amplify/amplify-hosting#1406]
**Describe the bug**
When deploying Amplify app using CDK, It does not recognize the framework (react in this case) and then I got `Access Denied` when trying to access `/static/` URL path.

**To Reproduce**
I have created a CDK project using the following code:
```
const amplifyApp = new amplify.App(this, 'dashboard-app', {
      sourceCodeProvider: new amplify.GitHubSourceCodeProvider({
        owner: '...',
        repository: '...',
        oauthToken: cdk.SecretValue.plainText('..`)
      }),
      buildSpec: codebuild.BuildSpec.fromObject({
        version: '1.0',
        frontend: {
          phases: {
            preBuild: {
              commands: [
                'npm install'
              ]
            },
            build: {
              commands: [
                'npm run build'
              ]
            }
          },
          artifacts: {
            baseDirectory: '/build',
            files: '**/*'
          },
          cache: {
            paths: [ 'node_modules/**/*' ]
          }
        }
      }),
      environmentVariables: {
        PUBLIC_URL: '...'
      }
    });
    amplifyApp.addBranch("main");
```

In console, checking **App Settings** and then **General**, Framework configuration is empty/null.

**Expected behavior**
Framework should be **React**, when I deploy it manually in console, it recognizes the framework, and then everything works.

**Additional context**
* When this does have a Framework in General settings, it seems to give errors when trying to access `/static/` path.

**Comment by ykrasik** [comment]
I'm also using a monorepo, did you add `appRoot`?
Here's a full example of `amplify.yml` at the root of my monorepo. The amplify related project is under the `amplify` folder:
```
version: 1
applications:
  - appRoot: amplify
    frontend:
      phases:
        preBuild:
          commands:
            - yarn
        build:
          commands:
            - yarn build
      artifacts:
        baseDirectory: dist
        files:
          - '**/*'
      cache:
        paths:
          - node_modules/**/*
          - .yarn/cache/**/*
```
