### ISSUE TITLE
Amplify seems to add a large amount of delay to reverse proxy requests

### ISSUE THREAD

**Issue by boatcoder** [aws-amplify/amplify-hosting#1719]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Describe the bug

When not using Amplify (using separate nginx hosted react front end, my backend responds in 18.2 seconds for a large set of data.  When using Amplify for the exact same data, to the exact same backend, the response exceeds 30 seconds and of course Amplify kills the request and returns a 502.  What is amplify doing to extend this 18 second response past the 30 second mark.

### Expected behavior

i expect an 18 second response, not a 12+ second delay.  This started out as #1171 to control the reverse proxy timeout, but if Amplify is going to add 12 seconds to everything then amplify will not be usable as a product.

### Reproduction steps

Open our NOT amplify version and load the page. 18 seconds from nothing to done
Open our amplify version of the same page (same JS, same backend as above) more than 30s (and then the connection is 502'd)
Exact same backend URL used in both cases.  One is handled via nginx reverse proxy, one is handled by amplify.

### Build Settings

```yaml
[
    {
        "source": "/api/v3/<*>",
        "target": "elements-api.humanyze.com/api/v3/<*>",
        "status": "200",
        "condition": null
    },
    {
        "source": "/<*>",
        "target": "/index.html",
        "status": "404-200",
        "condition": null
    },
    {
        "source": "</^[^.]+$|\\.(?!(css|gif|ico|jpg|js|png|txt|svg|woff|ttf|map|json)$)([^.]+$)/>",
        "target": "/index.html",
        "status": "200",
        "condition": null
    }
]
```

This is the Amplify version of the API access
https://user-images.githubusercontent.com/18578897/113328420-e0198d80-92e1-11eb-854f-b9cd657744a8.mp4

This is the NON-Amplify version of the same API Access
https://user-images.githubusercontent.com/18578897/113334013-c596e280-92e8-11eb-807d-8eb64383be88.mp4
