### ISSUE TITLE
[NextJS] Starting SSR Build... TypeError

### ISSUE THREAD

**Issue by mhamendes** [aws-amplify/amplify-hosting#1926]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

dt0016ajs5y61

### Region

us-east-1

### Amplify Console feature

Logging

### Describe the bug

My NextJS with TypeScript application fails to build without any additional information. The build logs contain the following messages:

2021-06-02T23:25:14.067Z [INFO]: Done in 155.35s.
2021-06-02T23:25:14.074Z [INFO]: Starting SSR Build...
2021-06-02T23:27:28.925Z [INFO]: TypeError

I suspect it's a TypeScript error, but when I run yarn lint, nothing is accused.

### Expected behavior

I expected the logs to show me what error is happening so I can fix it and successfully deploy the app

### Reproduction steps

1. Committed the code changes to the gitlab branch connected to amplify.
2. CI/CD kicked off
3. Front-end build failed.

### Build Settings

```yaml
version: 0.1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - export BUILD_DIR=$PWD/$BUILD_DIR_NAME
        - yarn install
        - cat aws-exports.js
        - yarn lint --fix
        - export NODE_OPTIONS="--max-old-space-size=5120"
    build:
      commands:
        - yarn build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

### Additional information

I tried using NODE_OPTIONS=--max-old-space-size=5120 but this didnt resolve the issue

I followed along here as well

#1853
#1874 
#1882 
#1889
