### ISSUE TITLE
amplify deployment of Next.js showing deployment failed without any error logs

### ISSUE THREAD

**Issue by zugger14** [aws-amplify/amplify-hosting#1941]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d1lxz7k7qngoq2

### Region
eu-central-1

### Amplify Console feature

Not applicable

### Describe the bug

i can deploy the repository existing in the root of created group but cannot deploy from the repository which are nested inside the group in gitlab.

### Expected behavior

my repository inside group should be deployed in amplify

### Reproduction steps

1.firstly create a group in gitlab
2. then further create a sub group 
3. and add a repository there in created sub group and deploy using amplify

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm install
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```
