### ISSUE TITLE
Nextjs SSR build error

### ISSUE THREAD

**Issue by ddangdol** [aws-amplify/amplify-hosting#1988]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d2qi06tpamqiic

### Region

ap-northeast-2

### Amplify Console feature

Build settings

### Describe the bug

My NextJS application fails to ssr build. Please check the build log  and webpack config in next.config.js below.

`2021-06-17T01:37:56.075Z [INFO]: Done in 180.45s.
2021-06-17T01:37:56.082Z [INFO]: Starting SSR Build...
2021-06-17T01:49:19.253Z [INFO]: The size of your SSR deployment is too large. Try reducing your build size by adding 'config.optimization.minimize = true;' in your webpack config in your 'next.config.js' file.
Terminating logging...`

`  webpack: (config, options) => {
    config.optimization.splitChunks.cacheGroups = { }
    config.optimization.minimize = true;`

### Expected behavior

SSR build succeed or expect the output to be a log where the problem is occurring.

### Reproduction steps

1. connected github project
2. save and deploy
3. done build
4. ssr build failed

### Build Settings

```yaml
version: 1
applications:
  - frontend:
      phases:
        install:
          runtime-versions:
            nodejs: 12
        preBuild:
          commands:
            - node -v
            - yarn install
        build:
          commands:
            - yarn build:dev
      artifacts:
        baseDirectory: .next
        files:
          - '**/*'
      cache:
        paths:
          - node_modules/**/*
```
