### ISSUE TITLE
Amplify Build failed

### ISSUE THREAD

**Issue by sandy182209** [aws-amplify/amplify-hosting#1998]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

aws:amplify:ap-southeast-2:698750000341:apps/d2pes57mg7f1ea

### Region

ap-southeast-2

### Amplify Console feature

Custom builds, Custom headers, Monorepo

### Describe the bug

2021-06-25T03:45:27.761Z [WARNING]: !Error: ENOENT: no such file or directory, open '/codebuild/output/src817206887/src/transiot/amplify.yml'
2021-06-25T03:45:27.785Z [INFO]: # Retrieving environment cache...
2021-06-25T03:45:27.812Z [INFO]: # Retrieved environment cache
2021-06-25T03:45:27.812Z [WARNING]: !Cannot read property 'split' of undefined
2021-06-25T03:45:27.823Z [ERROR]: !!! TypeError: undefined is not a function
2021-06-25T03:45:27.823Z [INFO]: # Starting environment caching...
2021-06-25T03:45:27.823Z [INFO]: # Environment caching completed
Terminating logging...

### Expected behavior

Build fails

### Reproduction steps

2021-06-25T03:45:27.761Z [WARNING]: !Error: ENOENT: no such file or directory, open '/codebuild/output/src817206887/src/transiot/amplify.yml'
2021-06-25T03:45:27.785Z [INFO]: # Retrieving environment cache...
2021-06-25T03:45:27.812Z [INFO]: # Retrieved environment cache
2021-06-25T03:45:27.812Z [WARNING]: !Cannot read property 'split' of undefined
2021-06-25T03:45:27.823Z [ERROR]: !!! TypeError: undefined is not a function
2021-06-25T03:45:27.823Z [INFO]: # Starting environment caching...
2021-06-25T03:45:27.823Z [INFO]: # Environment caching completed
Terminating logging...

### Build Settings

```yaml
version: 1
applications:
  appRoot: dist/apps/portal
  frontend:
  phases:
    preBuild:
      commands:
        - npm install
    build:
      commands:
        # - npm run build:$BUILD_ENV
        # - echo $BUILD_ENV > .env
        - echo $API_HOST >> .env
        - echo $tmp >> .env
        - npm run ui:generate apps-ui/portal
  artifacts:
    # IMPORTANT - Please verify your build output directory
    baseDirectory: dist/apps/portal
    files:
      - '**/*'
```

### Additional information

Not able to fix the issue 
 !!! TypeError: undefined is not a function
