### ISSUE TITLE
Build failed because ran out of memory

### ISSUE THREAD

**Issue by kevinadhiguna** [aws-amplify/amplify-hosting#2062]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d1op4jhqbx8i9i

### Region

ap-southeast-1

### Amplify Console feature

Build settings, Logging, Manual deploys

### Describe the bug

Build container ran out of memory

![image](https://user-images.githubusercontent.com/43397636/126066491-16c79ca1-2e0a-4082-86aa-255543d1ef31.png)

### Expected behavior

Build successful as the log says or display why container ran out of memory.

### Reproduction steps

1. Provision was successfully finished.
2. Build failed in Frontend
3. Suddenly it comes back to Provision and says that the provision phase was failed, just like this (please open images in a new tab to be able to see message correctly, I am trying to cover all section to debug so sorry if the images are too small to view) :

![image](https://user-images.githubusercontent.com/43397636/126066520-eab18e7c-6f01-461d-87c1-eb1bd6d3e9fa.png)

Last log in Frontend block in AWS Amplify Console : 

![image](https://user-images.githubusercontent.com/43397636/126066538-6d2cce19-12d8-45ad-92bd-fed04dc238a6.png)

After it said `[INFO]: [success] [webpackbar] Webpack: Compiled successfully in 47.62s` the build phase failed.

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - nvm install 14
        - nvm use 14
        - yarn install --frozen-lockfile
    build:
      commands:
        - nvm use 14
        - cp src/appConfig.staging.json src/appConfig.json
        - yarn build
  artifacts:
    baseDirectory: /dist
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
      - '!node_modules/.cache'
      - '!node_modules/ant-design-pro'
```

### Additional information

This is mentioned in #1676 as well. However, it still happened although I already excluded cache.
