### ISSUE TITLE
Amplify's CI/CD does not push changes that otherwise show up on local amplify push

### ISSUE THREAD

**Issue by wvidana** [aws-amplify/amplify-hosting#2075]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d59j1tvmglhyl

### Region

eu-west-1

### Amplify Console feature

Backend builds

### Describe the bug

I made manual changes to the Storage's cloudformation template, committed those changes and pushed to bitbucket. The Amplify CI/CD picked up the changes and started a deploy. Once done, the changes are not present (ie made changes to an IAM policy, but the policy didn't change).

If I do locally `amplify push` it tells me it needs to update the Storage category, and the changes actually take effect (after this the IAM policy does show the changes)

### Expected behavior

The changes are applied during backend build

### Reproduction steps

1. Make a change to the cloudformation template of the Storage element
2. push to the repository (github, bitbucket...) your changes
3. wait for Amplify to finish the build
4. check for the changes... they are not there

### Build Settings

```yaml
version: 1
env:
  variables:
    VERSION_AMPLIFY: 4.50.2
    AMPLIFY_USERPOOL_ID: XXXXXX
    AMPLIFY_WEBCLIENT_ID: XXXXXX
    AMPLIFY_NATIVECLIENT_ID: XXXXXX
    AMPLIFY_IDENTITYPOOL_ID: 'XXXXXX'
backend:
  phases:
    preBuild:
      commands:
        - npm i -g @aws-amplify/cli@${VERSION_AMPLIFY}
    build:
      commands:
        - echo '{}' > amplify/.config/local-env-info.json
        - amplify -v
        - update-alternatives --install /usr/bin/python3 python3 /usr/local/bin/python3.8 11
        - /usr/local/bin/pip3.8 install --user pipenv
        - '# Execute Amplify CLI with the helper script'
        - ./amplifyPush.sh --simple
```

### Additional information

Using a custom `amplifyPush.sh` altered from this repo's `master` branch.

Diff from https://github.com/aws-amplify/amplify-console/blob/081895f49291f3c1508c63ae68d42bc09a846ab9/scripts/amplifyPush.sh

```diff
 }"
 CATEGORIES=""
 if [[ -z ${AMPLIFY_FACEBOOK_CLIENT_ID} && -z ${AMPLIFY_GOOGLE_CLIENT_ID} && -z ${AMPLIFY_AMAZON_CLIENT_ID} ]]; then
-    CATEGORIES=""
+    if [[ -z ${AMPLIFY_USERPOOL_ID} && -z ${AMPLIFY_WEBCLIENT_ID} && -z ${AMPLIFY_NATIVECLIENT_ID} && -z ${AMPLIFY_IDENTITYPOOL_ID} ]]; then
+        CATEGORIES=""
+    else
+        AUTHCONFIG="{\
+        \"userPoolId\":\"${AMPLIFY_USERPOOL_ID}\",\
+        \"webClientId\":\"${AMPLIFY_WEBCLIENT_ID}\",\
+        \"nativeClientId\":\"${AMPLIFY_NATIVECLIENT_ID}\"\
+        \"identityPoolId\":\"${AMPLIFY_IDENTITYPOOL_ID}\"\
+        }"
+        CATEGORIES="{\
+        \"auth\":$AUTHCONFIG\
+        }"
+    fi
 else
     AUTHCONFIG="{\
     \"facebookAppIdUserPool\":\"${AMPLIFY_FACEBOOK_CLIENT_ID}\",\
```

Might be related to this other issue? https://github.com/aws-amplify/amplify-console/issues/2039
