### ISSUE TITLE
503 ERROR on paths with parameters inside

### ISSUE THREAD

**Issue by AustinDidierTran** [aws-amplify/amplify-hosting#2083]
**Please describe which feature you have a question about?**

I am using a custom domain with amplify (https://dev.sportfolios.app/), and all my routes that are well specified in my router works well. However, whenever there is a param inside, it seems to break. For example, `https://dev.sportfolios.app/:id`, or with this actual route: https://dev.sportfolios.app/7f2cfa7e-d561-4b95-be13-0c37c3623bc5.

This leads me to this view.

<img width="967" alt="Screen Shot 2021-07-23 at 9 54 55 AM" src="https://user-images.githubusercontent.com/8609477/126792202-5943d5dc-4356-4a92-9225-25f89d213200.png">

From the logs, I see two options:

1. Too many traffic, which I doubt since I'm the only one testing for now
2. Configuration error, which may be possible. I've tried this solution: https://stackoverflow.com/questions/57449853/react-router-dom-not-working-correctly-on-amplify-console-aws, but it didn't work

**Provide additional details**

This is a next.js project, using React + react-router. My application is SSR.

My amplify.yml.

```
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

This is my current redirect configuration

<img width="1342" alt="Screen Shot 2021-07-23 at 10 02 55 AM" src="https://user-images.githubusercontent.com/8609477/126793362-07a12c6b-841b-4dfe-9114-e6b8808f4025.png">

I've also tried this redirect configuration

<img width="1354" alt="Screen Shot 2021-07-23 at 10 04 24 AM" src="https://user-images.githubusercontent.com/8609477/126793566-0fcd94a0-fa1a-4074-addb-ef049cd84571.png">

Which leads me to this view instead

<img width="1680" alt="Screen Shot 2021-07-23 at 10 03 58 AM" src="https://user-images.githubusercontent.com/8609477/126793589-c0bfdd2f-931d-49d8-b03f-0550209a7603.png">

**What AWS Services are you utilizing?**

I am using Amazon Amplify, which should be the only thing necessary here. I also have a working environment on EC2 (which I am trying to migrate from) and it all works well there.

**Provide additional details e.g. code snippets**

Let me know if there are additional details needed here!
