### ISSUE TITLE
Amplify frontend build returns  Starting SSR Build...  [ERROR]: AccessDenied: Access Denied

### ISSUE THREAD

**Issue by zugger14** [aws-amplify/amplify-hosting#2086]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d3dh32c6fp1s0y

### Region

eu-cental-1

### Amplify Console feature

Not applicable

### Describe the bug

building next js app in amplify returns  Starting SSR Build...  [ERROR]: AccessDenied: Access Denied. 

### Expected behavior

the starting SSR build should happen without errors

### Reproduction steps

deploy a next.js SSR app using amplify console and in build steps the error comes in.

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm install
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

### Additional information

i  think the amplify is not letting me to create cloudfront distributions due to 25 number of limit of cloudfronts but i have deleted them and maybe the amplify is not detecting is my only guess.
