### ISSUE TITLE
Deployment fails with no log output

### ISSUE THREAD

**Issue by IvanLuchkin** [aws-amplify/amplify-hosting#2121]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

drbq5wwyeeiy4

### Region

eu-central-1

### Amplify Console feature

Build settings

### Describe the bug

I have created a plain CRA application and trying to deploy it using Amplify. Deployment stage of the pipeline fails as such: 
![image](https://user-images.githubusercontent.com/42548801/127745219-dce83648-808f-4763-b789-7d4cad1d37c9.png)

### Expected behavior

Pipeline should succeed

### Reproduction steps

1. Create a CRA app and push it to GitLab repo
2. Connect the repo to Amplify
3. Configure build settings (specified in the section below)
4. Trigger deployment pipeline

### Build Settings

```yaml
`version: 1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - yarn install --frozen-lockfile
    build:
      commands:
        - yarn build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
test:
  phases:
    preTest:
      commands:
        - yarn install --frozen-lockfile
    test:
      commands:
        - yarn test:ci
  artifacts:
    baseDirectory: coverage
    files:
      - '**/*'
      `
```

### Additional information

My Amplify app also contains a custom domain and a HelloWorld Lambda function on the backend.
