### ISSUE TITLE
AMPLIFY_DIFF_BACKEND, AMPLIFY_DIFF_DEPLOY and [skip-cd] not working

### ISSUE THREAD

**Issue by frank-unovica** [aws-amplify/amplify-hosting#2145]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d3hz155ieud30f

### Region

eu-central-1

### Amplify Console feature

Backend builds, Environment variables, Monorepo, Performance

### Describe the bug

According to https://docs.aws.amazon.com/amplify/latest/userguide/build-settings.html you should be able to set AMPLIFY_DIFF_BACKEND and AMPLIFY_DIFF_DEPLOY to true in the environment variables section of Amplify console and have only the frontend or backend built, depending on which files changed. Does not work.

And when you add [skip-cd] to a commit message, it should not trigger the automated build. Does not work.

Building is unacceptably slow due to pushing everything that already exists and not being able to select a decent EC2.

### Expected behavior

It should behave as documented.

### Reproduction steps

1. Create a project with automated build
2. Trigger automated build to see it works
3. Set environment variables or commit message as described above
4. Should not trigger but it does

### Build Settings

```yaml
version: 1
applications:
  - appRoot: pjk2
    backend:
      phases:
        preBuild:
          commands:
            - update-alternatives --install /usr/bin/python3 python3 /usr/local/bin/python3.8 11
            - /usr/local/bin/pip3.8 install --user pipenv
            - npm -v
            - node -v
            - nvm install 14
            - nvm use 14
            - npm -v
            - node -v
            - npm i -g yarn
            - yarn -v
            - npm i -g @aws-amplify/cli
        build:
          commands:
            - amplifyPush --simple
    frontend:
      phases:
        preBuild:
          commands:
            - yarn -v
            - yarn
        build:
          commands:
            - yarn run build
      artifacts:
        baseDirectory: build
        files:
          - '**/*'
```
