### ISSUE TITLE
Unable to connect a new branch: backend fails creation because the branch already exists

### ISSUE THREAD

**Issue by ludokx** [aws-amplify/amplify-hosting#2152]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

duwnea65ixsek

### Region

us-west-2

### Amplify Console feature

Backend builds

### Describe the bug

I've been trying to connect a new branch (along with a new environment of the same name) to my project for days now and it keeps failing. I have two branches (`main` and `dev`) that are connected and work just fine. I wanted to create a new `demo` environment off of a new `demo` branch that is the exact same one as `main`. After connecting the branch, the build kicks off but fails with an error saying that the branch (`AmplifyBranch`) can't be created because it already exists.

```
2021-08-11T20:49:58.857Z [INFO]: CREATE_FAILED AmplifyBranch                                               AWS::Amplify::Branch       Wed Aug 11 2021 20:49:56 GMT+0000 (Coordinated Universal Time) Resource handler returned message: "Invalid request provided: Failed to create branch. The branch demo already exists for the app XXX (Service: Amplify, Status Code: 400, Request ID: 824b01c2-a528-41f1-b3bc-4fac41fb647a, Extended Request ID: null)" (RequestToken: XXX, HandlerErrorCode: InvalidRequest)
```

I've looked at similar issues that mentioned `amplifyPush --simple` but that's how it's already set up currently.

### Expected behavior

The new `demo` environment should be created successfully and deployed, just like all my commits to `dev` and `main` work fine. Also the branch has to be available in the Git repo otherwise it can't be connected.
It seems like something in the Amplify internals is not being cleaned up correctly.

### Reproduction steps

1. Create a new branch `demo` off of `dev` or `main`, push it to the remote
2. Connect the branch on the Amplify console. 
  a. Select the branch 
  b. Select "Create new environment" (and leave environment name empty to create the same name as the branch)
3. Click "Save and deploy"
4. Wait for build to fail with error above

### Build Settings

```yaml
version: 1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```
