### ISSUE TITLE
Unable to deploy new backend for autodetected branch

### ISSUE THREAD

**Issue by adam-nygate** [aws-amplify/amplify-hosting#2189]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d2iqbpscp13v4y

### Region

eu-west-1

### Amplify Console feature

Backend builds

### Describe the bug

After an autodetected branch is connected to an app, during CI/CD, it fails to deploy a corresponding backend.

### Expected behavior

A corresponding backend should be deployed for newly connected branches, as configured in the app settings.

### Reproduction steps

1. Enable branch autodetection and define a branch pattern
2. Select the option "Create new backend environment for every connected branch"
3. On your repository, create a new branch that follows the aforementioned pattern

### Build Settings

```yaml
version: 2
env:
  variables:
    AMPLIFY_USERPOOL_ID: ---REDACTED---
    AMPLIFY_WEBCLIENT_ID: ---REDACTED---
    AMPLIFY_NATIVECLIENT_ID: ---REDACTED---
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn build
  artifacts:
    baseDirectory: dist
    files:
      - '**/*'
test:
  phases:
    preTest:
      commands:
        - yarn --cwd ./cypress
        - yarn run serve &
    test:
      commands:
        - npm run test:ci -C ./cypress
    postTest:
      commands:
        - npm run posttest -C ./cypress
  artifacts:
    baseDirectory: cypress
    configFilePath: "**/mochawesome.json"
    files:
      - "**/*.png"
      - "**/*.mp4"
```

### Additional information

Logs:
```
2021-08-21T11:13:07.833Z [INFO]: BackendEnvironment name full-stack/amplify for app d2iqbpscp13v4y is invalid
2021-08-21T11:13:07.900Z [INFO]: Random environment name shayla generated
## Checking for associated backend environment...
## No backend environment association found, continuing...
```
