### ISSUE TITLE
Build fails with "Starting SSR Build... ERROR: AccessDenied: Access Denied"

### ISSUE THREAD

**Issue by heikkikurkela** [aws-amplify/amplify-hosting#2192]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d3srkgpabkig16

### Region

eu-central-1

### Amplify Console feature

Access control

### Describe the bug

```
2021-08-23T07:09:12.169Z [INFO]: Export successful
2021-08-23T07:09:12.174Z [INFO]: Done in 63.27s.
2021-08-23T07:09:12.180Z [INFO]: Starting SSR Build...
2021-08-23T07:10:47.361Z [ERROR]: AccessDenied: Access Denied
                                  at Request.extractError (/root/.//node_modules/aws-sdk/lib/services/s3.js:714:35)
                                  at Request.callListeners (/root/.//node_modules/aws-sdk/lib/sequential_executor.js:106:20)
                                  at Request.emit (/root/.//node_modules/aws-sdk/lib/sequential_executor.js:78:10)
                                  at Request.emit (/root/.//node_modules/aws-sdk/lib/request.js:688:14)
                                  at Request.transition (/root/.//node_modules/aws-sdk/lib/request.js:22:10)
                                  at AcceptorStateMachine.runTo (/root/.//node_modules/aws-sdk/lib/state_machine.js:14:12)
                                  at /root/.//node_modules/aws-sdk/lib/state_machine.js:26:10
                                  at Request.<anonymous> (/root/.//node_modules/aws-sdk/lib/request.js:38:9)
                                  at Request.<anonymous> (/root/.//node_modules/aws-sdk/lib/request.js:690:12)
                                  at Request.callListeners (/root/.//node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
                                  code: 'AccessDenied',
                                  region: null,
                                  time: 2021-08-23T07:10:47.042Z,
                                  requestId: '<ID>',
                                  extendedRequestId: '<ID>',
                                  cfId: undefined,
                                  statusCode: 403,
                                  retryable: false,
                                  retryDelay: 73.0261642244596
                                  }
```

### Expected behavior

Build should be successful since no change

### Reproduction steps

Just re-run the pipeline

### Build Settings

```yaml
BuildSpec: |
        version: 1
        frontend:
          phases:
            preBuild:
              commands:
                - yarn install
            build:
              commands:
                - next build && next export
          artifacts:
            baseDirectory: out
            files:
              - '**/*'
          cache:
            paths:
              - node_modules/**/*
```

### Additional information

This problem began to occur from date 8/20/2021, 11:30:39 AM
