### ISSUE TITLE
Feature request: Option to disable caching based on cookies

### ISSUE THREAD

**Issue by xiaoxiaosaohuo** [aws-amplify/amplify-hosting#2243]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

dilkdnzrxxk9k

### Region

us-east-1

### Amplify Console feature

Performance

### Describe the bug

I have enable the performance mode, and configure the custom headers in `customHttp.yml`, my page sometimes is too slow, when miss cloudfront, the TTFB almost is 1s-2s,  when I access the page in chrome browser it always Miss from cloudfront, however, while I access in PostMan, it hit the cloudfront , then I access it in the command line with `curl`, the first time ,it shows `miss from cloudfront`,the others times  show `hit from cloudfront`. I don't know why they are so different, if the page is on CDN edge location, why I access it in postman ,and then access it in command line ,it shows `miss from cloudfront`? .

I think  it should hit the cloudfront after I access it, and I don't know the browser why always miss from cloudfront?

I need your kind help, thank you!

### Expected behavior

After I access the page , it should hit cloudfront , whether I use browser or the `curl`

### Reproduction steps

no steps

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - nvm install 16
        - nvm use 16
        - npm install
    build:
      commands:
        - npm run export

  artifacts:
    baseDirectory: __sapper__/export
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

### Additional information
```
customHeaders:
  - pattern: '**/*[!.html]'
    headers:
      - key: Cache-Control
        value: 'public,max-age=31536000,s-maxage=31536000,immutable'
  - pattern: '**/*'
    headers:
      - key: 'X-Frame-Options'
        value: 'SAMEORIGIN'
      - key: 'X-Content-Type-Options'
        value: 'nosniff'
      - key: 'X-XSS-Protection'
        value: '1; mode=block'
      - key: 'Strict-Transport-Security'
        value: 'max-age=31536000; includeSubDomains'

```
