### ISSUE TITLE
amplify backend build is being run twice

### ISSUE THREAD

**Issue by cfbo** [aws-amplify/amplify-hosting#2291]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d3i83n9mlag28r

### Region

eu-central-1

### Amplify Console feature

Backend builds

### Describe the bug

I am creating the bug as suggested in discord https://discord.com/channels/705853757799399426/708077731711156284/893174245184655400

I have noticed that the backend build is being run twice.
![image](https://user-images.githubusercontent.com/7568421/135522333-03153bcf-0d82-4186-b6c9-1efb654aaa82.png)

### Expected behavior

The build should run only once

### Reproduction steps

I am observing this in the cloud build when pushing in git to a branch connected to the automated build

### Additional information

this is my amplify.yml
```
version: 1
backend:
  phases:
    preBuild:
      commands:
        - npm install #this is needed for first build in a new env (because we use parent dependencies)
        - cd devops
        - npm install
        - npx ts-node ./src/build-scripts/pre-build.ts
        - cd ..
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - update-alternatives --install /usr/bin/python3 python3 /usr/local/bin/python3.8 11
        - /usr/local/bin/pip3.8 install --user pipenv        
        - amplifyPush --simple
    postBuild:
      commands:
        - cd devops
        - npm install
        - npx ts-node ./src/build-scripts/post-build.ts
        - cd ..
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: dist
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

Recently I had to make the following change:
![image](https://user-images.githubusercontent.com/7568421/135581371-a3eaa58c-089c-4100-b693-6ee298e2ad5f.png)
Any chance that's what is causing it or is unrelated?
