### ISSUE TITLE
Can't deploy after Amplify Auth Import

### ISSUE THREAD

**Issue by galacoder** [aws-amplify/amplify-hosting#2308]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

df8be0ia8uiak

### Region

ap-southeast-1

### Amplify Console feature

Build settings, Environment variables

## Backend environment association found
2021-10-07T16:18:37.531Z [INFO]: [0mAmplify AppID found: df8be0ia8uiak. Amplify App name is: projectyou[0m
2021-10-07T16:18:37.582Z [INFO]: [0mBackend environment dev found in Amplify Console app: projectyou[0m
2021-10-07T16:18:38.865Z [WARNING]: - Fetching updates to backend environment: dev from the cloud.
2021-10-07T16:18:39.418Z [WARNING]: ✔ Successfully pulled backend environment dev from the cloud.
2021-10-07T16:18:39.442Z [WARNING]: ✖ There was an error initializing your environment.
2021-10-07T16:18:39.449Z [INFO]: [31mFailed to pull the backend.[39m
2021-10-07T16:18:39.451Z [INFO]: [31mauth headless is missing the following inputParams userPoolId, webClientId, nativeClientId, identityPoolId[39m
2021-10-07T16:18:39.498Z [INFO]: [0mError: auth headless is missing the following inputParams userPoolId, webClientId, nativeClientId, identityPoolId[0m
                                 [0m    at ensureHeadlessParameters (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/src/provider-utils/awscloudformation/import/index.ts:1288:11)[0m
                                 [0m    at Object.headlessImport (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/src/provider-utils/awscloudformation/import/index.ts:1145:40)[0m
                                 [0m    at importedAuthEnvInit (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/src/provider-utils/awscloudformation/import/index.ts:922:18)[0m
                                 [0m    at runMicrotasks (<anonymous>)[0m
                                 [0m    at processTicksAndRejections (internal/process/task_queues.js:97:5)[0m
                                 [0m    at updateConfigOnEnvInit (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/src/provider-utils/awscloudformation/index.js:50:72)[0m
                                 [0m    at /root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/src/index.js:304:22[0m
2021-10-07T16:18:39.515Z [ERROR]: !!! Build failed
2021-10-07T16:18:39.515Z [ERROR]: !!! Non-Zero Exit Code detected
2021-10-07T16:18:39.516Z [INFO]: # Starting environment caching...
2021-10-07T16:18:39.516Z [INFO]: # Uploading environment cache artifact...
2021-10-07T16:18:39.628Z [INFO]: # Environment caching completed

### Expected behavior

Successfully deploy my app after importing my existing User Pool

### Reproduction steps

1. Amplify Auth Import
2. Amplify Push
3. Git Push

### Build Settings

```yaml
version: 1.0
backend:
  phases:
    build:
      commands:
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - npm install --quiet --global expo-cli
        - >
          if [ -f yarn.lock ]; then
            yarn
          elif [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then
            npm ci
          else
            npm install
          fi
    build:
      commands:
        - expo build:web
  artifacts:
    baseDirectory: web-build
    files:
      - "**/*"
  cache:
    paths:
      - node_modules/**/*
      - $(npm root --global)/**/*
```

### Additional information

I attempted this issue: https://github.com/aws-amplify/amplify-console/issues/1271#issuecomment-766311681
<img width="447" alt="Screen_Shot_2021-10-08_at_00 19 17" src="https://user-images.githubusercontent.com/13715145/136436936-a8758f04-e518-4a61-95e3-93fb8924bc82.png">

This is what I build error I got
<img width="1095" alt="Screen_Shot_2021-10-08_at_00 32 23" src="https://user-images.githubusercontent.com/13715145/136437004-c8f76e79-4d37-4707-88a5-d6cb30321e08.png">

<img width="1317" alt="Screen Shot 2021-10-08 at 10 54 23" src="https://user-images.githubusercontent.com/13715145/136495992-c189c6d7-928e-45fb-a990-3f3bc7df3507.png">

Your earliest assistance is very much appreciated. Tks!
