### ISSUE TITLE
Deploy fails after no apparent reason and without any error logs

### ISSUE THREAD

**Issue by lhrnd0** [aws-amplify/amplify-hosting#2312]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d3rzrp4hp1npt2

### Region

us-east-1

### Amplify Console feature

Logging, Manual deploys

### Describe the bug

Deploy fails just after starting (build was successful), with no apparent reason and with no clear logs.

![image](https://user-images.githubusercontent.com/1268808/136614787-cfec63b7-2ac8-42b9-a424-72868f4b883b.png)

### Expected behavior

Deploy happens successfully.

### Reproduction steps

No clear steps since it's just pushing to my repository.

### Build Settings

```yaml
version: 0.1

frontend:
  phases:
    preBuild:
      commands:
        - nvm use $VERSION_NODE_12
        - npm set //npm.pkg.github.com/:_authToken=$GITHUB_NPM_READ_TOKEN
        - npm set https://npm.pkg.github.com/
        - npm install -g npm@^7.11.0
        - rm -rf node_modules
        - npm install
    build:
      commands:
        - nvm use $VERSION_NODE_12
        - npm run release
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
```

### Additional information

The app is a `create-react-app` application.
