### ISSUE TITLE
Environment variables not pre-fixed with NEXT_PUBLIC are not available in server [Next.js] related issue

### ISSUE THREAD

**Issue by bhattibytes** [aws-amplify/amplify-hosting#2315]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

arn:aws:amplify:us-east-2:XXXXXXXXXXX:apps/dep5aop5dy2y4

### Region

us-east-2

### Amplify Console feature

Environment variables

### Describe the bug

When using NEXT.js our environment variables that are prefixed with NEXT_PUBLIC_  are accessible within our API/server code however, variables without that pre-fix are unavailable within the same scope.  

### Expected behavior

Both the with and without the prefix when testing this locally the environment variables are passed around properly but when deploying to amplify to the production build the problem arises.  

### Reproduction steps

Click on add workspace plus button 
Add any workspace 
Redirects to dashboard with env variables as undefined 

### Build Settings

```yaml
version: 1
applications:
  - backend:
      phases:
        build:
          commands:
            - '# Execute Amplify CLI with the helper script'
            - amplifyPush --simple
    frontend:
      phases:
        preBuild:
          commands:
            - npm ci
        build:
          commands:
            - npm run build
      artifacts:
        baseDirectory: .next
        files:
          - '**/*'
      cache:
        paths:
          - node_modules/**/*
    appRoot: slack-app
```

### Additional information

\n This is our server code where the env variable slack client id and slack client secret are being accessed but show as undefined but variables with pre-fix NEXT_PUBLIC_ are being accessible and defined 
<img width="1054" alt="Nextjs server redirect code " src="https://user-images.githubusercontent.com/72463293/136862636-c2ce463c-0916-404c-a330-ddbed5407dcf.png">
\n This is where we set client id in next.config.js file but then the environment variables are being exposed on the browser which is not what we want for the Slack client ID and Slack secret
<img width="2048" alt="Next js Bug env variables" src="https://user-images.githubusercontent.com/72463293/136862639-41aeb6f8-4768-46be-92aa-1627971659f0.png">
\n set environment variables in AWS amplify console but show up as undefined when trying to be accessed 
<img width="2048" alt="client ID and secret show undefined" src="https://user-images.githubusercontent.com/72463293/136862644-d5b1d5dd-ba56-4c18-8b91-9a3fa77f6dff.png">
