### ISSUE TITLE
NextJS server side redirect not working properly

### ISSUE THREAD

**Issue by mhamendes** [aws-amplify/amplify-hosting#2317]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

dt0016ajs5y61

### Region

us-east-1

### Amplify Console feature

Custom builds

### Describe the bug

I'm trying to redirect a path to another internal path in my application on getStaticProps. The redirect is successful during my local builds, but on my Amplify deploys I just get a JSON response that looks like this:

```
{
  "pageProps": {
    "__N_REDIRECT": "redirect-url",
    "__N_REDIRECT_STATUS": 307
  },
  "__N_SSG": true
}
```

My getStaticProps return looks like this:
```
if (redirectUrl) {
    return {
      redirect: {
        destination: redirectUrl,
        permanent: false,
      },
    };
  }
```

The thing is that the redirect url it's returning in the json file is the correct one, but it won't really redirect the page. I tested it with getServerSideProps and it worked just fine. For now it should be just fine, but it would be ideal for my project to use use getStaticProps and take advantages of Next JS's ISG.

### Expected behavior

The page should be redirected to the url provided.

### Reproduction steps

1. Create a redirect page in your Next JS app.
2. Deploy the application to Amplify.
3. Go to path that should redirect to other url

### Build Settings

```yaml
version: 0.1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - export BUILD_DIR=$PWD/$BUILD_DIR_NAME
        - yarn install
        - cat aws-exports.js
        - yarn lint --fix
        - export NODE_OPTIONS="--max-old-space-size=5120"
    build:
      commands:
        - yarn build
    postBuild:
        commands:
        - yarn postbuild
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```
