### ISSUE TITLE
Amplify Console should be able to build only when certain files have been modified

### ISSUE THREAD

**Issue by ffxsam** [aws-amplify/amplify-hosting#2336]
**Is your feature request related to a problem? Please describe.**
It's annoying and a waste of resources to build & deploy if we modify files that have nothing to do with the code (e.g. README or unit tests)

**Describe the solution you'd like**
It would be great to have a solution like the one GitHub Actions offers, where we can specify multiple paths to check for modified files:

```yaml
on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'infra/**'
      - '.env*'
      - 'cdk.context.json'
```
