### ISSUE TITLE
CloudFront caching errors

### ISSUE THREAD

**Issue by marco910** [aws-amplify/amplify-hosting#2355]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d7rx5b5im0en3

### Region

eu-central-1

### Amplify Console feature

Not applicable

### Describe the bug

I'm using Next.js with Incremental Site Regeneration (ISR) on Amplify. I noticed that when accessing a page that isn't built yet I'm getting a 404 error and this error is cached by CloudFront with the Cache-Control header `public, max-age=0, s-maxage=2678400, must-revalidate`.

I also tried overriding this Cache-Control headers, but that didn't work.

### Expected behavior

CloudFront shouldn't cache 404 or any other errors.

### Reproduction steps

1. Deploy a Next.js app with ISR on Amplify.
2. Try to access an ISR route – like "/news/awesome-post" that isn't built but is already created in the CMS.
3. Check the headers in the dev tools of your browser.

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

### Additional information

customHTTP.yml:

```
customHeaders:
  - pattern: '**/*'
    headers:
      - key: Cache-Control
        value: 'public, max-age=0, s-maxage=0, no-cache'
      - key: x-frame-options
        value: DENY
      - key: x-xss-protection
        value: 1; mode=block
```
