### ISSUE TITLE
Backend step still executing even if no backend differences detected with AMPLIFY_DIFF_BACKEND set to true

### ISSUE THREAD

**Issue by hisham** [aws-amplify/amplify-hosting#2385]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d2d6ty1wlg8jch

### Region

us-east-1

### Amplify Console feature

Backend builds

### Describe the bug

I recently enabled AMPLIFY_DIFF_BACKEND, I do see in the build log that amplify is checking for changes in the backend, however, even if no changes are detected the backend build phase is still run and amplify push command i executed: 

```
2021-11-16T19:18:50.458Z [INFO]: # Determining if there are buildable backend changes in the amplify directory of the repository...
2021-11-16T19:18:50.467Z [INFO]: # Last built commit: e2113968e9090f498243b161d3a580906265bdcc
2021-11-16T19:18:50.471Z [INFO]: # No differences detected.
```

And then I see

```
# Starting phase: build
# Executing command: amplify/amplify-deploy-backend.sh
2021-11-16T19:23:30.171Z [INFO]: added 192 packages, and audited 194 packages in 4s
...
```

### Expected behavior

Backend phase would be skipped. 

### Reproduction steps

1. Set AMPLIFY_DIFF_BACKEND to true
2. Make an empty commit - i.e git commit --allow-empty
3. Monitor amplify console, you'll see no backend differences detected, but backend phase still executes like before

### Build Settings

```yaml
version: 0.1
backend:
  phases:
    build:
      commands:
        - amplify/amplify-deploy-backend.sh

frontend:
  phases:
    build:
      commands:
        - frontend/amplify-deploy-frontend.sh
  artifacts:
    baseDirectory: frontend/dist/amplify
    files:
      - '**/*'
  cache:
    paths:
      - 'frontend/node_modules/**/*'
      - 'node_modules/**/*'
```
