### ISSUE TITLE
SSR Build - Module parse failed

### ISSUE THREAD

**Issue by jtmthf** [aws-amplify/amplify-hosting#2386]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d1b3v6taan5pst

### Region

us-east-1

### Amplify Console feature

Build settings

### Describe the bug

During the "SSR Build" phase the below error from webpack is logged:

```
Failed to compile.
./node_modules/openid-client/lib/client.js
Module parse failed: Unexpected character '#' (163:2)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
| class BaseClient {
>   #metadata;
|   #issuer;
|   #aadIssValidation;
> Build error occurred
```

This happens though after the first "next build" is successful.

### Expected behavior

I'd expect that the bundled webpack version is able to parse private class fields. I presume it is due to the included version being out of date.

### Reproduction steps

1. Create a new nextjs app
2. Include `next-auth` beta
3. Deploy with amplify

### Build Settings

```yaml
version: "1.0"
applications:
  - appRoot: apps/renderer
    frontend:
      phases:
        preBuild:
          commands:
            - nvm install
            - cd ../..
            - npm ci
        build:
          commands:
            - npm run build
            - cd apps/renderer
      artifacts:
        baseDirectory: .next
        files:
          - "**/*"
      cache:
        paths:
          - ~/.npm/**/*
          - .next/cache/**/*
```
