### ISSUE TITLE
Next.js SSR Build Error

### ISSUE THREAD

**Issue by lindsaybloomsonos** [aws-amplify/amplify-hosting#2387]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

arn:aws:amplify:us-east-1:885946279310:apps/dh2ndod2t9wbt

### Region

us-east-1

### Describe the bug

Yesterday I started seeing the following error suddenly without any code changes when deploying my Next.js app to amplify:
```
Starting SSR Build...
2021-11-16T22:10:34.047Z [ERROR]: Error: pages-manifest not found. Check if `next.config.js` target is set to ''
                                  at CLI.renderError (/root/.npm/_npx/1415/lib/node_modules/@sls-next/-patched/node_modules/@/cli/src/Context.js:325:15)
                                  at Object.runComponents (/root/.npm/_npx/1415/lib/node_modules/@sls-next/-patched/node_modules/@/cli/src/index.js:237:13)
                                  at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

### Expected behavior
```
2021-11-16T15:37:24.222Z [INFO]: Starting SSR Build...
2021-11-16T15:45:42.200Z [INFO]: SSR Build Complete.
2021-11-16T15:45:43.561Z [INFO]: # Completed phase: build
                                 # Starting phase: postBuild
```

### Reproduction steps

1. Create a Next.js app with a next.config.ts (use .ts extension)
2. Connect yourr Next.js app in a Github repository to deploy on merges to a branch
3. Merge code into that branch
4. Watch the build logs for the Amplify deployment
5. See if the build step succeeds

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - yarn install --frozen-lockfile
    build:
      commands:
        - yarn build
    postBuild:
      commands:
        - yarn update:cookies --dist-id-key=$COOKIE_OVERRIDE_BRANCH
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
      - .next/cache/**/*
```

### Additional information

I am using a `next.config.ts` file with a `.ts` extension
