### ISSUE TITLE
Getting stuck in the test phase

### ISSUE THREAD

**Issue by ImranArtwel** [aws-amplify/amplify-hosting#2413]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Region
us-west-2

### AppId
di7r4ky8gdyhi

### Describe the bug

When the deployment reaches the test phase it just hangs. That's all I can say. 
`2021-11-26T15:44:00.571Z [INFO]: + pm2@5.1.2
                                 added 180 packages from 200 contributors in 5.61s
2021-11-26T15:44:00.667Z [INFO]: # Executing command: npm install -g wait-on
2021-11-26T15:44:02.230Z [INFO]: /root/.nvm/versions/node/v12.21.0/bin/wait-on -> /root/.nvm/versions/node/v12.21.0/lib/node_modules/wait-on/bin/wait-on
2021-11-26T15:44:02.237Z [INFO]: + wait-on@6.0.0
                                 added 13 packages from 15 contributors in 1.24s
2021-11-26T15:44:02.338Z [INFO]: # Executing command: npm install mocha mochawesome mochawesome-merge mochawesome-report-generator
2021-11-26T15:44:18.106Z [WARNING]: npm
`

### Expected behavior

I used the default build settings so I expect the deployment to not hang and to finish successfully

### Reproduction steps

1. Create a new app
2. Deploy the app

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
test:
  artifacts:
    baseDirectory: cypress
    configFilePath: '**/mochawesome.json'
    files:
      - '**/*.png'
      - '**/*.mp4'
  phases:
    preTest:
      commands:
        - npm ci
        - npm install -g pm2
        - npm install -g wait-on
        - npm install mocha mochawesome mochawesome-merge mochawesome-report-generator
        - pm2 start npm -- start
        - wait-on http://localhost:3000
    test:
      commands:
        - 'npx cypress run --reporter mochawesome --reporter-options "reportDir=cypress/report/mochawesome-report,overwrite=false,html=false,json=true,timestamp=mmddyyyy_HHMMss"'
    postTest:
      commands:
        - npx mochawesome-merge cypress/report/mochawesome-report/mochawesome*.json > cypress/report/mochawesome.json
        - pm2 kill
```

**Comment by hloriana** [comment]
Hi @ImranArtwel can you try these build settings? The test phase is different from the documentation since this is an SSR app. We're working on updating testing documentation for SSR applications. 

```
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
test:
  phases:
    preTest:
      commands:
        - npm install
        - npm install start-server-and-test cypress mocha mochawesome mochawesome-merge mochawesome-report-generator --save-dev
    test:
      commands:
        - npm run build
        - npx start-test 'npm start' 3000 'npx cypress run --reporter mochawesome --reporter-options "reportDir=cypress/report/mochawesome-report,overwrite=false,html=false,json=true,timestamp=mmddyyyy_HHMMss"'
    postTest:
      commands:
        - npx mochawesome-merge cypress/report/mochawesome-report/mochawesome*.json > cypress/report/mochawesome.json
  artifacts:
    baseDirectory: cypress
    configFilePath: '**/mochawesome.json'
    files:
      - '**/*.png'
      - '**/*.mp4'

```
