### ISSUE TITLE
Amplify deploying incorrect files after Create React App. build

### ISSUE THREAD

**Issue by marcoamonteiro** [aws-amplify/amplify-hosting#2439]
**Please describe which feature you have a question about?**
Amplify Hosting

**Provide additional details**
I am deploying my Create React App application on amplify. In my postBuild step I `ls` the build folder and see all of my built files in there. 

The deploy step has very little logging:
```
2021-12-09T16:44:28 [INFO]: Beginning deployment for application dc6dm3d0dv5jx, branch:main, buildId 0000000017
2021-12-09T16:44:28 [INFO]: Got archive: 2060404 bytes
2021-12-09T16:44:29 [INFO]: Deployment complete
```
When I launch the application it fails to load. When I inspect the sources I see my entire application's source code has been copied into `static/js` and the build files are missing.

Here is my config:

```
version: "1.0"
frontend:
  phases:
    preBuild:
      commands:
        - cd web/dashboard
        - mkdir build
        - npm ci
    build:
      commands:
        - npm run build
    postBuild:
      commands:
        - pwd
        - ls build/static
        - ls build/static/js
  artifacts:
    baseDirectory: web/dashboard/build
    files: 
        - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

Region: us-east-1
Id: dc6dm3d0dv5jx
