### ISSUE TITLE
Missing acknowledge button for create new app with existing code

### ISSUE THREAD

**Issue by khinshankhan** [aws-amplify/amplify-hosting#2440]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Describe the bug

Hitting the next button on creation prompts the page to give the red message "Please acknowledge" but there's nowhere to toggle acknowledgment.

### Expected behavior

Can continue to create amplify app with existing code as outlined here https://docs.aws.amazon.com/amplify/latest/userguide/getting-started.html

### Reproduction steps

1. Open amplify home https://console.aws.amazon.com/amplify/home 
2. Hit get started under `Host your web app`
3. Choose github
4. Choose repository and branch
5. Choose environment name
6. Try hitting next button

### Build Settings

```yaml
version: 1
backend:
  phases:
    build:
      commands:
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - nvm install 15
        - yarn install
    build:
      commands:
        - echo "NEXT_PUBLIC_AMPLITUDE_API_KEY=$AMPLITUDE_API_KEY" >> .env
        - yarn build
  artifacts:
    baseDirectory: out
    files:
      - '**/*'
  cache:
    paths:
      - 'node_modules/**/*'
      - '*/node_modules/**/*'
      - '.next/cache/**/*'
test:
  phases:
    test:
      commands:
        - yarn test
  artifacts:
    baseDirectory: /
    configFilePath: jest.config.js
    files:
      - '**/*'
```

### Additional information

![image](https://user-images.githubusercontent.com/22206867/145448983-46a3b372-5f9f-4095-ad41-36b431d23e35.png)
