### ISSUE TITLE
Next.js build fails because npm command is not found

### ISSUE THREAD

**Issue by chase-pico** [aws-amplify/amplify-hosting#2447]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d1patyqgasciau

### Region

us-east-1

### Amplify Console feature

Build settings

### Describe the bug

When building the app, I'm getting an error that the app can't build 

### Expected behavior

I want to run npm install && npm run build:preview to build the next js app

### Reproduction steps

1.  npm install
2. npm run build:preview

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - rm -f ./.npmrc
        - nvm use --delete-prefix v12.21.0 --silent
        - . /root/.nvm/nvm.sh
        - nvm install 14.15.1
        - echo "@**********:registry=https://npm.pkg.github.com/" > ./.npmrc
        - echo "registry=https://registry.npmjs.org" >> ./.npmrc
        - echo "//npm.pkg.github.com/:_authToken=***************************" >> ./.npmrc
        - npm install
        - export NODE_OPTIONS='--max_old_space_size=4096'
    build:
      commands:
        - npm uninstall eslint && npm install --save-dev eslint@"<8.0.0"
        - export NODE_OPTIONS='--max_old_space_size=4096'
        - npm run build:preview
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```
