### ISSUE TITLE
No Test step shown in pipeline.

### ISSUE THREAD

**Issue by carlosbvz** [aws-amplify/amplify-hosting#2458]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d1t8f7v7uqkz9e

### Region

us-east-1

### Amplify Console feature

E2E tests

### Describe the bug

During build, not Test step is shown in the amplify console UI pipeline.
<img width="485" alt="Screen Shot 2021-12-16 at 17 20 44" src="https://user-images.githubusercontent.com/8539233/146463250-fb6f84dd-9362-4e1b-b875-e4021af1c786.png">

### Expected behavior

A Test step shows up in the UI between the Build and Deploy steps.

### Reproduction steps

Trigger a build by either, manually from the AWS console or by pushing a new feature branch (auto-deploy is set).

### Build Settings

```yaml
test:
  phases:
    preTest:
      commands:
        - npm install
        - npm install start-server-and-test cypress mocha mochawesome mochawesome-merge mochawesome-report-generator --save-dev
    test:
      commands:
        - npm run build
        - npx start-test 'npm start' 3000 'npx cypress run --reporter mochawesome --reporter-options "reportDir=cypress/report/mochawesome-report,overwrite=false,html=false,json=true,timestamp=mmddyyyy_HHMMss"'
    postTest:
      commands:
        - npx mochawesome-merge cypress/report/mochawesome-report/mochawesome*.json > cypress/report/mochawesome.json
  artifacts:
    baseDirectory: cypress
    configFilePath: '**/mochawesome.json'
    files:
      - '**/*.png'
      - '**/*.mp4'
```
