### ISSUE TITLE
Add Cloudfront headers and prevent reverse proxy from stripping custom headers.

### ISSUE THREAD

**Issue by Rafcin** [aws-amplify/amplify-hosting#2459]
**Is your feature request related to a problem? Please describe.**
Currently, you can't add additional CloudFront headers easily to a deployment. To add them you have to modify the serverless config during the build process and the Amplify team has to give access to the stripped headers if you use a custom domain.

**Current way to modify the serverless config**
```
  - appRoot: apps/example
    env:
    variables:
      #AMPLIFY_DIFF_DEPLOY: true
    frontend:
      phases:
        preBuild:
          commands:
            # Do pre-build stuff
        build:
          commands:
            # Run build and then copy over serverless
            - cp config/serverless.yml serverless.yml
      artifacts:
        baseDirectory: .next
        files:
          - '**/*'
      cache:
        paths:
          - node_modules/**/*
```
```
APPID-HERE:
  component: '@sls-next/serverless-component@3.6.0'
  inputs:
    timeout:
      defaultLambda: 30
      apiLambda: 30
      imageLambda: 30
      regenerationLambda: 30
    cloudfront:
      defaults:
        forward:
          headers:
            - CloudFront-Is-Desktop-Viewer
            - CloudFront-Is-Mobile-Viewer
            - CloudFront-Is-Tablet-Viewer
            - CloudFront-Viewer-Country
            - CloudFront-Viewer-Latitude
            - CloudFront-Viewer-Longitude
            - CloudFront-Viewer-Time-Zone
            - CloudFront-Viewer-City
            - Authorization
    build:
      env:
        AMPLIFY_DIFF_DEPLOY: 'false'
        AMPLIFY_MONOREPO_APP_ROOT: apps/news
```

https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/using-cloudfront-headers.html

**Describe the solution you'd like**
Ideally, a config option in the console would be nice. A dropdown similar to the Cloudfront behaviors dropdown would work.

The option to choose what is removed by the proxy would also be nice instead of having someone modify it. If someone plans to release 3 or 4 sites, they would need to contact the amplify team each time, therefore it would be easier to allow the users to modify it themselves per project.
