### ISSUE TITLE
aws doesn't detect nextjs apps in gitlab repositories

### ISSUE THREAD

**Issue by GiancarlosIO** [aws-amplify/amplify-hosting#2475]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Region

us-east-1

### Amplify Console feature

SSR app hosting

### Describe the bug

I'm trying to setup a nextjs project using gitlab but  aws amplify doesn't detect that my app is a "next.js" app.
Looks like this is only happening for **gitlab repositories,** I have tried the same source code with github and it detect it without any problems.
### Gitlab:
<img width="792" alt="Screen Shot 2021-12-26 at 19 51 38" src="https://user-images.githubusercontent.com/17274950/147424153-3bb00526-5509-4375-8808-16f2886824a4.png">

### Github:
<img width="822" alt="Screen Shot 2021-12-26 at 19 55 59" src="https://user-images.githubusercontent.com/17274950/147424285-22fb8f9b-b8bf-4133-8bbd-836a88d12433.png">

### Expected behavior

When using gitlab, aws-amplify should detect that my project is using nextjs.

### Reproduction steps

1. Go to amplify
2. Connect to gitlab
3. Select a nextjs project
4. Go to the build step
5. aws-amplify doesn't detect that the project is using nextjs.

### Additional information

Next.js: v11.x

**Comment by hloriana** [comment]
Hi @GiancarlosIO  👋🏽 thank you for raising this issue. I just deployed a Next.js app from GitLab and was able to see Amplify autodetect it as an SSR app. Can you try adding a basic Next.js app and see if this problem occurs with any SSR app or just my-team/my-app?

**Comment by GiancarlosIO** [comment]
@hloriana sorry for the late response.
Yes, looks like the problem only happens if I use a repository that belongs to a gitlab team.
My repository is within a sub team in gitlab:
```
my-team/
   my-frontend-team/
      my-next-app/
```

**Comment by Thanzex** [comment]
Hi, we are getting the same poblem, one of our project hosted on Github works just fine, but the exact same repository duplicated in Gitlab is not recognized by Amplify as a Next.js SSR App.

**Comment by hloriana** [comment]
Hi @GiancarlosIO and @Thanzex apologies for the delay. We have not yet root caused why this behavior happens but it has been added to our backlog for prioritization. Can you try editing the build script (setting `baseDirectory: .next`)so that Amplify builds the app as SSR:

```
version: 1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```
Please let me know if this works for you while we root cause.
