### ISSUE TITLE
503 issues on every api route with Nextjs 11

### ISSUE THREAD

**Issue by newilu** [aws-amplify/amplify-hosting#2518]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

arn:aws:amplify:eu-west-1:114719936836:apps/dwyqpdfjrd4u5

### Region

eu-west-1

### Amplify Console feature

Backend builds, Build settings

### Describe the bug

After build every request to /api/* fails with 503 error. Locally with "next dev" and "next build && next start" commands running I'm not getting this issue.
I've tried to give my lambda&edge functions roles such as AdministratorAccess-Amplify and AdministratorAccess - not worked.
Tried to recreate whole app (including services connected like  cognito & appsync) with cli (amplify init) and manually from console - not worked.
Tried to switch nextjs version from 12 to 11 and node from 14 to 12 and back - not worked.
About 2 months ago all of my api routes worked fine, after it i left the project, there was no commits and rebuilds at all and when i'm back im seeing this issue.

### Expected behavior

Expected behavior was app works after build as fine as locally.

### Reproduction steps

Open the link https://development.d2959ba1d856u5.amplifyapp.com/ and open dev console so you can see 503 errors on "sites" and other /api/* routes.

### Build Settings

```yaml
version: 1
backend:
  phases:
    build:
      commands:
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - nvm use $VERSION_NODE_14
        - npm ci
    build:
      commands:
        - nvm use $VERSION_NODE_14
        - npm run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```
