### ISSUE TITLE
Pattern matching change in customHttp file

### ISSUE THREAD

**Issue by Weetbix** [aws-amplify/amplify-hosting#2525]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Amplify Console feature

Custom headers

### Describe the bug

The pattern matching behaviour seems to have changed in `customHttp.yml`.

We have an app deployed with with this file structure in the dist folder:
```
foo/foo.123456.html (123456 is a hash)
bar.js
```

And a custom http file like so:
```
customHeaders:
  - pattern: '**/*'
    headers:
      - key: 'x-some-header'
        value: 'true'

  - pattern: '/foo/*.html'
    headers:
      - key: 'x-some-header'
        value: 'false'
```

### Expected behavior

Previously, `**/*` would apply to all files, and the second pattern would match our `foo.[hash].html` file, so:
- `bar.js` would have the `x-some-header: true`
- `foo/foo.[hash].html` would have `x-some-header: false`

Through no change of our own, yesterday new deployments began to return the `**/*` headers for `foo.[hash].html`. It seems the `/foo/*.html` pattern no longer matches our file. Our `customHttp` has not changed, our amplify setting have not changed, the files names and directory structure have not changed.

To fix our issue and achieve the old behaviour, we had to change the second pattern to: `**/foo.*.html`, so for example:
```
customHeaders:
  - pattern: '**/*'
    headers:
      - key: 'x-some-header'
        value: 'true'

  - pattern: '**/foo.*.html'
    headers:
      - key: 'x-some-header'
        value: 'false'
```

This results in our expected behaviour written above.

### Reproduction steps

1. Create a deployment with the files as described above
2. Copy the first example customHttp file
3. Request `/foo/foo.123456.html` and inspect the headers
4. Notice the pattern is not matched, as `x-some-header` is true
5. Change the pattern to `*/foo.*.html` as in the second example customHttp file
6. Request `/foo/foo.123456.html` and inspect the headers
7. Notice that `x-some-header` is false. This was the behaviour for pattern 1 previously.
