### ISSUE TITLE
BUG - Amplify is not serving correct build

### ISSUE THREAD

**Issue by alastairayliffe** [aws-amplify/amplify-hosting#2540]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

df9v3hnihrz8x

### Region

us-east-1

### Amplify Console feature

Build settings

### Describe the bug

I have multiple git branches connected to the Amplify app ('local', 'develop', 'production').

develop and production don't appear to be updating with the latest build on either the amplify URL, or the domain name I've added.

### Expected behavior

When merging changes into my develop and production branches within Git, I was expecting amplify to update with the latest changes (post build).

### Reproduction steps

1. I created 2 amplify hosting environments in the same app, linking to 'develop' and 'production' branches in Git (with continual deployment).
3. I work on a branch called 'local', then merge into 'develop' and 'production' in git, expecting a rebuild, and then see the merged changes reflected when visiting the amplify URL.
4. These changes were not reflected.
5. Having tried the above, to check, I created another hosting environment based on the 'local' branch (with all the updates). When the build completed, the 'local' hosting environment displayed the latest.

So it looks the build in amplify does reflect the latest if/when created for the first time ('local' branch in point 5 above), but does not reflect changes when a build is triggered from a merged branch ('develop' and 'production').

### Build Settings

```yaml
version: 1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```
