### ISSUE TITLE
Backend build not working(timed out)

### ISSUE THREAD

**Issue by jothikannan89** [aws-amplify/amplify-hosting#2541]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d1yvu27h0gqugj

### Region

us-east-2

### Amplify Console feature

Backend builds

### Describe the bug

I have my frontend repo in BitBucket and using another amplify backend by `amplify pull` . In local the app is working fine. I am trying to host the frontend, So selected BitBukcet hosting environment and selected my repo and followed "[Automatic build-time generation of Amplify config](https://docs.aws.amazon.com/amplify/latest/userguide/amplify-config-autogeneration.html)
"  to deploy. 

**But it taking too much time for the deploy, after 30mins got Timeout issue**

### Expected behavior

As the Frontend is working fine in local, the deployment should work here. But the deployment is not happening for last 3 days.

### Reproduction steps

1.  Create react app
2. Pull existing amplify backend by using  amplify pull --appId ##### --envName dev
3. Push the code into Bitbucket repo
4. Host the repo in amplify frontend environment with Automatic build-time generation

### Build Settings

```yaml
version: 1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

### Additional information

![image](https://user-images.githubusercontent.com/28098883/150915160-e8067f67-b89a-4fc7-869b-4477fcd7f44e.png)
