### ISSUE TITLE
How to use docker compose in Amplify pipeline?

### ISSUE THREAD

**Issue by anastasiyamazheika** [aws-amplify/amplify-hosting#2550]
Hello! 
I want to launch my tests in docker in Amplify pipeline. 

Dockerfile:
```
FROM mcr.microsoft.com/playwright:v1.16.3-focal

RUN npx playwright install chrome
ENTRYPOINT [ "npx", "playwright", "test", "--config=tests/playwright.config.ts" ] 
```

docker-compose.yml

```
version: "3.4"
services:
  tests:
    volumes:
      - .:/code
    build: 
      context: .
      dockerfile: Dockerfile
    working_dir: /code
    ipc: host
```

amplify.yml
```
test:
      commands:
        - docker compose up
```

Amplify console

```
# Starting phase: test
[INFO]: # Executing command: docker compose up
[WARNING]: /codebuild/output/src983611118/src/{project_name}/tests.sh: line 29: docker: command not found
[INFO]: # Completed phase: test
[INFO]: ## Tests completed successfully
```

Did I forget something that docker isn't recognized?
Why error _docker: command not found_ is recognized only as **WARNING** instead of **ERROR**?
