### ISSUE TITLE
Build failure not communicated to GitHub pull request

### ISSUE THREAD

**Issue by aimeeu** [aws-amplify/amplify-hosting#2575]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

arn:aws:amplify:us-east-2:025179128306:apps/dqjx68ea5d3rv

### Region

us-east-2

### Amplify Console feature

Notifications

### Describe the bug

AWS Amplify integration with GitHub pull requests (AWS Amplify Console Web Preview)

I am evaluating AWS Amplify as a host for my company's static docs site, which uses Hugo. I deployed a static Hugo website called docsy-example, linked to my GitHub repo aimeeu/docsy-example.
I created a new branch and created a PR. The PR built successfully; web preview generated successfully.
I then deliberately created a commit that I know will not build and pushed to an existing PR to see how the Amplify-GitHub integration (AWS Amplify Console Web Preview) displays a build failure. The build failed in Amplify in under 2 minutes, but Amplify doesn't appear to have notified GitHub. The PR doesn't reflect the build failure. The  GitHub PR Conversation tab says "In progress - This check has started" and the Checks tab shows a process clock that keeps accruing time. The AWS Amplify Console Web Preview doesn't even time out (20+ hours and still "running").

Monday 14 February 2022 

![image](https://user-images.githubusercontent.com/26799583/153925568-22749b01-bfca-444b-a8d5-0b4c17bef842.png)

![image](https://user-images.githubusercontent.com/26799583/153925648-58d326b0-4cc1-409c-8b84-3a4360b9dd2a.png)

![image](https://user-images.githubusercontent.com/26799583/154082097-69d7692b-b9f5-43f9-b533-0d31aa654f2e.png)

### Expected behavior

I expect the GitHub PR Conversation UI to reflect the AWS Amplify Console Web Preview build failure.

### Reproduction steps

1. Deploy a static Hugo website
2. Create a new branch (ie git checkout -b new-branch)
3. Create a pull request that builds (ie, add a new page)
3. Push a commit that you know does not build (ie, add a new shortcode, use the shortcode on a page,  commit the page but don't commit the new shortcode file)

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm install
    build:
      commands:
        - wget https://github.com/gohugoio/hugo/releases/download/v${VERSION_HUGO}/hugo_extended_${VERSION_HUGO}_Linux-64bit.tar.gz
        - tar --overwrite -xf hugo_extended_${VERSION_HUGO}_Linux-64bit.tar.gz hugo
        - mv hugo /usr/bin/hugo
        - rm -rf hugo_extended_${VERSION_HUGO}_Linux-64bit.tar.gz
        - hugo version
        - cd themes/docsy && git submodule update -f --init && cd ../.. && hugo
  artifacts:
    baseDirectory: public
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

### Additional information

Possibly related to https://github.com/aws-amplify/amplify-console/issues/367
