### ISSUE TITLE
CI/CD failed because of invalid feature flag configuration during getting-started hands-on react tutorial

### ISSUE THREAD

**Issue by dominicfarr** [aws-amplify/amplify-hosting#2576]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

arn:aws:amplify:eu-west-2:324303852622:apps/d10ymk4rykovl9

### Region

eu-west-2

### Amplify Console feature

Backend builds

### Describe the bug

Following along with this blog tutorial [getting-started/hands-on/build-react-app-amplify-graphql](https://aws.amazon.com/getting-started/hands-on/build-react-app-amplify-graphql/ ) during Module 3: Add Authentication -> Set up CI/CD of the front end,  pushing local changes that triggers the remote build phase of the CI/CD, causes a failure in the build step. 

The error is associated with "feature flag configuration" configured in the cli.json file. 

I've attached the log file: [log.txt](https://github.com/aws-amplify/amplify-console/files/8043308/log.txt)

This maybe a duplicate or at the least related to https://github.com/aws-amplify/amplify-console/issues/2552 

### Expected behavior

The tutorial works without issues.
Adds auth module and building the backend via the amplify CI/CD completes without issue. 

### Reproduction steps

Follow the steps detailed in the tutorial https://aws.amazon.com/getting-started/hands-on/build-react-app-amplify-graphql/
At the last step in module 3 pushing changes that trigger a remote build via CI/CD the build step will fail due to invalid feature flag configuration. 

### Build Settings

```yaml
version: 1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplify --version
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - npm install
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

### Additional information

I have tried this with clean, nvm  managed, node versions 14, 15, 16, 17 
Local amplify cli 7.6.15
