### ISSUE TITLE
Github check never completes - reports build is in progress multiple hours after completion

### ISSUE THREAD

**Issue by noahgorstein** [aws-amplify/amplify-hosting#2598]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d3f0pg2w8qgvko

### Region

us-east-1

### Amplify Console feature

Previews

### Describe the bug

Amplify Github check never reports complete despite the build building successfully. Instead, we see that the build is in "In Progress" after 15 hours despite the build finishing successfully in ~8 minutes. 
![Screen Shot 2022-02-23 at 9 25 04 AM](https://user-images.githubusercontent.com/23270779/155338782-60dabd9a-b92c-45cc-9146-4bbb35c7b86e.png)

### Expected behavior

Amplify Github check should always report the actual status of the build or have some mechanism to restart the check besides pushing another commit. 

### Reproduction steps

1. Create a PR against a branch you have previews enabled for
2. Push a commit before the build completes for the original PR

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - bundle install
    build:
      commands:
        - bundle exec jekyll b
  artifacts:
    baseDirectory: _site
    files:
      - '**/*'
  cache:
    paths: []
```
