### ISSUE TITLE
Deploy phase failing suddenly Next.js

### ISSUE THREAD

**Issue by jericopulvera** [aws-amplify/amplify-hosting#2602]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d2ueuypv723ohy

### Region

ap-southeast-1

### Amplify Console feature

Not applicable

### Describe the bug

Build Failing in Deploy Phase

```
2022-02-24T08:37:47 [INFO]: Beginning deployment for application d2ueuypv723ohy, branch:master, buildId 0000000057
2022-02-24T08:37:47 [INFO]: Cannot find any generated SSR resources to deploy. If you intend for your app to be SSR, please check your app Service Role permissions. Otherwise, please check out our docs on how to setup your app to be detected as SSG (https://docs.aws.amazon.com/amplify/latest/userguide/server-side-rendering-amplify.html#deploy-nextjs-app)
2022-02-24T08:37:47 [ERROR]: {"code":"7","message":"No ssrResources.json file"}
```

### Expected behavior

Build should complete successfully

### Reproduction steps

Trigger rebuild via Git or Webhook

### Build Settings

```yaml
version: 1
frontend:
    phases:
        preBuild:
            commands: ['npm ci']
        build:
            commands: ['npm run build']
    artifacts:
        baseDirectory: out
        files:
            - '**/*'
    cache:
        paths:
            - 'node_modules/**/*'
    customHeaders:
        -
            pattern: '**/*'
            headers: [
                {
                    key: Strict-Transport-Security, value: 'max-age=31536000; includeSubDomains'}, {key: X-Frame-Options, value: SAMEORIGIN}, {key: X-XSS-Protection, value: '1; mode=block'}, {key: X-Content-Type-Options, value: nosniff},
                    {key: X-Robots-Tag, value: 'noindex' }
                ]
```

### Additional information

Framework detected is Next.js - SSG - Amplify
