### ISSUE TITLE
Deployments failing at Build phase suddenly

### ISSUE THREAD

**Issue by bilafish** [aws-amplify/amplify-hosting#2603]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d2ntjtvmevoo40

### Region

ap-southeast-1

### Amplify Console feature

Manual deploys

### Describe the bug

Builds for my React app is failing suddenly in the Build step when it was working fine previously.
![image](https://user-images.githubusercontent.com/16050230/155501926-e2863c92-97bb-4d07-84ca-20316c9ec624.png)
There was an error message shown `There was an issue connecting to your repo provider, click "Reconnect repository" in General Settings, and then try your build again.`.  I have tried reconnecting my repo provider, by deleting the existing webhooks on the Github repository and retrying the build but the same issue still happens. Also, I tried deleting the app and recreating a new AWS Amplify app connected to the same Github repository but the same issue still happens.

### Expected behavior

Builds should be successful.

### Reproduction steps

Trigger rebuild via Github push or Webhook

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - echo "I am running 🏃on $BUILD_ENV"
        - yarn run build
        - echo "Github Commit SHA1: $REACT_APP_VERSION"
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

**Comment by hloriana** [comment]
Hi @bilafish can you try running the build again to see if you're still running into this issue?

**Comment by bilafish** [comment]
Hi @hloriana, the builds seems to be working after I remove this command from my build yaml: `echo "Github Commit SHA1: $REACT_APP_VERSION"`.

**Comment by Narrator** [comment]
@bilafish Please wrap your command within single quotes like so:

```
        - 'echo "Github Commit SHA1: $REACT_APP_VERSION"'
```
The `:` character in the YAML needs to be escaped or quoted. You can check how your YAML file is parsed using this online tool: https://jsonformatter.org/yaml-to-json.

**Comment by bilafish** [comment]
> @bilafish Please wrap your command within single quotes like so:
> 
> ```
>         - 'echo "Github Commit SHA1: $REACT_APP_VERSION"'
> ```
> 
> The `:` character in the YAML needs to be escaped or quoted. You can check how your YAML file is parsed using this online tool: https://jsonformatter.org/yaml-to-json.

@Narrator After modifying my build.yml as above, the builds are failing now with error: `!!! CustomerError: Base Directory not specified for artifacts, unable to create build artifact.` in the build log.

**Comment by Narrator** [comment]
@bilafish Your build spec is malformed. This is the build spec you have right now:
```
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - echo "I am running 🏃on ${BUILD_ENV}"
        - yarn run build
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

`baseDirectory` and `files` should not be under `phases`. They should be under `artifacts`. Here's the corrected YAML:
```
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - 'echo "I am running 🏃on ${BUILD_ENV}"'
        - yarn run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```
