### ISSUE TITLE
SSR Preview Deployment Resources Not Being Deleted After PR Merge/Close

### ISSUE THREAD

**Issue by EvilTeliportist** [aws-amplify/amplify-hosting#2605]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d2k26qrgfqnjn5

### Region

us-east-1

### Amplify Console feature

Previews

### Describe the bug

Basically a duplicate of #277 and #2123.

I currently have a React/NextJS/Amplify app running that has built up tons of lambdas, s3 buckets, and cloudfront distros due to previews being opened/merged. There resources are not being deleted after the MR is closed or merged.

For reference we're using GitLab at my team.

### Expected behavior

The resources associated with the MRs should be deleted when the MR is closed/merged.

### Reproduction steps

1. Make a repo with GitLab.
2. Setup a basic NextJS React app.
3. Setup Amplify with previews.
4. Open a MR, make sure preview is deployed.
5. Close or merge the MR.
Resources associated with the MR have not been deleted.

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```
