### ISSUE TITLE
"Successful" (4/4 green check marks) deployment leads to a 404 error on the cname 

### ISSUE THREAD

**Issue by kwong70** [aws-amplify/amplify-hosting#2664]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

dzgp6n3gqn46s

### Region

us-east-1

### Amplify Hosting feature

Build settings

### Describe the bug

- attempting to run a react frontend along with the next frame work 
- works fine locally on localhost:port 
- Have placed the build/deploy cli in the amplify.yml file 
- Problem: 
- amplify goes through all four steps: provision, build, deploy and verify with all green checks and no errors in the logs
- deployment is successful but when trying to hit the cname (given by amplify), 404 error not found 
- as if npm start is not executed or any server is being started

### Expected behavior

- To see our front page from our cname

### Reproduction steps

1. Must commit changes to the attached dev branch
2. Or can redeploy old version

### Build Settings

```yaml
version: 1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - npm install
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
```

### Additional information

kendallwong1@gmail.com
