### ISSUE TITLE
Deploy fails with error "No ssrResources.json file" when using aws_cli "aws amplify create-app"

### ISSUE THREAD

**Issue by nicholasrobertson** [aws-amplify/amplify-hosting#2669]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d3fak2tvugfhw6

### Region

ap-southeast-2

### Amplify Hosting feature

Manual deploys, Monorepo

### Describe the bug

When using the AWS_CLI to create a new Next.JS SSR application using in the AWS CLI, the deploy phase produces the following error.

```
2022-03-27T01:09:40 [INFO]: Beginning deployment for application d3fak2tvugfhw6, branch:main, buildId 0000000001
2022-03-27T01:09:40 [INFO]: Cannot find any generated SSR resources to deploy. If you intend for your app to be SSR, please check your app Service Role permissions. Otherwise, please check out our docs on how to setup your app to be detected as SSG (https://docs.aws.amazon.com/amplify/latest/userguide/server-side-rendering-amplify.html#deploy-nextjs-app)
2022-03-27T01:09:40 [ERROR]: {"code":"7","message":"No ssrResources.json file"}
```

### Expected behavior

The deploy should succeed with no errors

### Reproduction steps

1. Run the following command
```
aws amplify create-app --name "examplename" --repository "https://github.com/examplerepo" --platform "WEB_DYNAMIC" --iam-service-role-arn "arn:aws:iam::examplerolearn" --access-token "ghp_EXAMPLEACCESSTOKEN" --enable-branch-auto-build --enable-branch-auto-deletion --build-spec file://build.yml --enable-auto-branch-creation --auto-branch-creation-patterns "*" --auto-branch-creation-config file://auto-branch-creation-config.json
```
**file://auto-branch-creation-config.json**
```
{
    "stage": "PRODUCTION",
    "framework": "WEB_DYNAMIC",
    "enableAutoBuild": true,
    "enablePerformanceMode": false,
    "buildSpec": "version: 1\r\n    applications:\r\n      - frontend:\r\n          phases:\r\n            preBuild:\r\n              commands:\r\n                - npm ci\r\n            build:\r\n              commands:\r\n                - npm run build\r\n          artifacts:\r\n            baseDirectory: .next\r\n            files:\r\n              - '**\/*'\r\n          cache:\r\n            paths:\r\n              - node_modules\/**\/*\r\n        appRoot: unit-app",
    "enablePullRequestPreview": false
}
```

2. Navigate to the aws console
3. Inspect the new application
4. Connect to a branch
5. Save and deploy
6. Wait and Observe Error

### Build Settings

```yaml
version: 1
applications:
  - frontend:
      phases:
        preBuild:
          commands:
            - npm ci
        build:
          commands:
            - npm run build
      artifacts:
        baseDirectory: .next
        files:
          - '**/*'
      cache:
        paths:
          - node_modules/**/*
    appRoot: unit-app
```

### Additional information

When the application is created via the AWS console there are no error's, and the required Cloudfront and s3 resources are provisioned correctly on the first build.

Monorepo
**package.json**
```
{

  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },

  "dependencies": {
    "next": "^11.1.4",
    "react": "^17.0.2",
    "react-dom": "^17.0.2"
  }
}
```

**Comment by nicholasrobertson** [comment]
I managed to get this to build with no error just now.

I'm not exactly sure of the root cause however after running the `get-app` command and comparing my manually created app vs the cli created, 

- I made some changes to the auto-build/create settings, and 
- I also added some odd looking environment variables, and
- I added a new line to the build.yml but I doubt that did much.

As expected my the initial build went away and created the cloud-front resources successfully.

**AWS Cli**
```
aws amplify create-app --name "cli-app-5" --repository "https://github.com/examplerepopath" --platform "WEB_DYNAMIC" --iam-service-role-arn "arn:aws:iam::exampleiamrolearn" --access-token "ghp_EXAMPLEACCESSTOKEN" --environment-variables file://environmentVariables.json --no-enable-branch-auto-build --no-enable-branch-auto-deletion --build-spec file://build.yml --no-enable-auto-branch-creation
```

**environmentVariables.json**
```
{
    "AMPLIFY_DIFF_DEPLOY": "false",
    "AMPLIFY_MONOREPO_APP_ROOT": "unit-app",
    "_LIVE_UPDATES": "[{\"pkg\":\"next-version\",\"type\":\"internal\",\"version\":\"latest\"}]"
}
```

**build.yml **
```
version: 1
applications:
  - frontend:
      phases:
        preBuild:
          commands:
            - npm ci
        build:
          commands:
            - npm run build
      artifacts:
        baseDirectory: .next
        files:
          - '**/*'
      cache:
        paths:
          - node_modules/**/*
    appRoot: unit-app

```

Hope this helps someone <3
