### ISSUE TITLE
PR Preview env can't be created with env variables

### ISSUE THREAD

**Issue by vojtech-simko** [aws-amplify/amplify-hosting#2706]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d3pwsdrqmxpguf

### Region

eu-west-2

### Amplify Hosting feature

Backend builds, Environment variables

### Describe the bug

I'm using the `amplifyPush --simple` command to build/create my backend env for Preview environments. 

The build fails because of env variables and `--yes` flag - [known issue](https://docs.amplify.aws/cli/function/env-vars/#multi-environment-flows) 

`CREATE_FAILED               functiongetOpenViduToken             AWS::CloudFormation::Stack Tue Apr 19 2022 09:25:45 GMT+0000 (Coordinated Universal Time) Parameters: [openviduUrl] must have values` 

However, according to documentation to fix the issue you have to checkout the env and push it manually from local machine.
1. I copy the command from Amplify console `amplify pull --appId d3pwsdrqmxpguf --envName prcjb`
2. an empty env is pulled from cloud
3. I can't update the function nor push it back to cloud (because there're no categories)

### Expected behavior

I'd be great if the `amplifyPush --simple` (amplify push -y) command did carry over the env variables and secrets from target or current env without prompting).

Also I don't know why the failing env is empty why I pull it. Without it there's no way how to fix the env variables.

### Reproduction steps

1. Create lambda function that uses some env variable.
2. Define value for current environment and push to cloud - check if value is included in `team-provider-info.json`
3. Setup PR Previews for current branch in Amplify Console - **Create new backend environment for every Pull Request**
4. Create new branch from current branch
5. Make some changes, add dummy file etc.
6. Push changes to remote and create PR for the new branch.
7. PR env build should fail - try to pull the env from cloud.

### Build Settings

```yaml
version: 1
backend:
    phases:
        build:
            commands:
                - amplifyPush -e "${AWS_BRANCH}" --simple
frontend:
    phases:
        preBuild:
            commands:
                - npm ci
        build:
            commands:
                - npm run build-prod
    artifacts:
        baseDirectory: dist/stardio-pro
        files:
            - "**/*"
    cache:
        paths:
            - node_modules/**/*
```
