### ISSUE TITLE
SSR Build failed due to RequestEntityTooLargeException

### ISSUE THREAD

**Issue by hung1e** [aws-amplify/amplify-hosting#2707]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

dpoimtt9hpxe2

### Region

eu-west-2

### Amplify Hosting feature

Backend builds

### Describe the bug

My build is succeed in the local environment but failed on Amplify with the error:
Starting SSR Build...
RequestEntityTooLargeException: Request must be smaller than 69905067 bytes for the CreateFunction operation

I checked my application and it's only 30Mb in size. The previous build was succeeded.

### Expected behavior

I'd expect the build is success as our previous builds. Or if there's any workaround that can help us deploying the change.

### Reproduction steps

1. Commit the change to Github
2. The Amplify build was trigger automatically
3. Build failed with the error "Starting SSR Build...
4
![Uploading image.png…]()

### Build Settings

```yaml
version: 1
applications:
  - frontend:
      phases:
        preBuild:
          commands:
            - yarn install
        build:
          commands:
            - yarn run build
      artifacts:
        baseDirectory: .next
        files:
          - '**/*'
      cache:
        paths:
          - node_modules/**/*
          
    appRoot: Source/web
```
