### ISSUE TITLE
Next.js build process hanging

### ISSUE THREAD

**Issue by chris-bloomfield** [aws-amplify/amplify-hosting#2708]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d1pv7ibdadvelv

### Region

eu-west-2

### Amplify Hosting feature

Not applicable

### Describe the bug

The frontend build process for Next.js apps appears to be hanging whenever I trigger a deployment.  

It gets as far as:

2022-04-21T11:12:50.928Z [WARNING]: warn  - No ESLint configuration detected. Run next lint to begin setup
2022-04-21T11:12:50.934Z [INFO]: info  - Creating an optimized production build...
2022-04-21T11:12:55.062Z [INFO]: info  - Compiled successfully

Then just stops responding until I have to manually cancel the build.

### Expected behavior

Build should continue on collecting page data / generating static pages / finalizing page optimization... etc.

### Reproduction steps

I am seeing this issue with the default Next.js starter app, i.e:

 - `npx create-next-app xxxx`
 - Push to a repo
 - Link Amplify hosting to the repo with the default settings.

Have also tried with versions 9, 10 and 11 of Next.js but getting the same result.

### Build Settings

```yaml
(default auto-generated build settings)

version: 1
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```
