### ISSUE TITLE
Build fails from second time with enabled cache 

### ISSUE THREAD

**Issue by entest-hai** [aws-amplify/amplify-hosting#2712]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d2axh23o1z3uo

### Region

ap-southeast-1

### Amplify Hosting feature

Build settings

### Describe the bug

The first time, it is built successfully. However, from the second time, without code change, it is failed. 

I noticed the build setting with enabled cache 
```
cache:
    paths:
      - node_modules/**/*
```

When I remove the cache from the build setting, it build successfully but very very slow. 

### Expected behavior

It should be built successfully from second time when there is no code change. 

### Reproduction steps

[Here is my repository](https://github.com/entest-hai/aws-amplify-ui-nextjs)

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - yarn add --dev typescript
        - npm install
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*

```
```


### Additional information

_No response_
