### ISSUE TITLE
Deploy failed with "No ssrResources.json file" message

### ISSUE THREAD

**Issue by weiw05** [aws-amplify/amplify-hosting#2721]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d3uf7no1t1cjcs

### Region

us-east-1

### Describe the bug

I have a next.js SSR app hosted on Amplify.  The deployment stage is failing with error "Cannot find any generated SSR resources to deploy": [ERROR]: {"code":"7","message":"No ssrResources.json file"}.  
I have tried several things to no avail:
-  followed [the instructions](https://docs.aws.amazon.com/amplify/latest/userguide/server-side-rendering-amplify.html#deploy-nextjs-app) and everything seems correctly configured for SSR, including the new service role.  
- deleted and re-created the Amplify app
- downgraded Next to version 11

### Expected behavior

Amplify correctly detecting SSR app and deploying

### Reproduction steps

1. click the "redeploy this version" button on the build page

### Build Settings

```yaml
frontend:
      phases:
        preBuild:
          commands:
            - npm ci
        build:
          commands:
            - npm run build
      artifacts:
        baseDirectory: .next
        files:
          - '**/*'
      cache:
        paths:
          - node_modules/**/*
```
