### ISSUE TITLE
Unable to connect to Github

### ISSUE THREAD

**Issue by jtmthf** [aws-amplify/amplify-hosting#2733]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d1tq1tb6wa1mud

### Region

us-east-1

### Amplify Hosting feature

Build settings

### Describe the bug

In deploying a new Nextjs application, I am unable to get Amplify to connect to Github. The amplify deployment is done with CDK and uses the newer `accessToken` authentication with a PAT that has the `admin:repo_hook` scope.

Upon clicking "Reconnect repository", the "Github Reconnect: Install and authorize GitHub App" page refreshes repeatedly until arriving on the Github authorize app page. At this point Github will give a warning that excessive authorization attempts have been made. Repeating this multiple times will result in a secondary rate limit being applied by Github that will lock out authentication attempts for several hours.

### Expected behavior

I had deployed this app before in 2021 with a different AWS account have been able to successfully deploy the application that way. I would expect to see Amplify connect to Github whether using the legacy OAuthToken or accessToken approach.

### Reproduction steps

The application is deployed using the below CDK code.

```ts
const app = new aws_amplify.CfnApp(this, 'CfnAmplifyApp', {
  accessToken: secretsmanager.Secret.fromSecretNameV2(
    this,
    'GithubToken',
    'path/to/github-token',
  ).secretValue.toString(),
  repository: 'https://github.com/org/name',
  iamServiceRole: this.role.roleArn,
  environmentVariables: Object.entries(environmentVariables).map(
    ([name, value]) => ({ name, value }),
  ),
  buildSpec: codebuild.BuildSpec.fromObjectToYaml({
    version: '1.0',
    applications: [
      {
        appRoot: 'apps/renderer',
        frontend: {
          phases: {
            preBuild: {
              commands: [
                'nvm install',
                'cd ../..',
                'corepack enable',
                'pnpm install',
              ],
            },
            build: {
              commands: ['pnpm build', 'cd apps/renderer'],
            },
          },
          artifacts: {
            baseDirectory: '.next',
            files: ['**/*'],
          },
          cache: {
            paths: ['~/.pnpm-state/**/*', '.next/cache/**/*'],
          },
        },
      },
    ],
  }).toBuildSpec(),
});

new aws_amplify.CfnBranch(this, 'Master', {
  appId: app.attrAppId,
  branchName: 'master',
});
```

After running `cdk deploy` it can be seen that the project is not connected.

<img width="1046" alt="Screen Shot 2022-05-03 at 4 32 13 PM" src="https://user-images.githubusercontent.com/8162598/166569969-565adc3e-3faa-42db-9209-2622997c2086.png">

This page then refreshes multiple times 

<img width="708" alt="Screen Shot 2022-05-03 at 4 33 13 PM" src="https://user-images.githubusercontent.com/8162598/166570104-425a8b49-d2e9-44ab-8614-b722b3cd1bcc.png">

After which I am taken to the app authorization screen in which it appears the app has already been authorized. This then returns to the previous screen which continues to refresh repeatedly and return to Github in an endless loop.

<img width="853" alt="Screen Shot 2022-05-03 at 4 33 58 PM" src="https://user-images.githubusercontent.com/8162598/166570246-1c58bd4c-03cb-485b-ae18-874c8e3d1714.png">

### Build Settings

```yaml
version: "1.0"
applications:
  - appRoot: apps/renderer
    frontend:
      phases:
        preBuild:
          commands:
            - nvm install
            - cd ../..
            - corepack enable
            - pnpm install
        build:
          commands:
            - pnpm build
            - cd apps/renderer
      artifacts:
        baseDirectory: .next
        files:
          - "**/*"
      cache:
        paths:
          - ~/.pnpm-state/**/*
          - .next/cache/**/*
```

### Additional information

We have this app deployed in another AWS account and it continues to work. The issue only arises when we try to deploy in a new account.
