### ISSUE TITLE
nuxt build fails in "previews" 

### ISSUE THREAD

**Issue by manuel-84** [aws-amplify/amplify-hosting#2765]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

dl4hgzkr4l6xx

### Region

eu-central-1

### Amplify Hosting feature

Build settings, Custom builds

### Describe the bug

we have a nuxt app building correctly except for pull requests (preview apps - branch "feature"), in this case the build fails 

```
2022-05-24T09:57:53.316Z [INFO]: > memento@1.0.0 generate /codebuild/output/src374040070/src/bflows-frontend
                                 > nuxt generate
2022-05-24T09:57:53.320Z [WARNING]: sh: nuxt: command not found
```

### Expected behavior

the build of "feature" branch should run  normally like in other branches, the nuxt command should be found

### Reproduction steps

trigger a build for pr/review app

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - nvm install 12.13.0
        - npm ci
    build:
      commands:
        - npm run generate
  artifacts:
    baseDirectory: dist
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```
