### ISSUE TITLE
Build Time Out Error: got stuck at Frontend while running gulpfile.js

### ISSUE THREAD

**Issue by vinodvarma24** [aws-amplify/amplify-hosting#2769]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d16dy5mg6z0e38

### Region

us-east-1

### Amplify Hosting feature

Build settings

### Describe the bug

I moved from manual deployment to automatic CI/CD with my Github repo, In manual deployment, it was working with out any issues. After connecting the main repo and starting the build, it's not getting completed at the Frontend provision. 

I'm getting the build timeout error with 30 min default time setting and then increasing it to 120 min in environmental variables override. It's still taking so much time. 

On my local machine: it just takes <5 min to build without any errors. 

![Screen Shot 2022-05-26 at 8 16 14 AM](https://user-images.githubusercontent.com/20860716/170575663-7075841e-f881-4500-bd2c-9ed7b514e9c3.png)
![Screen Shot 2022-05-26 at 8 15 46 AM](https://user-images.githubusercontent.com/20860716/170575698-0c1a765f-b866-43f8-945a-e31fd06617f8.png)
![Screen Shot 2022-05-26 at 1 36 25 PM](https://user-images.githubusercontent.com/20860716/170575846-4b4a9cfa-d554-4854-bbf9-68db02bf34ec.png)

### Expected behavior

If there are no errors, it should move to the next steps in the build stage and I should be able to use the app in production. 

### Reproduction steps

Amplify CLI version on my local: 8.3.0
Used the same version in build settings also.

### Build Settings

```yaml
version: 1
env:
  variables:
    VERSION_AMPLIFY: 8.3.0
backend:
  phases:
    preBuild:
      commands:
        - npm i -g @aws-amplify/cli@${VERSION_AMPLIFY}
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn run build
        - node ./node_modules/gulp/bin/gulp.js
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

### Additional information

Please help, this is a production app, it's been down for many hours now. I screwed it up for the sake of CI/CD optimization.
