### ISSUE TITLE
Amplify Java runtime function build and deploy

### ISSUE THREAD

**Issue by pjsundhar** [aws-amplify/amplify-hosting#2776]
Running Amplify build with Gradle 7.x and Java_11 runtime version. 

```
Amplify ID : dxpkt19g6tfmo
Region : us-east-1
```
Build docker is missing Java runtime and gradle as defaults in provisioning. 

**Getting the following error**

> Unable to find Java version >=11 on the path
> Unable to find Gradle version >=5
> 

Question
1. Is there a way to use the gradle wrapper instead of gradle as build option in java runtime template
2. I can add few yum installs in amplify.yml but prefer them in provisioning dockerfile image itself. Is that configurable ?

```
backend:
  phases:
    build:
      commands:
        - sudo yum install java-11-amazon-corretto-headless
        - wget https://services.gradle.org/distributions/gradle-7.4.2-bin.zip -P /tmp
        - unzip -d /gradle /tmp/gradle-*.zip
        - mv /gradle /usr/bin/gradle
        - echo export PATH="/usr/bin/gradle/gradle-7.4.2/bin:$PATH" >> ~/.bashrc
        - gradle --version
        - amplifyPush --simple
```
