### ISSUE TITLE
Incorrect env variables for nextjs

### ISSUE THREAD

**Issue by newilu** [aws-amplify/amplify-hosting#2785]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d61j5m72chkto

### Region

eu-west-1

### Amplify Hosting feature

Environment variables

### Describe the bug

I'm using next-auth lib for authentication and that lib requires NEXTAUTH_URL. I'm setting it in env variables and initing it in code as app.storehero.ai but after build it's localhost:3000. It's not a problem with next-auth because locally all works fine and until previous build issues happened all worked just fine.

### Expected behavior

expected that nextauth_url will be set as in the env vars.

### Reproduction steps

go to https://app.storehero.ai/
register
go to /onboarding route
go to connect google analytics screen
try to authenticate your account
it will redirect you to localhost but should redirect back to app.storehero.ai

### Build Settings

```yaml
version: 1
backend:
  phases:
    build:
      commands:
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - nvm use $VERSION_NODE_16
        - yarn install --frozen-lockfile
    build:
      commands:
        - nvm use $VERSION_NODE_16
        - yarn build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```
