### ISSUE TITLE
Angular build with Node 14 stuck more than hour before timeout 

### ISSUE THREAD

**Issue by jpelaez-23blocks** [aws-amplify/amplify-hosting#2790]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

arn:aws:amplify:us-east-2:106337219444:apps/d23gzii0ai16ea

### Region

us-east-2

### Amplify Hosting feature

Not applicable

### Describe the bug

the last couple of days not front end build was successful, all the angular builds we have are failing after 30 or even 60 minutes running mostly after  ✔ ES5 bundle generation complete., sometimes even on the step 
 ES5 bundle generation complete.
- Copying assets...
environment variable to increase memory was added, this builds were working fine (17 to 19 minutes build) before. 

### Expected behavior

Build should be completed in less than 30 minutes

### Reproduction steps

Add any angular project,  use this script
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm install -g @angular/cli
        - npm ci
    build:
      commands:
        - ng build --configuration=stage --prod --build-optimizer
  artifacts:
    baseDirectory: dist/web-container
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*

node 14, and the build will get stuck and never complete deployment. 

### Build Settings

```yaml
60 minutes, Default Linux 2 machine, Node 14. 
Angular 9 to 11.
```

**Comment by jhuamanchumo** [comment]
Any updates, I'm having same issue with Node 14 / 16

**Comment by Jay2113** [comment]
@jpelaez-23blocks @jhuamanchumo Kindly downgrade your global install of the Angular CLI to v13.3.7 within your buildSpec as follows:
```
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm install -g @angular/cli@13.3.7
        - npm ci
    build:
      commands:
        - ng build --configuration=stage --prod --build-optimizer
  artifacts:
    baseDirectory: dist/web-container
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```
