### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by pull-task** [aws-amplify/amplify-hosting#2799]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d76urbu77joch

### Region

us-east-1

### Amplify Hosting feature

Backend builds, Build settings, Custom builds

### Describe the bug

My front-end react project, which builds fine on my local macOS, has recently started failing with an error on amplify-hosting.

Now, during the execution of the npm ci clean install, fsevents, which is a node package specifically for macOS, errors saying it isn't supported on the amazon linux x64 build os.

[INFO]: # Executing command: npm ci
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin"} (current: {"os":"linux","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  undefined
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64
[ERROR]: !!! Build failed

### Expected behavior

Build succeeds

### Reproduction steps

commit to branch that has Amplify CI Builds configured.

### Build Settings

```yaml
version: 1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    # IMPORTANT - Please verify your build output directory
    baseDirectory: /build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```
