### ISSUE TITLE
Amplify Frontend Build SSR Performance

### ISSUE THREAD

**Issue by jd-carroll** [aws-amplify/amplify-hosting#2801]
I created a Next.JS app using their `create-next-app` tool as a starting point for my Amplify journey.  I then followed the steps to:
```
$ amplify init
$ amplify add hosting
```
I'm also using a monorepo, so I did everything around that, and the build succeeds.  

**However, the build consistently takes 10min+ to complete for what should be the most basic of "Hello World" apps.  I've narrowed it down to the SSR deploy part of the build.  Here is an output from my logs:**

```
2022-06-10T22:17:02.337Z [INFO]: # Executing command: echo "PreBuild Dir:" /codebuild/output/src1234/src/my-monorepo/client-sites/my-app
...
2022-06-10T22:18:16.828Z [INFO]: Build Dir: /codebuild/output/src1234/src/my-monorepo/client-sites/my-app
2022-06-10T22:18:16.829Z [INFO]: # Executing command: npx lerna run build --scope '@client-sites/my-app'
...
2022-06-10T22:18:36.783Z [INFO]: @client-sites/my-app: Done in 11.10s.
2022-06-10T22:18:37.517Z [INFO]: Starting SSR Build...
2022-06-10T22:24:04.161Z [INFO]: SSR Build Complete.
```

**As you can see, the time between `Starting SSR Build...` and `SSR Build Complete` is 6min+.  Can this performance be optimized at all?**

I have two apps in my monorepo, one with an `api` folder and one without.  However, neither app has a "backend" configured in the Amplify configuration.  And both the `my-app` and `my-app-no-api` versions take 10min+.

Additionally, since this is the most basic template app from Next.JS, they don't even use SSR features.  (However, the "build" command in the package.json only contains `next build` so Amplify should treat them both as SSR's and not SSG's)

Below is a copy of the `amplify.yml` at the root of my repo.  

**Not sure if this is the right forum, but any assistance would be greatly appreciated!**

And one more, somewhat related question... I am using yarn workspaces for my package management.  Is the caching for the `node_modules/**/*` correct in the build config?  (Would it actually capture the packages which are contained in the node_modules folder two levels higher?)

```
version: 1
applications:
  - appRoot: client-sites/my-app
    env:
      variables:
        key: value
    frontend:
      phases:
        preBuild:
          commands:
            - echo "PreBuild Dir:" $(pwd)
            - yarn install
            - npx lerna bootstrap
        build:
          commands:
            - echo "Build Dir:" $(pwd)
            - npx lerna run build --scope '@client-sites/my-app'
      artifacts:
        baseDirectory: '.next'
        files:
          - '**/*'
      cache:
        paths:
          - 'node_modules/**/*'
          - '.next/**/*'

  - appRoot: client-sites/my-app-no-api
    env:
      variables:
        key: value
    frontend:
      phases:
        preBuild:
          commands:
            - echo "PreBuild Dir:" $(pwd)
            - yarn install
            - npx lerna bootstrap
        build:
          commands:
            - echo "Build Dir:" $(pwd)
            - npx lerna run build --scope '@client-sites/my-app-no-api'
      artifacts:
        baseDirectory: '.next'
        files:
          - '**/*'
      cache:
        paths:
          - 'node_modules/**/*'
          - '.next/**/*'
```
