### ISSUE TITLE
Deploy stage fails with "[ERROR]: Failed to deploy"

### ISSUE THREAD

**Issue by mathewr94** [aws-amplify/amplify-hosting#2805]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

dm6pmstqyhyh5

### Region

eu-west-2

### Amplify Hosting feature

Build settings, Previews

### Describe the bug

The Provision, Build and Test phases of our previews are all passing for pr-15 which needs to go into Master; I can confirm that the tests pass because I can download the test artifacts from the preview and see the Playwright traces of exactly what happened when the tests ran. The issue is, when the Deploy stage starts, it immediately fails and the only thing that gets logged is:
```
2022-06-13T08:40:25 [INFO]: Starting Deployment
2022-06-13T08:40:25 [ERROR]: Failed to deploy
```

I've searched for a resolution but all I could find of any relevance really was [this issue](https://github.com/aws-amplify/amplify-hosting/issues/115) which was supposedly resolved and wasn't down to the reporter's human error, so it doesn't help us much. 

### Expected behavior

The deploy stage should pass, allowing the verification stage to begin.

### Reproduction steps

Not really reproducible for anyone not working on our specific project. For us, we simply attempt to redeploy pr-15. The likelihood is, if there's any human error, it's in the amplify.yml file so please take a look and see if there's anything wrong there. 

### Build Settings

```yaml
version: 1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    # IMPORTANT - Please verify your build output directory
    baseDirectory: /dist
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
test:
  phases:
    preTest:
      commands: 
        - echo fs.inotify.max_user_watches=65536 | tee -a /etc/sysctl.conf && sysctl -p
        - npm ci
        - npm install pm2
        - npx pm2 start npm -- start
        - npm i -D @playwright/test
        - npx playwright install
    test:
      commands:
        - npx playwright test 
    postTest:
      commands:
        - npx pm2 kill
  artifacts:
    baseDirectory: /test-results
    files:
      - '**/*'
```
