### ISSUE TITLE
Build Error with Amplify CI/CD pipeline deploying

### ISSUE THREAD

**Issue by M-Harty21** [aws-amplify/amplify-hosting#2811]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

https://us-east-1.console.aws.amazon.com/amplify/home?region=us-east-1#/d3uha8rjehvj3x

### Region

us-east-1

### Amplify Hosting feature

Build settings

### Describe the bug

When I deploy the backend to my main branch, this errors come in the pipeline build for the ci/cd. For some reason the backend build when we specified that we do not want the backend to build. This keeps happening and we don't have any problems with our backend env, we even injected the amplify.yml to have the frontend only build and it seems to be building the backend. Please help          

                      at ensureAmplifyMetaFrontendConfig (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/extensions/amplify-helpers/on-category-outputs-change.js:101:60)
                                 at AmplifyToolkit.onCategoryOutputsChange [as _onCategoryOutputsChange] (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/extensions/amplify-helpers/on-category-outputs-change.js:41:9)
                                 at initializeEnv (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/initialize-env.js:83:31)
                                 at async onSuccess (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/attach-backend.js:94:9)
                                 at async attachBackend (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/attach-backend.js:45:9)
                                 at async Object.run (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/commands/pull.js:68:9)
                                 at async Object.executeAmplifyCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/index.js:292:9)
                                 at async executePluginModuleCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:142:5)
                                 at async executeCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:40:9)
                                 at async Object.run (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/index.js:165:13)
2022-06-16T10:37:46.563Z [ERROR]: !!! Build failed
2022-06-16T10:37:46.564Z [ERROR]: !!! Non-Zero Exit Code detected

### Expected behavior

Expected: To deploy the frontend only to our Amplify environment 

### Reproduction steps

1. Commit changed to branch
2. merge into main
3. breaks on build -> backend builds and fails

### Build Settings

```yaml
version: 1
applications:
  - frontend:
      phases:
        preBuild:
          commands:
            - npm ci
        build:
          commands:
            - npm run build
      artifacts:
        baseDirectory: dist/rabbithole
        files:
          - '**/*'
      cache:
        paths:
          - node_modules/**/*
    appRoot: rabbithole
```
