### ISSUE TITLE
Previews don't work with Next.js + frontend only

### ISSUE THREAD

**Issue by kylekirkby** [aws-amplify/amplify-hosting#2822]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d3aqki25vehjct

### Region

us-east-1

### Amplify Hosting feature

Previews

### Describe the bug

I've been attempting to setup frontend-only Previews for our Next.js app. Clicking "Deploy this version" in the Amplify Hosting console works for a specific branch however, when submitting a PR, Amplify Hosting attempts to either build the backend or cannot find the `aws-exports.js` file. 

```yml
version: 1
env:
    variables:
        AMPLIFY_BACKEND_PULL_ONLY: true
backend:
    phases:
        build:
            commands:
                - '# Execute Amplify CLI with the helper script...'
                - amplifyPush --simple
frontend:
    phases:
        preBuild:
            commands:
                - yarn install
                - export NODE_OPTIONS="--max-old-space-size=5120"
        build:
            commands:
                - yarn run build
    artifacts:
        baseDirectory: .next
        files:
            - '**/*'
    cache:
        paths:
            - node_modules/**/*


```

### Expected behavior

In the documentation for Previews, there is a section that looks promising by stating:

```
For full-stack applications do one of the following:

Choose, Create new backend environment for every Pull Request. This option enables you to test changes without impacting production.

Choose Point all Pull Requests for this branch to an existing environment.
```

These options do not exist. Have they been removed?

I've made sure that the "Enable full-stack deployments" option is off.

![Screenshot from 2022-06-22 11-30-15](https://user-images.githubusercontent.com/4564433/175008088-7822c321-fb56-4a03-b321-f10b6c6daa0f.png)

I've tried removing this section:

```
backend:
    phases:
        build:
            commands:
                - '# Execute Amplify CLI with the helper script...'
                - amplifyPush --simple
```
but this results in the `aws-exports.js` not found issue...

If I include the backend section, this error occurs:

```
2022-06-22T08:24:34.270Z [INFO]: ----- 🪝 pre-push execution start -----
2022-06-22T08:24:34.316Z [INFO]: TypeError: Cannot read property 'envName' of undefined
                                 at updateAppSyncAPIAdminRoles (/codebuild/output/src801838739/src/------------/amplify/hooks/pre-push.js:11:38)
```
The above error may be something different entirely from the issue I'm facing whereby the `pre-push` hook doesn't receive the correct variables...

Here is the relevant section of code in my pre-push script.
```
const parameters = JSON.parse(fs.readFileSync(0, { encoding: 'utf8' }));
/**
 * Updates the custom-roles.json file in AppSync API backend folder.
 */
const updateAppSyncAPIAdminRoles = () => {
    try {
        // Get the amplify environment
        const amplifyEnvironment = parameters.data.amplify.environment;
        const envName = amplifyEnvironment.envName;
```

### Reproduction steps

1. Setup Previews for a Next.js site that also has an `amplify` backend folder. 
2. Create a PR.
3. See that the PR fails and tries to create the backend, or does not include the `aws-exports.js` file.

### Build Settings

```yaml
version: 1
env:
    variables:
        AMPLIFY_BACKEND_PULL_ONLY: true
backend:
    phases:
        build:
            commands:
                - '# Execute Amplify CLI with the helper script...'
                - amplifyPush --simple
frontend:
    phases:
        preBuild:
            commands:
                - yarn install
                - export NODE_OPTIONS="--max-old-space-size=5120"
        build:
            commands:
                - yarn run build
    artifacts:
        baseDirectory: .next
        files:
            - '**/*'
    cache:
        paths:
            - node_modules/**/*
```

**Comment by hloriana** [comment]
Hi @kylekirkby 👋🏽 We have not removed those options from the console. I just tried to repro and was able to successfully create a preview with my SSR app. I 'm also able to see these options in the console: 

![Screen Shot 2022-06-24 at 11 40 58 AM](https://user-images.githubusercontent.com/76065904/175607056-550e19a2-07a9-4f4a-b5ce-3c89f7576b79.png)

I'm going to research this further to determine why you are not able to see these options.

**Comment by Jay2113** [comment]
Hi @kylekirkby, can you try the following steps to see if you are then presented with the "Manage preview settings for branch" workflow:
- Disable PR previews on your develop branch
- Navigate to App settings -> General -> Reconnect repository
- Enable PR previews on your develop branch

Additionally, you can setup frontend only PR Previews as follows:
- Remove the backend phase from your buildSpec (amplify.yml file)
```
version: 1
frontend:
    phases:
        preBuild:
            commands:
                - yarn install
                - export NODE_OPTIONS="--max-old-space-size=5120"
        build:
            commands:
                - yarn run build
    artifacts:
        baseDirectory: .next
        files:
            - '**/*'
    cache:
        paths:
            - node_modules/**/*
```
- Set the `AMPLIFY_SKIP_BACKEND_BUILD` environment variable to `true` within your app: https://docs.aws.amazon.com/amplify/latest/userguide/environment-variables.html#amplify-console-environment-variables:~:text=AMPLIFY_SKIP_BACKEND_BUILD
- Create a PR and it should only run the frontend build phase.
