### ISSUE TITLE
Running tests skips build artifact upload process

### ISSUE THREAD

**Issue by itswyll** [aws-amplify/amplify-hosting#2824]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

dm6pmstqyhyh5

### Region

eu-west-2

### Amplify Hosting feature

Build settings, E2E tests

### Describe the bug

Running tests during the pipeline with Playwright causes a skip uploading the build artifacts resulting in a deployment failure due to no files and ends the frontend build at `2022-06-15T11:41:56.935Z [INFO]: # Caching completed` instead of uploading them.

The provision, build, and test stages all pass, then deployment fails due to no build files.

### Expected behavior

After `2022-06-15T11:41:56.935Z [INFO]: # Caching completed`, the following appears in the frontend build on successful deployments.

I'm uncertain about the issue with the customHeaders. The file is empty on Amplify. This only appears when the artifact upload does.

```
2022-06-15T11:41:57.017Z [INFO]: !!Invalid custom header config file. The `customHeaders` key should be an array
2022-06-15T11:41:57.048Z [INFO]: # Starting build artifact upload process...
2022-06-15T11:41:57.523Z [INFO]: # Build artifact is: 5MB
2022-06-15T11:41:57.523Z [INFO]: # Uploading build artifact '__artifactsHash.zip'...
2022-06-15T11:41:57.524Z [INFO]: # Build artifact is: 5MB
2022-06-15T11:41:57.525Z [INFO]: # Uploading build artifact '__artifacts.zip'...
2022-06-15T11:41:57.690Z [INFO]: # Build artifact upload completed
2022-06-15T11:41:57.691Z [INFO]: # Starting environment caching...
2022-06-15T11:41:57.692Z [INFO]: # Uploading environment cache artifact...
2022-06-15T11:41:57.785Z [INFO]: # Environment caching completed
```

### Reproduction steps

Reproducible by using the following build settings and running a build deployment.

### Build Settings

```yaml
version: 1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - envCache --set stackInfo ""
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: /dist
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
test:
  phases:
    preTest:
      commands: 
        - echo fs.inotify.max_user_watches=65536 | tee -a /etc/sysctl.conf && sysctl -p
        - npm ci
        - npm install pm2
        - npm i -D @playwright/test
        - npx playwright install
        - npx pm2 start npm -- start
    test:
      commands:
        - npx playwright test
    postTest:
      commands:
        - npx pm2 kill
  artifacts:
    baseDirectory: /test-results
    files:
      - '**/*'
```

### Additional information

This is a similar issue to: https://github.com/aws-amplify/amplify-hosting/issues/41 https://github.com/aws-amplify/amplify-hosting/issues/963

I've tried a number of different build settings, but nothing changes unless the tests aren't run.
