### ISSUE TITLE
Rebuild required during test phase for Nextjs + Cypress

### ISSUE THREAD

**Issue by knightjdr** [aws-amplify/amplify-hosting#2826]
**Please describe which feature you have a question about?**

Adding Cypress testing to the build specification of a Nextjs app. I'm not sure if this is a bug or just a usage issue I don't understand.

**Provide additional details**

I've successfully setup testing with Cypress when deploying my Nextjs app. The concern I have is that I have to do my build step both during the frontend build and test phases. This doesn't seem to be required for non-Nextjs projects. In the build specification at the bottom of this post, the test phase will only work if it includes `npm run build`. Absence of that command results in next not finding an expected module:

```
2022-06-23T18:30:16.983Z [INFO]: # Executing command: npx start-test 'npm start' 3000 'npx cypress run --reporter mochawesome --reporter-options "reportDir=cypress/report/mochawesome-report,overwrite=false,html=false,json=true,timestamp=mmddyyyy_HHMMss"'
2022-06-23T18:30:17.243Z [INFO]: 1: starting server using command "npm start"
2022-06-23T18:30:17.245Z [INFO]: and when url "[ 'http://localhost:3000' ]" is responding with HTTP status code 200
2022-06-23T18:30:17.245Z [INFO]: running tests using command "npx cypress run --reporter mochawesome --reporter-options "reportDir=cypress/report/mochawesome-report,overwrite=false,html=false,json=true,timestamp=mmddyyyy_HHMMss""
2022-06-23T18:30:17.423Z [INFO]: > data-portal@1.0.0 start /codebuild/output/src249055319/src/data-portal/client
                                 > next start
2022-06-23T18:30:17.572Z [INFO]: ready - started server on 0.0.0.0:3000, url: http://localhost:3000
2022-06-23T18:30:17.970Z [WARNING]: Error: Cannot find module '/codebuild/output/src249055319/src/data-portal/client/.next/server/font-manifest.json'
                                    Require stack:
                                    - /codebuild/output/src249055319/src/data-portal/client/node_modules/next/dist/server/require.js
                                    - /codebuild/output/src249055319/src/data-portal/client/node_modules/next/dist/server/next-server.js
                                    - /codebuild/output/src249055319/src/data-portal/client/node_modules/next/dist/server/next.js
                                    - /codebuild/output/src249055319/src/data-portal/client/node_modules/next/dist/server/lib/start-server.js
                                    - /codebuild/output/src249055319/src/data-portal/client/node_modules/next/dist/cli/next-start.js
                                    - /codebuild/output/src249055319/src/data-portal/client/node_modules/next/dist/bin/next
                                    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
                                    at Function.mod._resolveFilename (/codebuild/output/src249055319/src/data-portal/client/node_modules/next/dist/build/webpack/require-hook.js:183:28)
                                    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
                                    at Module.require (internal/modules/cjs/loader.js:974:19)
                                    at require (internal/modules/cjs/helpers.js:101:18)
                                    at Object.requireFontManifest (/codebuild/output/src249055319/src/data-portal/client/node_modules/next/dist/server/require.js:63:26)
                                    at NextNodeServer.getFontManifest (/codebuild/output/src249055319/src/data-portal/client/node_modules/next/dist/server/next-server.js:480:30)
                                    at new Server (/codebuild/output/src249055319/src/data-portal/client/node_modules/next/dist/server/base-server.js:114:72)
                                    at new NextNodeServer (/codebuild/output/src249055319/src/data-portal/client/node_modules/next/dist/server/next-server.js:90:9)
                                    at NextServer.createServer (/codebuild/output/src249055319/src/data-portal/client/node_modules/next/dist/server/next.js:109:16) {
                                    code: 'MODULE_NOT_FOUND',
                                    requireStack: [
                                    '/codebuild/output/src249055319/src/data-portal/client/node_modules/next/dist/server/require.js',
                                    '/codebuild/output/src249055319/src/data-portal/client/node_modules/next/dist/server/next-server.js',
                                    '/codebuild/output/src249055319/src/data-portal/client/node_modules/next/dist/server/next.js',
                                    '/codebuild/output/src249055319/src/data-portal/client/node_modules/next/dist/server/lib/start-server.js',
                                    '/codebuild/output/src249055319/src/data-portal/client/node_modules/next/dist/cli/next-start.js',
                                    '/codebuild/output/src249055319/src/data-portal/client/node_modules/next/dist/bin/next'
                                    ]
                                    }
```

**What AWS Services are you utilizing?**

Just Amplify

**Provide additional details e.g. code snippets**

The test section is based on the recommendation [in this comment](https://github.com/aws-amplify/amplify-hosting/issues/2358#issuecomment-973313490)

```
version: 1
applications:
  - appRoot: client
    frontend:
      phases:
        preBuild:
          commands:
            - npm ci
        build:
          commands:
            - npm run build
      artifacts:
        baseDirectory: .next
        files:
          - '**/*'
      cache:
        paths:
          - node_modules/**/*
    test:
      phases:
        preTest:
          commands:
            - npm install
            - npm install start-server-and-test cypress mocha mochawesome mochawesome-merge mochawesome-report-generator --save-dev
        test:
          commands:
            - npm run build
            - npx start-test 'npm start' 3000 'npx cypress run --reporter mochawesome --reporter-options "reportDir=cypress/report/mochawesome-report,overwrite=false,html=false,json=true,timestamp=mmddyyyy_HHMMss"'
        postTest:
          commands:
            - npx mochawesome-merge cypress/report/mochawesome-report/mochawesome*.json > cypress/report/mochawesome.json
      artifacts:
        baseDirectory: cypress
        configFilePath: '**/mochawesome.json'
        files:
          - '**/*.png'
          - '**/*.mp4'
```
