### ISSUE TITLE
Why cache node_modules when prebuild command is "npm ci"?

### ISSUE THREAD

**Issue by LeoAso** [aws-amplify/amplify-hosting#2831]
When deploying an CRA or Next.js frontend to Amplify, the default configuration includes a prebuild command `npm ci` and cache path `node_modules/**/*`. 

````yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    # other stuff
  cache:
    paths:
      - node_modules/**/*
````

However, as far as I know, `npm ci` clears `node_modules` and installs everything from scratch, which means Amplify spends time caching dependencies after each build that will simply be discarded on the next build, rendering the caching unnecessary.

Am I mistaken about this, or would it be better &mdash; and faster &mdash; to use `npm install` or just to not cache `node_modules` at all?
