### ISSUE TITLE
Nextjs SSR Build Fail in yarn monorepo

### ISSUE THREAD

**Issue by itseasy21** [aws-amplify/amplify-hosting#2834]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d1trrhbw32iorq

### Region

us-east-1

### Amplify Hosting feature

Monorepo

### Describe the bug

We have a monorepo setup with 2 nextjs packages and 1 common UI packages. 

#### The issue: 
While installing the monorepo, yarn by default installs the packages in node_modules folder at the root directory of the repo. When the amplify build starts it is already in `packages/package1` directory and everything works fine until the next build finishes and SSR Build starts. At this point, as there is no `node_modules` in the current directory the SSR Build fails as it can't find `next` executable.

#### Workaround
As a workaround, we are executing the command `cp -r ../../node_modules .` post `yarn install` which makes the build go through, but this results in various warning messages of circular dependencies.

### Expected behavior

The SSR Build should be able to find the next executable from `../../node_modules` or there should be a way to set the `node_modules` path, like maybe using an env var `AMPLIFY_NODE_MODULES_DIR` where we can set this.

### Reproduction steps

Create a yarn monorepo, make sure it's on latest yarn(3.2.1).
Create a monorepo structrure like:
```
parent_dir
    packages
        common
        app1
        app2
```
Where app1 and app2 are nextjs projects
Deploy using the attached amplify.yml

### Build Settings

```yaml
version: 1
applications:
  - appRoot: packages/web
    frontend:
      phases:
        preBuild:
          commands:
            - yarn set version 3.2.1
            - yarn install
        build:
          commands:
            - SKIP_PREFLIGHT_CHECK=true yarn build
      artifacts:
        baseDirectory: .next
        files:
            - '**/*'
      cache:
        paths:
          - '../../node_modules/**/*' # Cache `node_modules` for faster `yarn` or `npm i`
          - '.next/cache/**/*' # Cache Next.js for faster application rebuilds
  - appRoot: packages/admin
    frontend:
      phases:
        preBuild:
          commands:
            - yarn set version 3.2.1
            - yarn install
        build:
          commands:
            - SKIP_PREFLIGHT_CHECK=true yarn build
      artifacts:
        baseDirectory: .next
        files:
            - '**/*'
      cache:
        paths:
          - '../../node_modules/**/*' # Cache `node_modules` for faster `yarn` or `npm i`
          - '.next/cache/**/*' # Cache Next.js for faster application rebuilds
```

### Additional information
Yarn Version: 3.2.1
NextJS Version: 12.1

### Error Log
<details>
  <summary>Logs</summary>

  ```bash
2022-06-27T09:19:35.029Z [INFO]: λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
2022-06-27T09:19:35.232Z [INFO]: Starting SSR Build...
2022-06-27T09:20:47.078Z [ERROR]: Error: Command failed with ENOENT: node_modules/.bin/next build
                                  spawn node_modules/.bin/next ENOENT
                                  at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
                                  at onErrorNT (node:internal/child_process:478:16)
                                  at processTicksAndRejections (node:internal/process/task_queues:83:21) {
                                  errno: -2,
                                  code: 'ENOENT',
                                  syscall: 'spawn node_modules/.bin/next',
                                  path: 'node_modules/.bin/next',
                                  spawnargs: [ 'build' ],
                                  originalMessage: 'spawn node_modules/.bin/next ENOENT',
                                  shortMessage: 'Command failed with ENOENT: node_modules/.bin/next build\n' +
                                  'spawn node_modules/.bin/next ENOENT',
                                  command: 'node_modules/.bin/next build',
                                  escapedCommand: '"node_modules/.bin/next" build',
                                  exitCode: undefined,
                                  signal: undefined,
                                  signalDescription: undefined,
                                  stdout: '',
                                  stderr: '',
                                  failed: true,
                                  timedOut: false,
                                  isCanceled: false,
                                  killed: false
                                  }
2022-06-27T09:20:47.080Z [ERROR]: [G[?25h[G[J
                                  31s › d1trrhbw32iorq › Error: Command failed with ENOENT: node_modules/.bin/next build
                                  spawn node_modules/.bin/next ENOENT
                                  [G[?25h
Terminating logging...
  ```

</details>
