### ISSUE TITLE
Build failed 

### ISSUE THREAD

**Issue by selva-harivara** [aws-amplify/amplify-hosting#2845]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

https://ap-south-1.console.aws.amazon.com/amplify/home?region=ap-south-1#/d2g5po0fxaesn8

### Region

ap-south-1

### Amplify Hosting feature

Backend builds

### Describe the bug

it's showing the error from when we using the build. the error is There was an error initializing your environment.
Error : ENOENT: no such file or directory, open '/amplify/backend/awscloudformation/build/root-cloudformation-stack.json'

### Expected behavior

there was error every time build running. i could not find the error. when we push the code into repository from the build start to build and every time build backend failed. we are using amplify cli version 9.1.0 

### Reproduction steps

1. git push into dev  branch
2. amplify build start build
3. Provision status is completed
4. build Backend is getting failed every time.

### Build Settings

```yaml
version: 1
backend:
  phases:
    build:
      commands:
        # - npm uninstall -g @aws-amplify/cli 
        # - rm -rf node_modules/@aws-amplify/
        # - npm install -g @aws-amplify/cli
        # - amplify init
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        # Generates a .npmrc file configured for installing private modules:
        # NPM_REGISTRY_URL: the full URL of your private registry
        # defaults to registry.npmjs.org.
        # NPM_TOKEN: secret token for installing private modules. This
        # this token can be found in your .npmrc, after logging in.
        - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
        - npm install
        # installs public and private modules.
        #- npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```
