### ISSUE TITLE
[Hosting] Access git credentials in build phase

### ISSUE THREAD

**Issue by Lorenzohidalgo** [aws-amplify/amplify-hosting#2850]
> **Note**: If your question is regarding the AWS Amplify Console service, please log it in the
> [AWS Amplify Console repository](https://github.com/aws-amplify/amplify-console/issues)

How could I access/use the git credentials during the build phase?
The application depends on a second repository (To which the Amplify GitHub app has access) which is accessed during the build phase. It is currently not built due to authentication issues.

I've seen in the cloning repository phase that it is accessing the git credentials:
`2022-07-05T17:50:37.992Z [INFO]: Git SSH Key acquired`
But they are disposed of after the repository is cloned:
`2022-07-05T17:50:43.901Z [INFO]: Successfully cleaned up Git credentials`

How could I replicate that during the build phase?

**Provide additional details e.g. code snippets. _Be sure to remove any sensitive data._**
Build Settings `amplify.yaml`
```yaml
version: 1
frontend:
  phases:
    preBuild:
        commands:
        - git clone https://github.com/flutter/flutter.git -b stable --depth 1
        - export PATH="$PATH:`pwd`/flutter/bin"
    build:
      commands:
      - flutter build web
  artifacts:
    baseDirectory: build/web/
    files:
      - '**/*'
  cache:
    paths: []
```

Current log errors:
```
2022-07-05T18:22:24.074Z [WARNING]: | stderr:
                                    | | Cloning into bare repository '/root/.pub-cache/git/cache/repo-5df103248e0ad3474cc445f31444989b6fc33aca'...
                                    | | Warning: Permanently added the ECDSA host key for IP address '140.82.121.3' to the list of known hosts.
                                    | | Permission denied (publickey).
2022-07-05T18:22:24.074Z [WARNING]: | | fatal: Could not read from remote repository.
                                    | |
                                    | | Please make sure you have the correct access rights
                                    | | and the repository exists.
                                    IO  : Spawning "git rev-parse --is-inside-git-dir" in /root/.pub-cache/git/cache/repo-5df103248e0ad3474cc445f31444989b6fc33aca
2022-07-05T18:22:24.075Z [WARNING]: IO  : Finished git. Exit code 128
```

**Comment by hloriana** [comment]
Hi @Lorenzohidalgo 👋🏽 thanks for raising this issue. Try following our FAQ guide for [How do I pull private packages during a build?](https://github.com/aws-amplify/amplify-hosting/blob/main/FAQ.md#how-do-i-pull-private-packages-during-a-build). This will show you how to create a new keypair and add it to your Amplify app and the repository you want to clone. Please let us know if this unblocks you.

**Comment by Lorenzohidalgo** [comment]
Hi @hloriana , thanks for the info! I've checked the FAQs and update the build settings to:
```yaml
version: 1
frontend:
  phases:
    preBuild:
        commands:
        - git clone https://github.com/flutter/flutter.git -b stable --depth 1
        - export PATH="$PATH:`pwd`/flutter/bin"
    build:
      commands:
      - eval "$(ssh-agent -s)"
      - ssh-add <(echo "$DEPLOY_KEY" | base64 -d)
      - flutter build web
  artifacts:
    baseDirectory: build/web/
    files:
      - '**/*'
  cache:
    paths: []
```

For some reason, the build is now getting stuck after the `export PATH` command. It's not even returning the prints stating that the `preBuild` phase has ended and the next one has started. Any idea why that could be happening? Is there any dependency between the Build Settings used to deploy the app and the build settings used to deploy a Preview? (The app was last deployed with the settings in the issue description and the preview should be built with the new settings but it's failing)
