### ISSUE TITLE
Support for Playwright testing framework with Amplify

### ISSUE THREAD

**Issue by Jay2113** [aws-amplify/amplify-hosting#2857]
**Is your feature request related to a problem? Please describe.**
Currently, Amplify only supports E2E tests with the Cypress testing framework.

**Describe the solution you'd like**
Extend Amplify's support for E2E tests with other testing framework such as Playwright.

**Comment by alexhhn** [comment]
Hi, does anyone have a working example of `amplify.yml` with playwright ?

**Comment by tonymaynard97** [comment]
Any update on when this will get prioritised? Around 1 in 5 downloads are Playwright
<img width="780" alt="Screenshot 2023-04-28 at 17 31 03" src="https://user-images.githubusercontent.com/43003807/235203346-427f660a-e6aa-4b23-bcc7-11f2b8a80915.png">

**Comment by dadamsGS** [comment]
> Any update on when this will get prioritised? Around 1 in 5 downloads are Playwright <img alt="Screenshot 2023-04-28 at 17 31 03" width="780" src="https://user-images.githubusercontent.com/43003807/235203346-427f660a-e6aa-4b23-bcc7-11f2b8a80915.png">

+1

**Comment by amcanirn** [comment]
+1

**Comment by magarwal19** [comment]
+1

**Comment by codenimble** [comment]
+1

**Comment by ZakBrinlee** [comment]
+1

**Comment by bensonarokiadoss** [comment]
+1

**Comment by nhantran3395** [comment]
+1

**Comment by miekassu** [comment]
+1

**Comment by swaminator** [comment]
@ZakBrinlee @dadamsGS what exactly would you like available for you out of the box?

**Comment by benjeater** [comment]
@swaminator I would like to be able to view the test artifacts within the Amplify Console in the same way as you can for Cypress tests.

As shown in [this post](https://github.com/aws-amplify/amplify-backend/issues/2150#issuecomment-2461169956), there is an error when visiting the test artifacts page when using Playwright.

It would also be great to have documentation such as you have for [Cypress](https://docs.aws.amazon.com/amplify/latest/userguide/running-tests.html)

**Comment by tomalessi** [comment]
+1

**Comment by sunggatalimbetov** [comment]
+1

**Comment by maria-luiza-rodrigues-ti** [comment]
+1

**Comment by aexiting** [comment]
+1

**Comment by koehn** [comment]
+1

**Comment by cipick** [comment]
+1

**Comment by felixpro** [comment]
+1

**Comment by Laurentiu28** [comment]
+1

**Comment by lyleunderwood** [comment]
I've setup playwright using [this mochawesome reporter](https://github.com/armindojr/pwmochawesome). I tried setting it up to mirror as closely as possible what seems like the intended cypress setup from [the](https://aws.amazon.com/blogs/mobile/running-end-to-end-cypress-tests-for-your-fullstack-ci-cd-deployment-with-amplify-console/) [docs](https://docs.aws.amazon.com/amplify/latest/userguide/running-tests.html).

amplify.yml:

```
test:
  phases:
    preTest:
      commands:
        - yarn tsc:check
        - yarn lint:errors
        - yarn test:ci
        - yarn test:functions:ci

        - yarn e2e:setup
        - 'yarn start & yarn exec wait-on http://localhost:3000'

    test:
      commands:
        - yarn e2e:auth
        - yarn exec dotenvx run -f .env.production -f .env.local -f .env -f .env.test -- playwright test
  artifacts:
    baseDirectory: cypress
    configFilePath: '**/mochawesome.json'
    files:
      - '**/*.png'
      - '**/*.mp4'
```
playwright config:

```
  reporter: [
    ['list'],
    [
      'pwmochawesome',
      {
        outputJSON: true,
        outputFileName: 'mochawesome.json',
        reportDir: 'cypress/report',
        generateHTML: false,
        overwrite: true
      }
    ]
  ],
```

And my build log seems to indicate that the output json file got picked up:

```
[INFO]: * JSON File saved to: /codebuild/output/src1358126117/src/<redacted>/cypress/report/mochawesome.json
[INFO]: # Completed phase: test
[INFO]: ## Tests completed successfully
[INFO]: # Starting test artifact upload process...
[INFO]: # Uploading test config file 'report/mochawesome.json'...
[INFO]: # Uploading build artifact 'testArtifacts.zip'...
[INFO]: # Uploaded test config file 'report/mochawesome.json'
[INFO]: # Test artifact upload completed
[INFO]: # Starting environment caching...
[INFO]: # Uploading environment cache artifact...
[INFO]: # Uploaded environment cache artifact
[INFO]: # Environment caching completed
```

But I still don't get any of the test UI. I can't download the test artifacts or anything.
