### ISSUE TITLE
Enable yarn berry

### ISSUE THREAD

**Issue by vetan2** [aws-amplify/amplify-hosting#2895]
**Describe the solution you'd like**
I'd like to enable to use yarn berry because of its better building-speed due to zero-install. But currently yarn version is fixed to 1.22.15.
I have tried setting node version to 16 then adding "corepack enable", or tried setting yarn version to 3.2.1 in Build image settings. But those did not work.

**Comment by itseasy21** [comment]
In your preBuild phase you can enable yarn berry by adding the following commands:
```yml
phases:
   preBuild:
       commands:
         - yarn set version 3.2.1 # This enables yarn berry and all commands after this will use that
         - yarn config set nodeLinker node-modules # if you use node modules else remove it if you use pnp
         - yarn install

**Comment by Octiony** [comment]
Is this a dead feature request?

**Comment by Octiony** [comment]
actually i managed to do it easily by modifying the build script

Here is what I used:

```
// amplify.yml

version: 1
frontend:
  phases:
    preBuild:
      commands:
        - nvm use 20
        - corepack enable
        - yarn set version stable
        - yarn install
    build:
      commands:
        - yarn run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```
