### ISSUE TITLE
Custom header overriding for matching patterns

### ISSUE THREAD

**Issue by tatethurston** [aws-amplify/amplify-hosting#2899]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Amplify Hosting feature

Custom headers

### Describe the bug

```yaml
customHeaders:
  - pattern: '**/*'
    headers:
    - key: 'Cache-Control'
      value: 'public, max-age=300'
  - pattern: '*.css'
    headers:
    - key: 'Cache-Control'
      value: 'public, max-age=604800, immutable'
```

With the above `customHttp.yml` I'm seeing all paths served with a `Cache-Control: public, max-age=300` header. Searching the documentation, there doesn't seem to be any discussion of how pattern collision is handled.

### Expected behavior

All pages have a `Cache-Control: public, max-age=300` header, except `*.css` pages, which have have `Cache-Control: public, max-age=604800, immutable`.

### Reproduction steps

1. Create the above `customHttp.yml`.
2. Observe the cache-control header for an application serving paths that end in .css

**Comment by tatethurston** [comment]
```
customHeaders:
  - pattern: '**/*'
    headers:
    - key: 'Cache-Control'
      value: 'public, max-age=300'
  - pattern: '**/*.css'
    headers:
    - key: 'Cache-Control'
      value: 'public, max-age=604800, immutable'
```
Resolves it for me. What are the matching / override semantics here, is amplify doing something clever with specificity? Or does `*.css` not match /foo/bar.css?
