### ISSUE TITLE
NuxtJs 503 error randomly happening

### ISSUE THREAD

**Issue by m7salam** [aws-amplify/amplify-hosting#2900]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d2p1ly4w7m10ve

### Region

eu-central-1

### Amplify Hosting feature

Performance

### Describe the bug

randomly I get 503 error can't satisfy your request cuz of load on one of the edge servers or something it happens very random can't really reproduce it, Im using NuxtJS (not next) on top of Vuejs

![image](https://user-images.githubusercontent.com/12870986/182099224-5371a186-1aa8-4c14-8226-2670cca2e1fc.png)

### Expected behavior

It suppose to work without getting this 503 error

### Reproduction steps

can't really reproduce it It happens very random

so I was wanting to know which direction should I check and what could cause it

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - if [ "${AWS_BRANCH}" = "master" ]; then npm run generate; fi
        - if [ "${AWS_BRANCH}" = "staging" ]; then npm run generateStaging; fi
        - if [ "${AWS_BRANCH}" != "master" || "${AWS_BRANCH}" != "staging" ]; then npm run generate; fi
  artifacts:
    # IMPORTANT - Please verify your build output directory
    baseDirectory: dist
    files:
      - "**/*"
  # cache:
  #   paths:
  #     - node_modules/**/*
```
