### ISSUE TITLE
Amplify is serving tsx files when using vitejs

### ISSUE THREAD

**Issue by tand22** [aws-amplify/amplify-hosting#2902]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d22t4p4muz6r32

### Region

ap-southeast2

### Amplify Hosting feature

Build settings

### Describe the bug

The build and deploy stage of AWS amplify work fine. However, trying to view the url in the browser shows a blank page and an error as the browser is trying to read a .tsx file. The bundled files from the build are not being sent.

### Expected behavior

Expecting to see the static bundled .js files from the output of the build log.

### Reproduction steps

1. Create a react typescript vitejs application
2. Commit it to github
3. Connect your github repo to amplify and deploy using default settings

### Build Settings

```yaml
version: 1
applications:
  - frontend:
      phases:
        preBuild:
          commands:
            - npm install
        build:
          commands:
            - npm run build
      artifacts:
        baseDirectory: /
        files:
          - '**/*'
      cache:
        paths:
          - node_modules/**/*
    appRoot: frontend
```
