### ISSUE TITLE
Build failing on app with empty frontend

### ISSUE THREAD

**Issue by m-crescentini** [aws-amplify/amplify-hosting#2917]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d1revzooetkjt4

### Region

eu-south-1

### Amplify Hosting feature

Build settings

### Describe the bug

I have an Amplify app with an empty frontend definition in the build settings and a backend definition which packages and deploys a CloudFormation stack (see below the definition). It always worked fine until 27/05; since then, the frontend step of the build fails with this error:

_[ERROR]: !!! CustomerError: Invalid artifact file paths provided in build spec_

Obviously I did not change anything in the build settings file.

### Expected behavior

The build completes successfully.

### Reproduction steps

1. Create an app with an empty frontend definition as configured in the build settings below
2. Push to the branch
3. The build starts
4. The build (frontend step) fails with the error "[ERROR]: !!! CustomerError: Invalid artifact file paths provided in build spec"

### Build Settings

```yaml
version: 1
frontend:
  phases:
    build:
      commands: []
  artifacts:
    baseDirectory: /
    files: []
  cache:
    paths: []
backend:
  phases:
    preBuild:
      commands:
        *CloudFormation stack package*
    build:
      commands:
        *ClouFormation stack deploy*
    postBuild:
        commands:
            ...
```

### Additional information

Working frontend build step (before May 27th):
![image](https://user-images.githubusercontent.com/88338153/183836440-bb57c8c2-e811-4e05-8e09-4ccad083d64d.png)

Failing frontend build step (since May 27th):
![image](https://user-images.githubusercontent.com/88338153/183836621-9dac3ce0-aab8-4cea-9fdf-a3ae5d467751.png)

**Comment by hloriana** [comment]
Hi @m-crescentini 👋🏽 your builds were not failing before because we were not validating this error at the time. Moving forward, the expected behavior is for this error to display when there is a frontend build detected and no proper file paths are provided. 

To skip the frontend entirely please set `PROCESS_SKIP_FRONTEND_DEPLOY` to `true` in your environment variables section.

Please let us know if you are unblocked. Thank you!

**Comment by m-crescentini** [comment]
Hi @hloriana, I got the build working for my app by setting `PROCESS_SKIP_FRONTEND_DEPLOY ` to `true` and changing the `artifacts/files` frontend param in the build settings like this:

```
version: 1
frontend:
  phases:
    build:
      commands: []
  artifacts:
    baseDirectory: /
    files:
        - '**/*'
  cache:
    paths: []
backend:
...
```

Thank you!
