### ISSUE TITLE
Lerna Monorepo - Can't install private github package

### ISSUE THREAD

**Issue by dylan-westbury** [aws-amplify/amplify-hosting#2923]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d4qjx8bzy0kti

### Region

us-east-1

### Amplify Hosting feature

Build settings, Custom builds, Monorepo

### Describe the bug

Private github package is not found for Lerna monorepo during build. Although it installs based on custom build settings.

### Expected behavior

Private github package should be found after successful install

### Reproduction steps

1. Set up amplify hosting for react app as monorepo (Lerna)
2. Update build settings to create .npmrc and install package
3. Run build

### Build Settings

```yaml
version: 1
applications:
  - backend:
      phases:
        build:
          commands:
            - '# Execute Amplify CLI with the helper script'
            - amplifyPush --simple
    frontend:
      phases:
        preBuild:
          commands:
            - yarn install --frozen-lockfile
            - echo -e "always-auth=true\n@apptractive:registry=https://npm.pkg.github.com/\n//npm.pkg.github.com/:_authToken=${NPM_AUTH_TOKEN}" > .npmrc
            - yarn add @apptractive/shared
            - yarn add @apptractive/design-system-web
        build:
          commands:
            - yarn run build
      artifacts:
        baseDirectory: build
        files:
          - '**/*'
      cache:
        paths:
          - node_modules/**/*
    appRoot: packages/backoffice-app
```

### Additional information

Also tried for another react frontend 

AppId `d3cy3g6nh4jbkc`

![Uploading Screen Shot 2022-08-11 at 8.33.38 pm.png…]()

**Comment by dylan-westbury** [comment]
Ah screenshot did not upload

![Screen Shot 2022-08-11 at 8 33 38 pm](https://user-images.githubusercontent.com/16129043/184568944-1e29cba9-51a6-436a-b9d3-ed8ef67f7938.png)

**Comment by dylan-westbury** [comment]
From https://docs.aws.amazon.com/amplify/latest/userguide/build-settings.html I also tried:

```
version: 1
applications:
  - backend:
      phases:
        build:
          commands:
            - '# Execute Amplify CLI with the helper script'
            - amplifyPush --simple
    frontend:
      phases:
        preBuild:
          commands:
            - npm config set registry https://npm.pkg.github.com
            - npm config set always-auth true
            - npm config set //https://npm.pkg.github.com/:_authToken ${NPM_AUTH_TOKEN}
            - yarn
        build:
          commands:
            - yarn run build
      artifacts:
        baseDirectory: build
        files:
          - '**/*'
      cache:
        paths:
          - node_modules/**/*
    appRoot: packages/backoffice-app

```

Same error

**Comment by dylan-westbury** [comment]
Issue was that the packages themselves within the monorepo required building.

```
version: 1
applications:
  - backend:
      phases:
        build:
          commands:
            - '# Execute Amplify CLI with the helper script'
            - amplifyPush --simple
    frontend:
      phases:
        preBuild:
          commands:
            - yarn global add lerna
            - npm config set registry https://npm.pkg.github.com
            - npm config set always-auth true
            - npm config set //https://npm.pkg.github.com/:_authToken=${NPM_AUTH_TOKEN}
            - lerna bootstrap --include-dependencies
            - cd ../shared && yarn build
            - cd ../design-web && yarn build
        build:
          commands:
            - yarn run build
      artifacts:
        baseDirectory: build
        files:
          - '**/*'
      cache:
        paths:
          - node_modules/**/*
    appRoot: packages/backoffice-app
```
