### ISSUE TITLE
AWS Hosting Pipeline Test phase keeps on failing even the Cypress specs passed

### ISSUE THREAD

**Issue by jonassarcilla** [aws-amplify/amplify-hosting#2929]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d22d3pytivgr2l

### Region

ap-southeast-2

### Amplify Hosting feature

E2E tests

### Describe the bug

Tried to deploy a web app with Cypress E2E testing.
On local, tested the yaml script and working
But when deployed to AWS amplify it keeps failing even when all the Cypress specs run as expected and with no fails.

![image](https://user-images.githubusercontent.com/32216903/184734654-8f02ed2b-5cfd-4971-a795-f6f374362260.png)

All specs passed
![image](https://user-images.githubusercontent.com/32216903/184734747-a134b090-fb99-4a49-b53e-c0d64908717b.png)

![image](https://user-images.githubusercontent.com/32216903/184734819-d1d208bf-9541-46c7-89db-dceb09345003.png)

I can also download the artifacts
![image](https://user-images.githubusercontent.com/32216903/184734927-9e7548c2-673a-4c49-a3b3-405ca0c30f57.png)

### Expected behavior

1. Since all Cypress spec passed, it should go through Deploy and Verify phase and the app will run as expected without any error.

### Reproduction steps

1. Redeploy manually

### Build Settings

```yaml
version: 2
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
      - .next/cache/**/*
      - ~/.cache
test:
  phases:
    preTest:
      commands:
        - yarn install
    test:
      commands:
        - yarn run test:unit && node -e 'setTimeout(() => process.exit(0), 5000)'
        - yarn run build && node -e 'setTimeout(() => process.exit(0), 5000)'
        - yarn cypress install --force
        - npx start-test 'yarn start' 3000 'npx cypress run --reporter mochawesome --reporter-options "reportDir=cypress/report/mochawesome-report,overwrite=false,html=false,json=true,timestamp=mmddyyyy_HHMMss"'
    postTest:
      commands:
        - node -e 'setTimeout(() => process.exit(0), 5000)'
        - npx mochawesome-merge cypress/report/mochawesome-report/mochawesome*.json > cypress/report/mochawesome.json
        - node -e 'setTimeout(() => process.exit(0), 5000)'
  artifacts:
    baseDirectory: cypress
    configFilePath: '**/mochawesome.json'
    files:
      - '**/*.png'
      - '**/*.mp4'
```
