### ISSUE TITLE
Some gzip files are not served for blazor wasm project

### ISSUE THREAD

**Issue by emerabet** [aws-amplify/amplify-hosting#2942]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d3drcnfa1b1cqc

### Region

eu-west-1

### Amplify Hosting feature

Performance

### Describe the bug

Hello,

I'm trying to host a blazor wasm project using amplify connected to github.
I followed this guide https://aws.amazon.com/fr/blogs/devops/deploy-net-blazor-webassembly-application-to-aws-amplify/
The gzip files and brotli files are well generated by the build command `dotnet publish -c Release -o release` but when deployed by Amplify only .js and .css are served with content-enconding to gzip.

<img width="928" alt="1" src="https://user-images.githubusercontent.com/37020593/186027111-d7a219fd-ebf4-46db-b7a9-04b0d9b72ffd.png">

<img width="778" alt="2" src="https://user-images.githubusercontent.com/37020593/186027138-d09c7af1-7ee5-48fd-9334-8848babedb3b.png">

### Expected behavior

All gzip files should be served

### Reproduction steps

1. Create a new blazor wasm project
2. Deploy using using amplify hosting 
3. Open the web site with the network tab active

or

Open this url with network tab active: https://main.d3drcnfa1b1cqc.amplifyapp.com

### Build Settings

```yaml
version: 1
applications:
  - frontend:
      phases:
        preBuild:
          commands:
            - curl -sSL https://dot.net/v1/dotnet-install.sh > dotnet-install.sh
            - chmod +x *.sh
            - ./dotnet-install.sh -c 6.0 -InstallDir ./dotnet6
            - ./dotnet6/dotnet --version
        build:
          commands:
            - ./dotnet6/dotnet publish -c Release -o release
      artifacts:
        baseDirectory: /release/wwwroot
        files:
          - '**/*'
      cache:
        paths: []
```

### Additional information

Thanks for your help
