### ISSUE TITLE
Can't Deploy Application, 'Houston, there's a problem. Network Failure'

### ISSUE THREAD

**Issue by reeslabree** [aws-amplify/amplify-hosting#2950]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

Can't Deploy

### Region

eu-central-1

### Describe the bug

Trying to host a Next.js app from amplify hosting, after clicking through all the menu options (connect Github, build settings, environment variables, etc.) when I reach the final screen and click 'Save and Deploy' it stalls for a second, and then throws `Houston, there's a problem. Network failure`.

Someone else on my team is able to host on AWS Amplify, and I can make edits, but when it comes to hosting a new application myself, it almost always throws this error. Only once or twice have I been able to make a new application, but due to the complexities of working around an Nx repository, I've had to delete applications and try again to tweak with app-root and whatnot.

### Expected behavior

Amplify should attempt to host my application, and at least reach the build step.

### Reproduction steps

1. new app
2. host web app
3. connect git repository
4. configure branch, select app root, etc.
5. click 'save and deploy'

### Build Settings

```yaml
# not sure if this is applicable, however I'm using the yml specified in a workaround related to nx
# with my app name, ofc
version: 1
applications:
  - frontend:
      phases:
        preBuild:
          commands:
            - npm install
        build:
          commands: 
            - npm run build:prod
      artifacts:
        baseDirectory: ../../dist/apps/mono-repro/.next
        files:
          - '**/*'
      cache:
        paths: 
            - node_modules/**/*
    appRoot: apps/mono-repro
```
