### ISSUE TITLE
build issue when trying to build react app

### ISSUE THREAD

**Issue by timalive** [aws-amplify/amplify-hosting#2955]
I am getting a very similar issue to  https://github.com/aws-amplify/amplify-hosting/issues/1365, but adding the backend build to the amplify.yml file does not help.  I amplify.yml file is as follows.  Everything works locally as expected, but building on amplify fails:
```
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm install
    build:
      commands:
        - REACT_APP_USER_POOL_ID=$REACT_APP_USER_POOL_ID
        - npm run build --verbose
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
backend:
  phases:
    build:
      commands:
        - amplifyPush --simple

```

The last few lines of output in the build are:
```
2022-08-29T19:43:54.997Z [INFO]: Creating an optimized production build...
2022-08-29T19:44:04.327Z [INFO]: Failed to compile.
```

Any help would be appreciated!

_Originally posted by @timalive in https://github.com/aws-amplify/amplify-hosting/issues/1365#issuecomment-1230786880_

**Comment by hloriana** [comment]
Hi @timalive 👋🏽 apologies for the delay. If you are still experiencing this issue, try adding the backend phase first and see if that resolves the issue. Full stack builds are completed with the backend phase building out first, followed by the frontend. So your amplify.yml should look like this:

```
version: 1
backend:
  phases:
    build:
      commands:
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - npm install
    build:
      commands:
        - REACT_APP_USER_POOL_ID=$REACT_APP_USER_POOL_ID
        - npm run build --verbose
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```
