### ISSUE TITLE
Redirect strips query params

### ISSUE THREAD

**Issue by DevPowers** [aws-amplify/amplify-hosting#2967]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d1op66f9k171p6

### Region

us-east-1

### Amplify Hosting feature

Redirects

### Describe the bug

1) When navigating to my website via the URL:  
'example.com?query1=query1' domain is redirected -> 'www.example.com' **stripping the query params**

### Expected behavior

1) When navigating to my website via the URL:  
'example.com?query1=query1' domain is redirected -> 'www.example.com?query1=query1'

2) The expected behavior works for my subdomains but not the main domain. 
'**subdomain**.example.com?query1=query1' domain is redirected -> 'www.**subdomain**.example.com?query1=query1'

### Reproduction steps

1. I can trigger the bug by entering my domain without the WWW and query params. The result is being navigated to the WWW domain with query params stripped.

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npx ci
    build:
      commands:
        - if [[("${AWS_BRANCH}" = "develop")]]; then npm run build:sandbox; fi
        - if [[("${AWS_BRANCH}" = "main")]]; then npm run build:sandbox; fi
        - if [[("${AWS_BRANCH}" != "main") && ("${AWS_BRANCH}" != "develop")]]; then npm run build:sandbox; fi
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```
