### ISSUE TITLE
I can't create a notification to notify you when the build succeeds or fails

### ISSUE THREAD

**Issue by parkournick2** [aws-amplify/amplify-hosting#2968]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

https://us-east-1.console.aws.amazon.com/amplify/home?region=us-east-1&code=08a6b86e9efc69d0f557#/d2okwu1ibzhglh

### Region

us-east-1

### Amplify Hosting feature

Notifications

### Describe the bug

I can't create a notification to notify when the build succeeds or fails. it loads for a long time and then it just disappears when i reload page without giving an error and without adding an email to receive the notification

### Expected behavior

I hope I can add an email to receive notifications

### Reproduction steps

1. ![image](https://user-images.githubusercontent.com/61525227/188633254-9276f942-df03-4304-b34c-83c44eef86c8.png)
2. ![image](https://user-images.githubusercontent.com/61525227/188633454-a4342823-69f7-486d-97dc-f9d721e2c756.png)

![image](https://user-images.githubusercontent.com/61525227/188633640-6aac5eb0-9ae9-41d7-b09b-0c0cb6897916.png)

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
        - nvm use 16
        - cd client
        - yarn --production=false
        - yarn install
    build:
      commands:
        - yarn build
  artifacts:
    baseDirectory: client/dist
    files:
      - 'client/*'
  cache:
    paths:
      - client/node_modules//*
```
