### ISSUE TITLE
Failed to deploy with no error messages

### ISSUE THREAD

**Issue by alexdemers** [aws-amplify/amplify-hosting#2976]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d3v5fhuza2jj3v

### Region

ca-central-1

### Amplify Hosting feature

Logging, Manual deploys

### Describe the bug

Since about a week ago, every builds in the application complete but the deployment fails, then a few seconds later they complete. Because of this, it seems that the deployment is incomplete: the application responds with a blank page, then a few minutes later (and after clearing the browser cache) the application deployed correctly, even though amplify mentions that the deployment failed.

I have no error message except this in the `Deploy` tab:

```
2022-09-08T13:59:51 [INFO]: Starting Deployment
2022-09-08T13:59:51 [INFO]: Updating Edge config
2022-09-08T13:59:51 [ERROR]: Failed to deploy
 Got archive: 7602706 bytes
2022-09-08T13:59:53 [INFO]: Deployment complete
```

### Expected behavior

Expected to deploy and verify successfully with the application being immediately available without any clearing of caches.

### Reproduction steps

1. Any deployment either manually with the console, or with automatically with new commits.

### Build Settings

```yaml
version: 1
frontend:
    phases:
        preBuild:
            commands:
                - yarn install --frozen-lockfile
        build:
            commands:
                - yarn run build
    artifacts:
        baseDirectory: public
        files:
            - '**/*'
    cache:
        paths:
            - node_modules/**/*
```
