### ISSUE TITLE
post-push.js is not executing anymore

### ISSUE THREAD

**Issue by danielhstahl** [aws-amplify/amplify-hosting#2981]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

dkn95cusc5c8

### Region

us-west-2

### Amplify Hosting feature

Backend builds

### Describe the bug

We have a post-push.js script which runs on after every build.  This has been working without fail for months.  On Tuesday it stopped working for us on some of our existing branches.  Today I created a new branch and post-push.js ran on it, but when redeploying post-push.js no longer runs.  The post-push.js file exists in the app S3 bucket.  When I pull the environment locally the post-push.js file exists.  When I attempt to deploy locally it runs post-push.js locally.  

### Expected behavior

post-push.js should continue running after a build.  

### Reproduction steps

1. Add post-push.js to your hooks folder
2. Push to your github branch that is connected to amplify 
3. Amplify builds and post-push.js runs
4. Push another change to the same branch
5. Amplify builds but post-push.js does not run

### Build Settings

```yaml
version: 1
env:
  variables:
    NODE_OPTIONS: --max-old-space-size=6500
backend:
  phases:
    preBuild:
      commands:
        - yum install -y yum-utils
        - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
        - yum install -y terraform
        - yum install -y python3

    build:
      commands:
        - update-alternatives --install /usr/bin/python3 python3 /usr/local/bin/python3.8 11
        - /usr/local/bin/pip3.8 install --user pipenv
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
```
