### ISSUE TITLE
Starting SSR build - Serverless error - NX Monorepo

### ISSUE THREAD

**Issue by sbacon-bamboo** [aws-amplify/amplify-hosting#2999]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d28kfw3ppjilgu

### Region

eu-west-2

### Describe the bug

I have tried multiple variations of amplify.yml from various online resources to deploy an NX monorepo application to Amplify. I had it working fine with SSG but now I need SSR I cannot get it to deploy. The process terminates without any feedback on why the serverless deployment is failing.

2022-09-21T09:54:41.101Z [INFO]: Starting SSR Build...
2022-09-21T09:55:41.052Z [ERROR]: Serverless Error ----------------------------------------
Terminating logging...

### Expected behavior

Application should be deployed to Amplify with SSR enabled.

### Reproduction steps

1. Trigger new Amplify build.
2. Review frontend build step and view error.

### Build Settings

```yaml
version: 1
applications:
  - frontend:
      phases:
        build:
          commands:
            # This step will build app with Nx framework
            - cd ../../
            - yarn install
            - yarn run build
            # This step will build/update SSR resources(S3, Cloudfront, Lambda@Edge)
            - cd apps/bamboo-fusion
            - yarn install
      artifacts:
        baseDirectory: ../../dist/apps/bamboo-fusion/.next
        files:
          - '**/*'
      cache:
        paths:
            - node_modules/**/*
    appRoot: apps/bamboo-fusion
```

**Comment by hloriana** [comment]
Hi @sbacon-bamboo 👋🏽 apologies for the delay in response. We are investigating this behavior and will provide an update shortly.

**Comment by sbacon-bamboo** [comment]
Thank you. I appreciate you looking into this. We need to be able to deploy NX monorepos to maintain using Amplify going forwards. I have seen quite a few other users online struggling with the same thing.

**Comment by tranthienhao** [comment]
I'm facing the same issue with this Amplify settings:
```
version: 1
applications:
  - frontend:
      phases:
        preBuild:
          commands:
            - yarn install
        build:
          commands:
            - cd .. && yarn build
      artifacts:
        baseDirectory: .next
        files:
          - '**/*'
      cache:
        paths:
          - node_modules/**/*
    appRoot: site
```

The response: 
```
2022-10-13T07:24:22.796Z [INFO]: Starting SSR Build...
2022-10-13T07:25:31.406Z [ERROR]: Serverless Error ----------------------------------------
```

Please help to resolve, thanks
