### ISSUE TITLE
Access to fetch at 'http..........endNotification' from origin 'https:........amplifyapp.com' has been blocked by CORS policy: Request header field content-type is not allowed by Access-Control-Allow-Headers in preflight response.

### ISSUE THREAD

**Issue by tegaologe** [aws-amplify/amplify-hosting#3009]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Region

us-central1

### Amplify Hosting feature

Not applicable

### Describe the bug

Access to fetch at 'https://........cloudfunctions.net/sendNotification' from origin 'https:/.............com' has been blocked by CORS policy: Request header field content-type is not allowed by Access-Control-Allow-Headers in preflight response.

### Expected behavior

I am using firebase cloud function for a specific reason. It will work when i disable CORS on my localhost when I build on Amplify Hosting I get the error listed

`Access to fetch at 'https://........cloudfunctions.net/sendNotification' from origin 'https:/.............com' has been blocked by CORS policy: Request header field content-type is not allowed by Access-Control-Allow-Headers in preflight response.`

I hope someone can help me explain how to disable CORS so this function can work.

### Reproduction steps

1.  Running the function with error above
2. I have tried editing customHttp.yml'
3. 

### Build Settings

```yaml
version: 0.1
backend:
  phases:
    # IMPORTANT - Please verify your build commands
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - npm install -g @quasar/cli
        - npm ci
    build:
      commands:
        - quasar build -m pwa
  artifacts:
    # IMPORTANT - Please verify your build output directory
    baseDirectory: /dist/pwa
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

### Additional information

customHeaders:
  - pattern: '**'
    headers:
      - key: Cross-Origin-Opener-Policy
        value: same-origin
      - key: Cross-Origin-Embedder-Policy
        value: require-corp
      - key: Access-Control-Allow-Origin
        value: '*'
      - key: Access-Control-Allow-Methods
        value: GET
