### ISSUE TITLE
Amplify configured for next.js is not removing always removing all services

### ISSUE THREAD

**Issue by fnavarrodev** [aws-amplify/amplify-hosting#3024]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d28nwgksusfkk0

### Region

eu-west-1

### Amplify Hosting feature

Not applicable

### Describe the bug

We have issues using Amplify configured as Next.js. We had an app with ID d28nwgksusfkk0 than now is deleted. I noticed that some PRs and branches after being closed still had cloudfront, s3 buckets, Lambda functions and cloudwatch log groups. This is a big problem because at some point the buckets are more than 100 and we are over quota. Also I'm not sure if we are paying more for things that we are not using. We have other apps using Amplify and we don't even see all their infrastructure(cloudfront, S3...). I think there's a bug somewhere in Amplify for Next.js and Bitbucket. Now they are 3 cloudfronts and buckets even after deleting the app. Cloudfront IDS: E3CDR1ZN4TVPC, E3VT9FDUFW0OQN, EEYQSHDEE3LX5. Let me know if you need more information.

### Expected behavior

We were expecting not seeing the infrastructure services in our account, as Amplify does with other kind of apps. At least we were expecting to some of them to be deleted after branches/PRs are closed.

### Reproduction steps

1. Make a next.js app
2. Connect previews
3. Connect branches
4. Close PRs
5. Close branches

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - rm -rf serverles.yml
        - rm -rf .serverless
        - printf "//`node -p \"require('url').parse(process.env.NPM_REGISTRY_URL || 'https://registry.npmjs.org').host\"`/:_authToken=${NPM_TOKEN}\nregistry=${NPM_REGISTRY_URL:-https://registry.npmjs.org}\n" >> ~/.npmrc
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
test:
  artifacts:
    baseDirectory: cypress
    configFilePath: '**/mochawesome.json'
    files:
      - '**/*.png'
      - '**/*.mp4'
  phases:
    preTest:
      commands:
        - npm install
        - npm install start-server-and-test cypress mocha mochawesome mochawesome-merge mochawesome-report-generator --save-dev
    test:
      commands:
        - npm run build
        - >-
          npx start-test 'npm start' 3000 'npx cypress run --reporter mochawesome --reporter-options
          "reportDir=cypress/report/mochawesome-report,overwrite=false,html=false,json=true,timestamp=mmddyyyy_HHMMss"'
    postTest:
      commands:
        - npx mochawesome-merge cypress/report/mochawesome-report/mochawesome*.json > cypress/report/mochawesome.json
```

### Additional information

We use our own serverless infrastructure for production, this is why we have a serverless.yml in our repository. I don't know if this can affect.
