### ISSUE TITLE
USER_DISABLE_TESTS=true not working

### ISSUE THREAD

**Issue by kwanso-salman** [aws-amplify/amplify-hosting#3027]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Region

us-east-1

### Amplify Hosting feature

Environment variables

### Describe the bug

I have USER_DISABLE_TESTS set to true for quite a time and it was working fine (skipping test phase in build), but from today (7th October 2022), this just does not seem to work and test cases are being executed regardless of USER_DISABLE_TESTS = true for all branches

### Expected behavior

if USER_DISABLE_TESTS is set to true, amplify should not run test phase

### Reproduction steps

run build

### Build Settings

```yaml
test:
  phases:
    preTest:
      commands:
        - ls -l
        - rm -rf node_modules
        - ls -l
        - npm ci
        - npm install wait-on
        - npm install pm2
        - npm install mocha@5.2.0 mochawesome mochawesome-merge mochawesome-report-generator
        - npx pm2 start npm -- start
        - "npx wait-on http://localhost:3000"
    test:
      commands:
        - npm test -- --watchAll=false
    postTest:
      commands:
        - npx pm2 kill
  artifacts:
    baseDirectory: test_artifacts
    configFilePath: "**/mochawesome.json"
    files:
      - "**/*.png"
      - "**/*.mp4"
```
