### ISSUE TITLE
Test step stays "pending or cancelled" after build completes.

### ISSUE THREAD

**Issue by 0618** [aws-amplify/amplify-hosting#3038]
**Please describe which feature you have a question about?**

Test skipped with message "Test is still pending or has been cancelled for this build."

**Provide additional details**

**What AWS Services are you utilizing?**

Amplify Hosting build

**Provide additional details e.g. code snippets**

**App ARN**: arn:aws:amplify:us-east-1:200176217753:apps/d2i9fogabw4dwd

amplify.yml

```
version: 1
applications:
  - frontend:
      phases:
        preBuild:
          commands:
            - rm -rf node_modules
            - nvm install 16.13 # NodeJS 16.13+ is the latest version that Amplify Hosting supports
            - nvm use 16
            - node -v
            - export FLUTTER_HOME=${HOME}/sdks/flutter
            - git clone -b stable --depth 1 https://github.com/flutter/flutter.git ${FLUTTER_HOME}
            - export PATH="$PATH:${FLUTTER_HOME}/bin"
            # Skip cypress binary installation, as it's unneeded for docs and often fails transiently
            # https://docs.cypress.io/guides/references/advanced-installation#Skipping-installation
            - export CYPRESS_INSTALL_BINARY=0
            - (cd .. && yarn install && yarn build)
        build:
          commands:
            - nvm install 16.13
            - nvm use 16
            - node -v
            - yarn flutter:build
            - yarn build
      artifacts:
        baseDirectory: .next
        files:
          - '**/*'
    appRoot: docs
  - test:
      phases:
        preTest:
          commands:
            - npm ci
            - yarn add wait-on
            - yarn add pm2
            - yarn add mocha@5.2.0 mochawesome mochawesome-merge mochawesome-report-generator
            # - npx pm2 start npm -- start
            - 'yarn docs dev & npx wait-on http://localhost:5001'
        test:
          commands:
            - 'npx cypress run --reporter mochawesome --reporter-options "reportDir=cypress/report/mochawesome-report,overwrite=false,html=false,json=true,timestamp=mmddyyyy_HHMMss"'
        postTest:
          commands:
            - npx mochawesome-merge cypress/report/mochawesome-report/mochawesome*.json > cypress/report/mochawesome.json
            - npx pm2 kill
      artifacts:
        baseDirectory: docs/cypress
        configFilePath: '**/mochawesome.json'
        files:
          - '**/*.png'
          - '**/*.mp4'
```
