### ISSUE TITLE
Amplify previews don't update after the initial deployment

### ISSUE THREAD

**Issue by yznima** [aws-amplify/amplify-hosting#3043]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

XXXXX (I can provide privately)

### AWS Region

us-east-2

### Amplify Hosting feature

Backend builds, Deployments, Frontend builds, Web previews

### Describe the bug

We deploy a web application, NextJS SSR, using Amplify. The application uses Amplify Hosting. 

Starting yesterday, we are running into an issue where previews are not updates when a new commit is added to the branch. When a new commit is pushed to the branch, the preview is built and deployed successfully as shown in the UI. However, when I navigate to the preview page, nothing is updated from the first iteration. This is a new issue and everything was working as of 2 days ago.

Before this, all the previews where sharing the same backend. I have also tried changing that configuration so that each preview creates a new backend environment but that doesn't change anything. Still broken.

### Expected behavior

I expect the previews UI to be updated when a new change is pushed to the branch associated with the preview.

### Reproduction steps

1. Enable Previews for a branch.
2. Create a Pull Request to that branch.
3. Wait for the Preview to be built and deployed
4. Push a new commit to the branch
5. Wait for the Preview to be built and deployed
6. Expect the preview to be updated with new content but it is not

### Build Settings

```yaml
version: 1
applications:
  - backend:
      phases:
        build:
          commands:
            - amplifyPush --simple
  - frontend:
      phases:
        preBuild:
          commands:
            - yarn install
        build:
          commands:
            - yarn build
      artifacts:
        baseDirectory: .next
        files:
          - '**/*'
      cache:
        paths: 
          - '/web/node_modules/**/*'
          - '/web/.next/cache/**/*'
    appRoot: web
```

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

After some investigation, I can confirm that even-though the I see the log line that Deployment is complete, the S3 content don't seem to be updated
