### ISSUE TITLE
Deployment successful but blank screen on homepage 

### ISSUE THREAD

**Issue by kriti-eco** [aws-amplify/amplify-hosting#3048]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d375dbai5qprls

### AWS Region

us-west-2

### Amplify Hosting feature

Deployments, Frontend builds

### Describe the bug

Deloyed ReactJS , MUI based application. Deployment was successful but then it shows blank screen as home page. 
On browser inspect , there are errors - 
main.7678acd3.js:2 TypeError: Cannot read properties of undefined (reading 'error')
Unchecked runtime.lastError: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received

### Expected behavior

It should provide home page with dashboard. 

### Reproduction steps

Build and deploy the app from Github using Amplify hosting

### Build Settings

```yaml
version: 1
backend:
  phases:
    build:
      commands:
        - ln -fs /usr/local/bin/pip3.8 /usr/bin/pip3
        - ln -fs /usr/local/bin/python3.8 /usr/bin/python3
        - pip3 install --user pipenv
        - npm install @mui/material
        - npm install @mui/icons-material
        - npm install @emotion/styled
        - npm install @emotion/cache
        - npm install @emotion/react
        - npm install @emotion/babel-plugin
        - npm install @emotion/css
        - npm install @emotion/serialize
        - npm install @emotion/memoize
        - npm install @emotion/sheet
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
        - aws amplify update-app --app-id d375dbai5qprls --platform WEB --region us-west-2
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

### Log output

<details>

```
# Put your logs below this line

DevTools failed to load source map: Could not parse content for https://main.d375dbai5qprls.amplifyapp.com/static/js/main.7678acd3.js.map: Unexpected token '<', "<!doctype "... is not valid JSON
TypeError: Cannot read properties of undefined (reading 'error')
Manifest: Line: 1, column: 1, Syntax error.
Unchecked runtime.lastError: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
```

</details>
