### ISSUE TITLE
Hugo deploy issue

### ISSUE THREAD

**Issue by yinxiangshi** [aws-amplify/amplify-hosting#3050]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

dss7jdt6jz73o

### AWS Region

us-east-1

### Amplify Hosting feature

Not Applicable

### Describe the bug

I'm trying to deploy my hugo site on Amplify. My personal domain is configured, but I still can't open my site, either from the domain provided by Amplify or from my own domain.

### Expected behavior

Site working well

### Reproduction steps

None

### Build Settings

```yaml
version: 1
frontend:
  phases:
    build:
      commands:
        - rm -rf /usr/bin/hugo
        - wget -q https://github.com/gohugoio/hugo/releases/download/v${VERSION_HUGO_NEW}/hugo_extended_${VERSION_HUGO_NEW}_Linux-64bit.tar.gz
        - tar -xvf hugo_extended_${VERSION_HUGO_NEW}_Linux-64bit.tar.gz
        - mv hugo /usr/bin/hugo
        - rm -rf hugo_extended_${VERSION_HUGO_NEW}_Linux-64bit.tar.gz
        - hugo
  artifacts:
    baseDirectory: public
    files:
      - '**/*'
  cache:
    paths: []
```

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

Error message: Failed to load resource: the server responded with a status of 404 () allonsygamma.com/:1
