### ISSUE TITLE
Setting up Amplify studio failed

### ISSUE THREAD

**Issue by apal** [aws-amplify/amplify-hosting#3051]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

arn:aws:amplify:us-west-2:867402340790:apps/d3tl1b3kio2dw1

### AWS Region

us-west-2

### Amplify Hosting feature

Backend builds

### Describe the bug

I have tried several times and configured IAM users correctly according to this document (https://aws.amazon.com/getting-started/hands-on/build-react-app-amplify-graphql/module-two/?e=gs2020&p=build-a-react-app-one)

I get "Setting up Amplify Studio failed"

I read https://github.com/aws-amplify/amplify-adminui/issues/609 but that doesn't seem to have comments on how this can be resolved.

### Expected behavior

Amplify studio backend environment is set up successfully

### Reproduction steps

1. Go to AWS Amplify console 
2. Select your _app_-> Backend Environment -> Get Started

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

### Log output

<details>

```
# Put your logs below this line


```

</details>
