### ISSUE TITLE
Test stopped and failed for no reason

### ISSUE THREAD

**Issue by 0618** [aws-amplify/amplify-hosting#3052]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d2iylcvof45zeg

### AWS Region

us-east-1

### Amplify Hosting feature

E2E Cypress tests

### Describe the bug

The test stopped and failed, but there's no error message in the log and the artifact is not accessible

![image](https://user-images.githubusercontent.com/11983489/197861280-23c65973-9125-4904-9c2b-7a6e26550f93.png)

![image](https://user-images.githubusercontent.com/11983489/197861646-e4e88d17-2535-4fee-8131-d21255563265.png)

### Expected behavior

If the test fails, there should be error messages logged in the console and/or in the artifact.

### Reproduction steps

Build this commit from github https://github.com/0618/amplify-ui/commit/000cf8222b34263531bab0e7eee110ea26ab62b3

### Build Settings

```yaml
the `test` stage in `amplify.yml`


test:
      phases:
        preTest:
          commands:
            - nvm install 16.13 # NodeJS 16.13+ is the latest version that Amplify Hosting supports
            - nvm use 16
            - npm install
            - npm install wait-on
            - npm install pm2
            - npm install mocha mochawesome mochawesome-merge mochawesome-report-generator
            - npm install cypress
            - npm run build
            - npx pm2 start npm -- start
            - 'npx wait-on http://localhost:3000'
        test:
          commands:
            - 'npx cypress run --reporter mochawesome --reporter-options "reportDir=cypress/report/mochawesome-report,overwrite=false,html=false,json=true,timestamp=mmddyyyy_HHMMss"'
        postTest:
          commands:
            - npx mochawesome-merge cypress/report/mochawesome-report/mochawesome*.json > cypress/report/mochawesome.json
            - npx pm2 kill
      artifacts:
        baseDirectory: cypress
        configFilePath: '**/mochawesome.json'
        files:
          - '**/*.png'
          - '**/*.mp4'
```
```


### Log output

<details>

```
# Put your logs below this line

```

</details>


### Additional information

_No response_
