### ISSUE TITLE
Website not working, build successful

### ISSUE THREAD

**Issue by benbelo** [aws-amplify/amplify-hosting#3053]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

https://us-east-2.console.aws.amazon.com/amplify/home?region=us-east-2#/d3rsgiy8hyiumr

### AWS Region

us-east-2

### Amplify Hosting feature

Frontend builds

### Describe the bug

Hello,

I have a successful build (I tried it couples mins ago).
I am hosting a Jekyll website, the code is fine.

I can't see where to find what causes my issue.
It seems not to be a dns issue.

My custom domain is in Route 53 and the link is ok.

The browser message is : ERR_CONNECTION_RESET

Can you please help me ?

### Expected behavior

A working site...

### Reproduction steps

1. Build
2. Website not working

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - bundle install
    # IMPORTANT - Please verify your build commands
    build:
      commands:
        - bundle exec jekyll b
  artifacts:
    # IMPORTANT - Please verify your build output directory
    baseDirectory: _site
    files:
      - '**/*'
  cache:
    paths: []
```

### Log output

<details>

```
# Put your logs below this line


```

</details>
