### ISSUE TITLE
Provision > Build > Deploy Process Exceedingly Slow

### ISSUE THREAD

**Issue by nategoethel** [aws-amplify/amplify-hosting#3082]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d1v6pv2eihui24

### AWS Region

us-east-2

### Amplify Hosting feature

Deployments

### Describe the bug

My app appears to be stuck at "Pending":
<img width="462" alt="Screen Shot 2022-11-04 at 5 43 57 PM" src="https://user-images.githubusercontent.com/44580393/200085900-fa22ebbc-6294-4ecd-b63e-0997cb83c1f1.png">

The provision > build > deploy process is also exceedingly slow. For the "in progress" build, I see no movement from the provision stage. I used to be able to watch this process complete in real time over the course of a couple of minutes.

### Expected behavior

The entire process used to take <5 minutes.

### Reproduction steps

??

### Build Settings

```yaml
version: 1
applications:
- appRoot: user_docs
  frontend:
      phases:
        preBuild:
          commands:
            - dir=$(pwd)
            - echo $dir
            - ls
            - npm install
        build:
          commands:
            - npm run build
      artifacts:
        baseDirectory: /build
        files:
          - '**/*'
      cache:
        paths:
          - node_modules/**/*
```

### Log output

<details>

```
# Put your logs below this line


```

</details>
