### ISSUE TITLE
Issue with Access control in AWS Amplify

### ISSUE THREAD

**Issue by RyousukeUchino** [aws-amplify/amplify-hosting#3113]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d2lghr8m48vytd

### AWS Region

ap-northeast-1

### Amplify Hosting feature

Access control

### Describe the bug

If you change any settings in Access Control, all branches will stop accepting access
If you disable access restrictions and change to public access, the change will not be applied
I have a SSR build, so committing to the branch again and rebuilding does not fix the problem.

### Expected behavior

Change Access Control settings

### Reproduction steps

1.Open Access Control
2.Change password
3.Save Changes
4.Add a commit to the branch and deploy
5.Access the page after deployment is complete
6.When I access the site, it asks me for my ID and password, and when I enter the correct ID and password, it asks me to do the same thing forever
Or, even if I have public access, I am asked for my ID and password forever  
Entering the information as requested will not give  access, and  will be asked to enter ID password forever

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

Announcement was made and Amplify Hosting was upgraded according to the announcement
[https://docs.aws.amazon.com/amplify/latest/userguide/ssr-Amplify-support.html](https://docs.aws.amazon.com/amplify/latest/userguide/ssr-Amplify-support.html)

However, I had the same problem before this change
