### ISSUE TITLE
Web Previews not showing on PR in private GitHub repo

### ISSUE THREAD

**Issue by lexhl** [aws-amplify/amplify-hosting#3149]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d2u922lorr92pe

### AWS Region

eu-west-1

### Amplify Hosting feature

Web previews

### Describe the bug

I am not seeing any PR web previews on my private github repo. The branches are being created automatically on amplify and they shows as "previews enabled" put the PR list in the amplify console is empty.

### Expected behavior

When I create a PR for a branch with a matching branch name a web preview appears on the GitHub PR UI and the PR appears in the amplify console 

### Reproduction steps

I do not know why this happened. I followed the instructions for using CDK to set up an amplify app against my private github repo within my organization, initially using a personal access token. Everything seemed to work apart from the web previews. I have tried reinstalling the amplify GitHub app and reconnecting the repository neither of which fixed the issue.  

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - cd app
        - yarn
    build:
      commands:
        - yarn run build
  artifacts:
    files:
        - "**/*"
    discard-paths: yes
    baseDirectory: "app/dist"
  cache:
    paths:
        - "app/node_modules"
```

### Additional information

![Screenshot 2022-11-25 at 13 25 14](https://user-images.githubusercontent.com/5296869/203995611-865e2af4-90c4-43a0-bfc5-0f0ac2b9b4fa.png)
![Screenshot 2022-11-25 at 13 25 48](https://user-images.githubusercontent.com/5296869/203995615-80e228b5-35c9-4086-ab5f-1247b8c4f41c.png)
![Screenshot 2022-11-25 at 13 26 37](https://user-images.githubusercontent.com/5296869/203995617-414c2601-00db-4daa-9fe7-db5d08ac783e.png)
