### ISSUE TITLE
NextJS 12 frontend build throws "No build cache found. Please configure build caching for faster rebuilds" warning

### ISSUE THREAD

**Issue by LucasLemanowicz** [aws-amplify/amplify-hosting#3209]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d2gl6gra9yo4lf

### AWS Region

us-west-2

### Amplify Hosting feature

Frontend builds

### Describe the bug

NextJS 12 build cache does not seem to be working for me on AWS Amplify. I have a monorepo with the frontend hosted in a subdirectory, and my amplify.yml configuration looks like this:

```yml
version: 1
applications:
  - frontend:
      phases:
        preBuild:
          commands:
            - nvm install 14
            - nvm use 14
            - yarn install
        build:
          commands:
            - nvm use 14
            - yarn run build:$BUILD_TYPE
        test:
          commands:
            - nvm use 14
            - yarn run test:$BUILD_TYPE
      artifacts:
        baseDirectory: .next
        files:
          - '**/*'
      cache:
        paths:
          - '.next/cache/**/*'
          - 'node_modules/**/*'
    appRoot: path/to/frontend
```

When I run a build, I see the following warning message in my frontend build logs:
```
warn  - No build cache found. Please configure build caching for faster rebuilds. Read more: https://nextjs.org/docs/messages/no-cache
```

### Expected behavior

I expect the build cache to be found.

### Reproduction steps

1. See the config above

### Log output

<details>

```
# Put your logs below this line


```

</details>
