### ISSUE TITLE
Internationalized (i18n) sub-path routing

### ISSUE THREAD

**Issue by dr-star** [aws-amplify/amplify-hosting#3224]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d1y61lmg5x2yx8

### AWS Region

us-east-1

### Amplify Hosting feature

Redirects

### Describe the bug

As it is written into the [documentation ](https://docs.aws.amazon.com/amplify/latest/userguide/ssr-Amplify-support.html) should be supported by Amplify.

At this moment, for me, it is not working

### Expected behavior

Given the following configuration
```
// next.config.js
module.exports = {
  i18n: {
    locales: ['en', 'it'],
    defaultLocale: 'en',
  },
}
```

If I have a _pages/login.js_ the following urls would be available:

/login
/it/login

### Reproduction steps

1. Create next.js app (version 13>)
2. [Add i18n feature](https://nextjs.org/docs/advanced-features/i18n-routing)
3. Deploy to amplify

### Build Settings

```yaml
version: 1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

App created 11/23/2022, 10:55:03 AM
