### ISSUE TITLE
Amplify Build is broken with error - "TypeScript executable not found."

### ISSUE THREAD

**Issue by KarthickSelvam** [aws-amplify/amplify-hosting#3231]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d243offqyjitf0

### AWS Region

eu-central-1

### Amplify Hosting feature

Backend builds

### Describe the bug

the deployment CI is failing with error - 

2023-01-09T10:37:30.981Z [INFO]: [0mAmplify AppID found: d243offqyjitf0. Amplify App name is: ----[0m
2023-01-09T10:37:31.032Z [INFO]: [0mBackend environment test found in Amplify Console app: -----[0m
2023-01-09T10:37:31.899Z [WARNING]: - Fetching updates to backend environment: test from the cloud.
2023-01-09T10:37:32.760Z [WARNING]: - Building resource auth/-------
2023-01-09T10:37:32.761Z [WARNING]: - Building resource api/-----
2023-01-09T10:37:32.762Z [WARNING]: - Building resource custom/----
2023-01-09T10:37:32.762Z [WARNING]: - Building custom resources
2023-01-09T10:37:38.093Z [WARNING]: ✖ There was an error initializing your environment.
2023-01-09T10:37:38.563Z [INFO]: 🛑 TypeScript executable not found.
                                 Resolution: Please add it as a dev-dependency in the package.json file for this resource.
2023-01-09T10:37:38.564Z [INFO]: Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/
2023-01-09T10:37:38.565Z [INFO]: 
2023-01-09T10:37:38.565Z [INFO]: Session Identifier: 14ff5981-c8aa-4926-bf52-c625f18f47c3

### Expected behavior

Build completes without error, even previous successful build is failing now so that should pass.

### Reproduction steps

Go to the console
Go to the amplify app
click on "redeploy this version" and see the build is failing

### Build Settings

```yaml
version: 1
backend:
  phases:
    build:
      commands:
        - npm i -g graphql-ttl-transformer
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn run build
  artifacts:
    baseDirectory: build
    files:
      - "**/*"
  cache:
    paths:
      - node_modules/**/*
test:
  artifacts:
    baseDirectory: cypress
    configFilePath: "**/mochawesome.json"
    files:
      - "**/*.png"
      - "**/*.mp4"
  phases:
    preTest:
      commands:
        - yarn install
        - yarn add mocha mochawesome mochawesome-merge mochawesome-report-generator
    test:
      commands:
        - npx start-test 'yarn start' 3000 'npx cypress run --reporter mochawesome --reporter-options "reportDir=cypress/report/mochawesome-report,overwrite=false,html=false,json=true,timestamp=mmddyyyy_HHMMss"'
    postTest:
      commands:
        - npx mochawesome-merge cypress/report/mochawesome-report/mochawesome*.json > cypress/report/mochawesome.json
```

### Log output

<details>

```
# Put your logs below this line


```

</details>
