### ISSUE TITLE
Invalid monorepo spec, no appRoot matching path found

### ISSUE THREAD

**Issue by k4l397** [aws-amplify/amplify-hosting#3281]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d3lhvdx4tw196s

### AWS Region

eu-west-2

### Amplify Hosting feature

Frontend builds, Monorepo

### Describe the bug

When deploying a new Amplify app it errors at the end of the frontend build (after all the build steps specified in the build spec have completed.

I get this error:
```
2023-01-31T20:14:44.327Z [ERROR]: !!!Invalid monorepo spec, no appRoot matching dashboard/packages/dashboard found
2023-01-31T20:14:44.327Z [ERROR]: !!!Invalid monorepo app root, please set correct AMPLIFY_MONOREPO_APP_ROOT environment variable
2023-01-31T20:14:44.328Z [ERROR]: !!!Unable to save headers
```

The configuration was copied from an existing amplify app within our repo (which is building fine). We also hit the same issue when trying to create a new app manually in the console.

I've tried setting `AMPLIFY_MONOREPO_APP_ROOT` to the same value as the `appRoot` defined in the build spec (amplify.yml), this results in the build failing a step earlier (in the backend build stage). The path of `appRoot` definitely exists as the build steps work as expected.

### Expected behavior

The application should finish the frontend build step successfully.

### Reproduction steps

1. Connect amplify to a monorepo (see terraform below)
2. Upload build spec with appRoot pointing towards the project that needs building
3. Run a build

### Build Settings

```yaml
# build_spec.yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - yarn install --immutable
    build:
      commands:
        - yarn run build
  artifacts:
    baseDirectory: ./build # Relative to pwd of `build` step.
    files:
      - '**/*'
```

```tf
resource "aws_amplify_app" "app" {
  name       = "amplifyapp"
  repository = "<repo>"

  build_spec = file("${path.module}/build_spec.yaml")

  access_token = <repo_access_token>

  enable_auto_branch_creation = false
  enable_branch_auto_deletion = true
  enable_branch_auto_build    = true

  dynamic "auto_branch_creation_config" {
    content {
      enable_pull_request_preview = true
      enable_auto_build           = false
      framework                   = local.framework
      stage                       = "PULL_REQUEST"
    }
  }

  custom_rule {
    source = "</^[^.]+$|\\.(?!(css|gif|ico|jpg|js|png|txt|svg|woff|ttf|map|json|md)$)([^.]+$)/>"
    status = "200"
    target = "/index.html"
  }

  environment_variables = {
    # https://github.com/tumelohq/docker-images/blob/main/amplify-git-lfs/Dockerfile
    _CUSTOM_IMAGE : "ghcr.io/tumelohq/amplify-git-lfs:latest"
    AMPLIFY_DIFF_DEPLOY : "true", // only deploy if the app root has changed
  }
}

resource "aws_amplify_branch" "master_app" {
  app_id            = aws_amplify_app.app.id
  branch_name       = "master"
  enable_auto_build = true

  framework = "Next.js - SSG"
  stage     = "PRODUCTION"
}
```

Unsure if relevant but we also have a single customHttp.yml at the root of the repo
```yaml
# customHttp.yml
  - appRoot: dashboard/packages/otherdashboard
    customHeaders: *headers
  - appRoot: dashboard/packages/dashboard
    customHeaders: *headers
```

### Log output

<details>

```
# Put your logs below this line


```

</details>
