### ISSUE TITLE
Repository url is not valid

### ISSUE THREAD

**Issue by awesomewaffle007** [aws-amplify/amplify-hosting#3285]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

NEW_APP

### AWS Region

us-east-1

### Amplify Hosting feature

One click deploy

### Describe the bug

I am trying to deploy using github integration. My github integration was successful. When I try to save and deploy, I am getting "Repository url is not valid" error. 

### Expected behavior

save and deploy succeeds

### Reproduction steps

1. Connect with Github
2. After github integration is successful, try to save and deploy

![Screenshot 2023-02-01 at 6 49 57 PM](https://user-images.githubusercontent.com/124062942/216219233-175155e9-53ea-49dd-a02d-0260ca387db6.png)

### Build Settings

```yaml
version: 1
frontend:
  phases:
    # IMPORTANT - Please verify your build commands
    build:
      commands: []
  artifacts:
    # IMPORTANT - Please verify your build output directory
    baseDirectory: /
    files:
      - '**/*'
  cache:
    paths: []
```

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by hloriana** [comment]
Hi @awesomewaffle007 👋🏽 I just walked through these steps and was able to successfully deploy a new application. I noticed that the build script you are using did not populate with the necessary commands to build your application. What frontend framework is your app using?

If you're using react, the build settings should look like:

```
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```
