### ISSUE TITLE
PNPM Monorepo Nextjs SSR Not working

### ISSUE THREAD

**Issue by rushi308** [aws-amplify/amplify-hosting#3304]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d23s4a8slavtvr

### AWS Region

us-east-1

### Amplify Hosting feature

Monorepo

### Describe the bug

SSR is used with AWS Serverless Appsync GraphQL APIs in my pnpm Mono repository Nextjs app. I used AWS Amplify for hosting, however it returns a 500 error.

### Expected behavior

It should work

### Reproduction steps

1. Go to https://main.d23s4a8slavtvr.amplifyapp.com and it should work

### Build Settings

```yaml
version: 1
applications:
  - frontend:
      phases:
        preBuild:
          commands:
            - npm i -g pnpm
            - pnpm add project-schema --filter client --workspace
            - pnpm i
        build:
          commands:
            - npm run build
      artifacts:
        baseDirectory: .next
        files:
          - '**/*'
      cache:
        paths:
          - node_modules/**/*
    appRoot: apps/client
```

### Log output

<details>

```
# Put your logs below this line


```

</details>
