### ISSUE TITLE
Amplify Next.js frontend file returns 500 error

### ISSUE THREAD

**Issue by JasurN** [aws-amplify/amplify-hosting#3310]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d2o8r8q8g2t9n6

### AWS Region

us-east-1

### Amplify Hosting feature

Frontend builds, SSR

### Describe the bug

The problem is when I access a file(size ~ 6MB) on https://feat-temp.d2o8r8q8g2t9n6.amplifyapp.com/files/Whitepaper.pdf
it returns 500,

But I compressed it to 1.5MB and it is downloading fine. 
https://staging.d2o8r8q8g2t9n6.amplifyapp.com/files/Whitepaper.pdf

I suspect that issues it with file size because I tried another 10MB and it returned 500. While other small files downloaded as expected. 
1. https://feat-temp.d2o8r8q8g2t9n6.amplifyapp.com/files/XI1Datasheet-Felix.pdf
2. https://feat-temp.d2o8r8q8g2t9n6.amplifyapp.com/files/XO1Datasheet-Lucius.pdf

### Expected behavior

It should download file without a problem. files

### Reproduction steps

1. https://feat-temp.d2o8r8q8g2t9n6.amplifyapp.com/files/Whitepaper.pdf returns 500,
2. the same file, but compressed https://staging.d2o8r8q8g2t9n6.amplifyapp.com/files/Whitepaper.pdf works fine

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```
