### ISSUE TITLE
Amplify hosting stopped publishin commits out of nowhere, reconnect does nothing

### ISSUE THREAD

**Issue by talaikis** [aws-amplify/amplify-hosting#3340]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

dva2ry3ckn8vc

### AWS Region

eu-central-1

### Amplify Hosting feature

Deployments

### Describe the bug

1) Commit doesn't trigger build
2) Github config always shows "We do not have permission to access this repository. Please update your permissions and try again." with the existing permissions (obviously, builds worked fine few commits ago)

### Expected behavior

To have normally working service.

### Reproduction steps

1. No idea how to repro if that's on AWS side.

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

### Log output

<details>

```
# Put your logs below this line


```

</details>
