### ISSUE TITLE
How can I confirm that env variables are being added to Hosting Lambdas (Web Compute)?

### ISSUE THREAD

**Issue by foobarnes** [aws-amplify/amplify-hosting#3345]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d263pg34gxs8oh

### AWS Region

us-east-1

### Amplify Hosting feature

Environment variables

### Question

I am using [NextAuth](https://next-auth.js.org/). It requires an env variable `NEXTAUTH_URL` to be set.

NextAuth makes available several auth-related api routes with a catchall/decomp. route. `api/auth/[...nextauth].js`

I am logging `process.env.NEXTAUTH_URL` at the bottom of this route generator/config, and it seems to be correctly set at the time of NextAuth's initialization.

Immediately after, however, it appears to be unavailable from NextAuth's perspective. I receive the [`[next-auth][warn][NEXTAUTH_URL]`](https://next-auth.js.org/warnings#nextauth_url) warning stating `Environment variable NEXTAUTH_URL missing. Please set it in your .env file.` I'm not sure why that would be the case.

**How can I confirm that my env variables have been applied to my SSR Lambdas?** I'm using Amplify Hosting in web compute mode. [These instructions](https://github.com/aws-amplify/amplify-hosting/blob/main/FAQ.md#access-lambda-edge-logs) for web dynamic deployments used to be the steps I'd follow to find my lambda IDs.

`api/auth/[...nextauth].js`
---------
```js
import NextAuth from 'next-auth';
// ... imports

export const authOptions = {
  debug: process.env.NODE_ENV !== 'production',
  providers: [
    TwitterProvider({
      clientId: process.env.TWITTER_CLIENT_ID,  // Correctly set
      clientSecret: process.env.TWITTER_CLIENT_SECRET,  // Correctly set
      version: '2.0'
    }),
    // ...more providers here
  ],
  secret: process.env.NEXTAUTH_SECRET  // Correctly set
  // ... other config here
};

console.log("Auth URL: ", process.env.NEXTAUTH_URL);   // Correctly logs (see CloudWatch logs below)

export default NextAuth(authOptions);
```

`CloudWatch Logs`
---------
![image](https://user-images.githubusercontent.com/41340559/222784165-122e83f0-00c0-4d5b-9edc-0d862ce4917a.png)

`Amplify Console Env Variables`
---------
![image](https://user-images.githubusercontent.com/41340559/222785579-c2099085-17b0-48d2-9866-6710b5d14b0e.png)

`next.config.js`
---------
```js
/** @type {import('next').NextConfig} */

const nextConfig = {
  reactStrictMode: true,
  async redirects() {
    // ...
  },
  async rewrites() {
    // ...
  },
  compiler: {
    // ...
  },
  env: {
    // ...
    NEXT_PUBLIC_NEXTAUTH_URL: process.env.NEXTAUTH_URL,
    NEXTAUTH_URL: process.env.NEXTAUTH_URL,
    NEXTAUTH_SECRET: process.env.NEXTAUTH_SECRET,
    // ...
  },
  swcMinify: true,
};

module.exports = () => {
  const plugins = [withSvgr, withBundleAnalyzer, withTM];

  return plugins.reduce((acc, plugin) => plugin(acc), {
    ...nextConfig,
  });
};
```

`amplify.yml`
---------
```yml
version: 1
applications:
  - backend:
      phases:
        build:
          commands:
            - cd ..
            - amplifyPush --simple
            - cd web
    frontend:
      phases:
        preBuild:
          commands:
            - yarn
        build:
          commands:
            - yarn build
            - echo "NEXTAUTH_URL=$NEXTAUTH_URL" >> .env
            - echo "NEXTAUTH_SECRET=$NEXTAUTH_SECRET" >> .env
            - echo "NEXTAUTH_URL=$NEXTAUTH_URL" >> .env.production
            - echo "NEXTAUTH_SECRET=$NEXTAUTH_SECRET" >> .env.production
      artifacts:
        baseDirectory: .next
        files:
          - '**/*'
      # cache:
      #   paths:
      #     - 'node_modules/**/*' # Cache `node_modules` for faster `yarn` or `npm i`
      #     - '.next/cache/**/*' # Cache Next.js for faster application rebuilds
    appRoot: web
```
Questions:
- **How can I confirm that my env variables have been applied to my SSR Lambdas now that I'm using Hosting Compute?**

I appreciate any sanity checking as well. This has been driving me crazy. 🥲
