### ISSUE TITLE
Next.js server responds with cloudfront 403

### ISSUE THREAD

**Issue by joekur** [aws-amplify/amplify-hosting#3356]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d38i4fqw82uakm

### AWS Region

us-east-1

### Amplify Hosting feature

Frontend builds

### Describe the bug

I have deployed a next.js app, for which the build/deploy steps all succeed.

At first, I was seeing 404s for my app. I discovered that there was a redirect rule (it was auto-created, I didn't create it), for all pages `/<*>` as 404. I removed this rule.

Now, I am getting 403 Access Denied from CloudFront. Eg:

```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>R2ZV77JVTKA8QB9D</RequestId>
<HostId>5IUk61uc8ks551tD+t5sYFmYn1oX+vDZ4AWPxfU+2DEsgCfli3xTzRxd8HbY3QEBOHZMUrr+MeM=</HostId>
</Error>
```

I confirmed that running `next build` and `next start` locally work. I have also deployed to vercel with success.

### Expected behavior

I expect a 200 response, with my next.js static index.html page.

### Reproduction steps

1. Visit the app https://test-aws-amplify.d38i4fqw82uakm.amplifyapp.com/
2. See a 403 response

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

### Log output

<details>

```
# Put your logs below this line


```

</details>
