### ISSUE TITLE
High TTFB for NextJs application

### ISSUE THREAD

**Issue by Akhilesh-aarzoo** [aws-amplify/amplify-hosting#3357]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

dyyv7k61mxhcc

### AWS Region

us-east-1

### Amplify Hosting feature

Not Applicable

### Describe the bug

We have a NextJs application hosted on Amplify. We are seeing high TTFB for our application in production. We are getting this problem without any changes at our end. This is happening since 2:30 AM UTC today.

### Expected behavior

TTFB should not take so long. It should be back to normal.

### Reproduction steps

1. Deploy a NextJs app on Amplify on us-east-1
2. Use the hosted application URL on browser and check the Network tab

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
```

### Log output

<details>

```
# Put your logs below this line


```

</details>
