### ISSUE TITLE
CI builds are failing at the build stage - eu-west-3

### ISSUE THREAD

**Issue by bistace** [aws-amplify/amplify-hosting#3360]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d378ukj8e11ytt

### AWS Region

eu-west-3

### Amplify Hosting feature

Backend builds

### Describe the bug

My new application CI builds fail at build stage with this error:
```
2023-03-08T13:05:44.883Z [ERROR]: !!! Unable to assume specified IAM Role. Please ensure the selected IAM Role has sufficient permissions and the Trust Relationship is configured correctly.
2023-03-08T13:05:44.964Z [INFO]: # Starting environment caching...
2023-03-08T13:05:45.580Z [INFO]: # Environment caching completed
Terminating logging...
``` 

I have created an admin role as explained in the docs. 

### Expected behavior

It should be able to build.

### Reproduction steps

Deploy the app via Commit or manually in the Amplify console.

### Build Settings

```yaml
version: 1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```
```


### Log output

<details>

```
# Put your logs below this line
2023-03-08T13:05:44.883Z [ERROR]: !!! Unable to assume specified IAM Role. Please ensure the selected IAM Role has sufficient permissions and the Trust Relationship is configured correctly.
2023-03-08T13:05:44.964Z [INFO]: # Starting environment caching...
2023-03-08T13:05:45.580Z [INFO]: # Environment caching completed
Terminating logging...
```

</details>


### Additional information

NA
