### ISSUE TITLE
Next.js 12 successful deploy throws error 500 because of next/dist/server/next-server. TypeError: handler is not a function

### ISSUE THREAD

**Issue by alexcracea** [aws-amplify/amplify-hosting#3368]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

deuq5sef8ny5q

### AWS Region

us-east-2

### Amplify Hosting feature

SSR

### Describe the bug

The app throws error 500 with `internal server error` message in browser. The logs show `TypeError: handler is not a function` which is clear indication of `next/dist/server/next-server` not handling the request right.
The app works well on any other environments even on localhost i am able to run it after `yarn build` and `yarn start`

### Expected behavior

After a successful deployment the app should be running without errors on the domain

### Reproduction steps

- Set up the Amplify app setting to `WEB_COMPUTE` via the "Migrate" banner action (it shows `Next.js - SSR` now)
- Setup `"next": "^12.3.4",`
- `output: 'standalone'` set up in next.config.js
- project with a few pages, one page has `getServerSideProps`

### Build Settings

```yaml
version: 1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

### Log output

<details>

```
# Put your logs below this line

2023-03-13T01:51:46.334+02:00 | START RequestId: 34ee75d5-2370-455b-8606-284fdf338888 Version: $LATEST
  | 2023-03-13T01:51:46.334+02:00 | info - Loaded env from /tmp/app/.env.production
  | 2023-03-13T01:51:46.347+02:00 | TypeError: handler is not a function
  | 2023-03-13T01:51:46.347+02:00 | at Server.<anonymous> (/tmp/app/server.js:19:11)
  | 2023-03-13T01:51:46.347+02:00 | at Server.emit (node:events:513:28)
  | 2023-03-13T01:51:46.347+02:00 | at parserOnIncoming (node:_http_server:998:12)
  | 2023-03-13T01:51:46.347+02:00 | at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
  | 2023-03-13T01:51:46.351+02:00 | REPORT RequestId: 34ee75d5-2370-455b-8606-284fdf338888 Duration: 17.37 ms Billed Duration: 18 ms Memory Size: 1024 MB Max Memory Used: 120 MB Init Duration: 634.63 ms

```
</details>
