### ISSUE TITLE
Deploying amplify project produces "Uncaught ReferenceError: process is not defined" error

### ISSUE THREAD

**Issue by willb0246** [aws-amplify/amplify-hosting#3370]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d2us9vo3swdw5a/main/23

### AWS Region

us-west-2

### Amplify Hosting feature

One click deploy

### Describe the bug

The app is working fine with localhost (npm start) and I have deployed the app successfully through the Amplify AWS console, using GitHub as the repo. When the app is deployed and I navigate to the URL, I get a blank screen with the attached (below in additional info) error in the console. 

NOTE: I am very happy to share additional details as useful, trying to be concise and not sure which files/code would be useful to share.

### Expected behavior

App is accessible as in local host

### Reproduction steps

1. App is coded (plenty of room for errors here, happy to share any relevant files. I have found suggestions around webpack manipulations that I have done).
2. Deploy through AWS Amplify console
3. navigate to URL

### Build Settings

```yaml
version: 1
backend:
  phases:
    build:
      commands:
        - ln -fs /usr/local/bin/pip3.8 /usr/bin/pip3
        - ln -fs /usr/local/bin/python3.8 /usr/bin/python3
        - pip3 install --user pipenv
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - npm install --force
    build:
      commands: 
        - npm run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

### Log output

<details>

```
# Put your logs below this line

main.c9d3d725.js:formatted:88103 Uncaught ReferenceError: process is not defined
    at 83431 (main.c9d3d725.js:formatted:88103:37)
    at n (main.c9d3d725.js:formatted:117674:21)
    at 38125 (main.c9d3d725.js:formatted:89562:21)
    at n (main.c9d3d725.js:formatted:117674:21)
    at 11341 (main.c9d3d725.js:formatted:88063:25)
    at n (main.c9d3d725.js:formatted:117674:21)
    at main.c9d3d725.js:formatted:118290:17
    at main.c9d3d725.js:formatted:126563:6
    at main.c9d3d725.js:formatted:126564:2
83431 @ main.c9d3d725.js:formatted:88103
n @ main.c9d3d725.js:formatted:117674
38125 @ main.c9d3d725.js:formatted:89562
n @ main.c9d3d725.js:formatted:117674
11341 @ main.c9d3d725.js:formatted:88063
n @ main.c9d3d725.js:formatted:117674
(anonymous) @ main.c9d3d725.js:formatted:118290
(anonymous) @ main.c9d3d725.js:formatted:126563
(anonymous) @ main.c9d3d725.js:formatted:126564
2DevTools failed to load source map: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/browser-polyfill.js.map: System error: net::ERR_FILE_NOT_FOUND
```

</details>

### Additional information

<img width="679" alt="image" src="https://user-images.githubusercontent.com/50647513/225744936-34b95a1e-83d6-4e35-ac20-e3ea9b6a0600.png">
