### ISSUE TITLE
AWS Amplify - 404 error when deploying Nextjs App

### ISSUE THREAD

**Issue by krirkrirk** [aws-amplify/amplify-hosting#3398]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d2ucxgoxb4z8kg

### AWS Region

eu-west-3

### Amplify Hosting feature

Deployments

### Question

I'm trying to deploy a Nextjs (v12) to Amplify.

All the checkmarks are green, but when I visit the URL (provided by AWS), it 404.

My build settings :

```
version: 1
frontend:
  phases:
    preBuild:
        commands:
            - npm ci
    build:
      commands:
        - npm run buildamp
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

The command `npm run buildamp` is simply `next build`

The build directory is indeed `.next`. I have no `/src` directory.

The App is quite big and old, with both TS and JS files. There are some dubious settings in `tsconfig.json`, `jsconfig.json` and `next.config` files.

What should I look into to find the source of the error ?

Thanks !
