### ISSUE TITLE
Build failing with next in AWS amplify but not in dev

### ISSUE THREAD

**Issue by infunit** [aws-amplify/amplify-hosting#3402]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

dx9qc8ofwuagk

### AWS Region

us-east-1

### Amplify Hosting feature

Build settings

### Describe the bug

This error is not very descriptive and I don't really know why it's not building in AWS amplify but works fine to run the dev yarn script.

2023-04-02T01:56:47.528Z [WARNING]: error Command failed with exit code 1.
2023-04-02T01:56:47.528Z [INFO]: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
2023-04-02T01:56:47.536Z [ERROR]: !!! Build failed
2023-04-02T01:56:47.536Z [INFO]: Please check the supported SSR features to find if your build failure is related to an unsupported feature: https://docs.aws.amazon.com/amplify/latest/userguide/ssr-Amplify-support.html#supported-unsupported-features. You may also find this troubleshooting guide useful: https://docs.aws.amazon.com/amplify/latest/userguide/troubleshooting-ssr-deployment.html
2023-04-02T01:56:47.536Z [ERROR]: !!! Non-Zero Exit Code detected
2023-04-02T01:56:47.536Z [INFO]: # Starting environment caching...
2023-04-02T01:56:47.537Z [INFO]: # Environment caching completed

### Expected behavior

Builds successfully 

### Reproduction steps

Trying to build

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - nvm install lts/fermium
        - nvm use lts/fermium 
        - yarn install
    build:
      commands:
        - nvm use lts/fermium
        - node -v
        - yarn run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

### Log output

<details>

```
# Put your logs below this line


```

</details>
