### ISSUE TITLE
Multiple builds started in parallel from commits

### ISSUE THREAD

**Issue by jbarnickol** [aws-amplify/amplify-hosting#3409]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d17s4o0gti878f

### AWS Region

us-east-1

### Amplify Hosting feature

Backend builds

### Describe the bug

We have an amplify project connected to a codecommit repo and have it automatically start builds when code is pushed. Starting on 3/31/23 amplify starts a build on every commit so it's possible to have 3-4 builds running at the same time. Some of the builds typically fail because of an error like "stack is in UPDATE_IN_PROGRESS state and can not be updated" because of the previous build is still running.

This project is 3 years old and until last week it always would run one build at a time. If commits were pushed while a build was running, it would create 1 "pending" build that would start when the previous build finished. Even several pushes would only create one pending build.

To the best of my knowledge we didn't change any configuration or versions, this just started out of the blue. It is causing some headaches in our CI flow, is there any way to change this behavior?

### Expected behavior

 If commits were pushed while a build was running, it would create 1 "pending" build that would start when the previous build finished.

### Reproduction steps

Push code while a build is running

### Build Settings

```yaml
version: 0.1
backend:
  phases:
    build:
      commands:
        - nvm version
        - npm -v
        - npm install -g npm@latest
        - npm -v
        - amplify -v
        - amplifyPush --simple
frontend:
  phases:
    build:
      commands:
        - cd ../../www
        - PUBLIC_URL=https://${AWS_BRANCH}.${AWS_APP_ID}.amplifyapp.com npm run build-production
        
  artifacts:
    baseDirectory: /www/build/
    files:
```

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

<img width="915" alt="AWS_Amplify_console" src="https://user-images.githubusercontent.com/1030307/230130030-43009b5a-b174-4513-859a-f9a48eee0a24.png">
