### ISSUE TITLE
Test step shows before Build in pipeline

### ISSUE THREAD

**Issue by hangoocn** [aws-amplify/amplify-hosting#3414]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d1xwodoqqlnzqe

### AWS Region

ca-central-1

### Amplify Hosting feature

Build settings

### Describe the bug

The pipelines are shown as "Provision -> Test -> Build -> Deploy", which has "Test" step shown before "Build" Step

### Expected behavior

Pipeline shown as "Provision -> Build-> Test -> Deploy"

### Reproduction steps

Go to the amplify app landing page, we can see the pipeline steps shown as  "Provision -> Test -> Build -> Deploy".

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
test:
  phases:
    preTest:
      commands:
        - npm ci
        - npm install -g pm2
        - npm install -g wait-on
        - npm install mocha mochawesome mochawesome-merge mochawesome-report-generator
        - pm2 start npm -- start
        - wait-on http://localhost:3000
    test:
      commands:
        - 'npx cypress run --reporter mochawesome --reporter-options "reportDir=cypress/report/mochawesome-report,overwrite=false,html=false,json=true,timestamp=mmddyyyy_HHMMss"'
    postTest:
      commands:
        - npx mochawesome-merge cypress/report/mochawesome-report/mochawesome*.json > cypress/report/mochawesome.json
        - pm2 kill
  artifacts:
    baseDirectory: cypress
    configFilePath: '**/mochawesome.json'
    files:
      - '**/*.png'
      - '**/*.mp4'
```

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

Although "Test" is shown before "Build", the execution order is Build first then Test. It will execute third step Build first then go back to second step "Test".

But I assume this is still a bug and cause confusion to have "Test" shown before "Build."
