### ISSUE TITLE
App provision stack in pending stage

### ISSUE THREAD

**Issue by cosmosinnovate** [aws-amplify/amplify-hosting#3415]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

NEW_APP

### AWS Region

us-east-1

### Amplify Hosting feature

Deployments

### Describe the bug

App provision stuck in pending and when creating a new app I see this error. 
Houston, there's a problem
pageSize must be greater than 0.

### Expected behavior

I expected the provisioning from Github and build to deploy to work correctly in Amplify.

### Reproduction steps

1. Creating new/deploying new via Github
2. Final process of deploying you will this error "Houston, there's a problem
pageSize must be greater than 0."

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm install
    build:
      commands:
        - npm run build
  artifacts:
    # IMPORTANT - Please verify your build output directory
    baseDirectory: /build
    files:
      - "**/*"
  cache:
    paths:
      - node_modules/**/*
```

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

None
