### ISSUE TITLE
Amplify Hangs on Provisioning

### ISSUE THREAD

**Issue by ThePatrickDavis** [aws-amplify/amplify-hosting#3416]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

NEW_APP

### AWS Region

us-east-2

### Amplify Hosting feature

Git providers

### Describe the bug

When creating a new app in AWS amplify, I get an error "pageSize must be greater than 0." on the app settings card of the configuration.

### Expected behavior

A new amplify app would be created. 

### Reproduction steps

1. Go to AWS Amplify in AWS Console
2. Click "Create New App"
3. Select "Host Web App"
4. Select Github
5. Browse for an existing react app in github and select main
6. Use auto-detected build settings
7. Click Next
8. Click "Save and Deploy"
9. Get error mentioning page size
![Screen Shot 2023-04-10 at 4 14 27 PM](https://user-images.githubusercontent.com/8438887/230990471-ee0f0148-f05c-4258-86ac-26dda54d94cc.png)

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

I'm not sure where to find additional logs?
