### ISSUE TITLE
[nextjs] Missing dependencies for SSR

### ISSUE THREAD

**Issue by taylorsmithgg** [aws-amplify/amplify-hosting#3419]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

dbbff8yaqbc49

### AWS Region

us-west-2

### Amplify Hosting feature

SSR

### Describe the bug

spectaql is installed in my package.json

Hosting compute logs indicate it is missing

### Expected behavior

Dependencies should work like dependencies.

### Reproduction steps

1. Create next.js app
2. Use spectaql

### Build Settings

```yaml
default
```

### Log output

<details>

```
# Put your logs below this line

Error: Cannot find module '/var/task/node_modules/spectaql/dist/spectaql/index'

```

</details>

### Additional information

No workarounds that I am aware of, would appreciate any help.

**Comment by hloriii** [comment]
Hi @taylorsmithgg 👋🏽 thanks for raising this issue. Can you try building your app locally and see if you run into this same error?

**Comment by hloriii** [comment]
@taylorsmithgg can you try building your app locally in `standalone` mode and see if the module is available under the `.next/standalone` directory?

You can do this by adding the following code your `next.config.js` file:

```
module.exports = {
  output: 'standalone',
}
```

If that works, our next course of action would be for us to reproduce the behavior. In that case, it would be helpful if you could provide us a basic repo that produces this issue so we can further investigate.

**Comment by taylorsmithgg** [comment]
@hloriii We were already using standalone in this project.
The dependency is available in `.next/standalone/node_modules`

**Comment by abepuentes** [comment]
@taylorsmithgg maybe this hasn't apply to you but I was having errors using nextjs v13.0.0, first related to images and once that was fixed in a canary-16 revision but we start having issues using a middleware which has a workaround modifying the built. Next v13.2.4 has been working fine.

This is the middleware workaround
```
// amplify.yml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn run build
        - cp -r .next/server/edge-chunks .next/standalone/.next/server/edge-chunks
  artifacts:
    baseDirectory: .next
    files:
      - "**/*"
  cache:
    paths:
      - node_modules/**/*
```
