### ISSUE TITLE
Provisioning not work

### ISSUE THREAD

**Issue by dsursulino** [aws-amplify/amplify-hosting#3420]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

new_app

### AWS Region

us-east-1

### Amplify Hosting feature

Access logs

### Describe the bug

Amplify no longer provisions the build docker. I thought it was a problem with the code version, but even creating a new application is showing an error.

### Expected behavior

What was expected was to provision a docker to build my code

### Reproduction steps

1- Create new app
2 - Build Old App

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

![image](https://user-images.githubusercontent.com/2229631/231289492-b914c09f-6845-479d-90df-d9d78f817689.png)
![image](https://user-images.githubusercontent.com/2229631/231289746-637a9dcd-9dfc-49bb-8e4c-4068f59095c5.png)
