### ISSUE TITLE
Deployment stuck with a message - internal error

### ISSUE THREAD

**Issue by fahidqashio** [aws-amplify/amplify-hosting#3424]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d3mmp4qranpgym

### AWS Region

eu-central-1

### Amplify Hosting feature

Deployments

### Describe the bug

Deployment is stuck with the following error message 

```
2023-04-12T10:09:32 [INFO]: Beginning deployment for application d3mmp4qranpgym, branch:master, buildId 0000000004
2023-04-12T10:10:51 [ERROR]: Internal error
```

### Expected behavior

-> Deployment should be successful or a detailed error message should be provided why it failed

### Reproduction steps

1. Deploy a new version / redeploy a version 
2. The Provision is successful
3. The Build is also successful
4. The error is only on Deploy stage with not much error info to understand the reason for failure

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

### Log output

<details>

```
# Put your logs below this line


```

</details>
