### ISSUE TITLE
Error: Cannot find module 'next/dist/server/next-server.js'

### ISSUE THREAD

**Issue by alex-anikeev** [aws-amplify/amplify-hosting#3425]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d1svddhthsj85t

### AWS Region

eu-west-1

### Amplify Hosting feature

Deployments, SSR

### Describe the bug

We are using monorepo setup with Web Compute which was working fine for a long time and got broken 13.04.23 around 19:00 UTC. 
Some preview builds we have are still functional but if you do a redeployment without any code change it gets broken.

Build itself runs fine and completes successfully but when you access website you get 500 error.

### Expected behavior

Website is accessible after build

### Reproduction steps

1. Deploy a new version / redeploy existing version
2. Provision, Build and Deploy are successful
3. Access website via custom domain or amplifyapp domain

### Build Settings

```yaml
"applications":
- "appRoot": "apps/rio"
  "frontend":
    "artifacts":
      "baseDirectory": ".next"
      "files":
      - "**/*"
    "phases":
      "build":
        "commands":
        - "cd ../.."
        - "nvm use 16"
        - "yarn install --frozen-lockfile"
        - "yarn run build:packages"
        - "cd apps/rio"
        - "yarn build"
        - "cp -r .next/standalone/apps/rio/.next .next/standalone/"
        - "cp -r .next/standalone/apps/rio/server.js .next/standalone/"
"version": 0.1
```

### Log output

<details>

CloudWatch logs:

```
INIT_START Runtime Version: nodejs:16.v12	Runtime Version ARN: arn:aws:lambda:eu-west-1::runtime:734d712d91ebc245bd01c52ae85b4025a7885efd1b8c87c0ce49f3e47d2116a4
--
LOGS	Name: bootstrap	State: Subscribed	Types: [Platform, Function]
node:internal/modules/cjs/loader:998
throw err;
^
Error: Cannot find module 'next/dist/server/next-server.js'
Require stack:
- /tmp/app/server.js
at Function.Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
at Function.Module._load (node:internal/modules/cjs/loader:841:27)
at Module.require (node:internal/modules/cjs/loader:1067:19)
at require (node:internal/modules/cjs/helpers:103:18)
at Object.<anonymous> (/tmp/app/server.js:16:16121)
at Module._compile (node:internal/modules/cjs/loader:1165:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
at Module.load (node:internal/modules/cjs/loader:1043:32)
at Function.Module._load (node:internal/modules/cjs/loader:878:12)
at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
code: 'MODULE_NOT_FOUND',
requireStack: [ '/tmp/app/server.js' ]
}
LOGS	Name: bootstrap	State: Already subscribed	Types: [Platform, Function]
ln: failed to create symbolic link ‘/tmp/app/assets/assets’: Read-only file system
ln: failed to create symbolic link ‘/tmp/app/public/public’: Read-only file system
node:internal/modules/cjs/loader:998
throw err;
^
Error: Cannot find module 'next/dist/server/next-server.js'
Require stack:
- /tmp/app/server.js
at Function.Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
at Function.Module._load (node:internal/modules/cjs/loader:841:27)
at Module.require (node:internal/modules/cjs/loader:1067:19)
at require (node:internal/modules/cjs/helpers:103:18)
at Object.<anonymous> (/tmp/app/server.js:16:16121)
at Module._compile (node:internal/modules/cjs/loader:1165:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
at Module.load (node:internal/modules/cjs/loader:1043:32)
at Function.Module._load (node:internal/modules/cjs/loader:878:12)
at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
code: 'MODULE_NOT_FOUND',
requireStack: [ '/tmp/app/server.js' ]
}
START RequestId: 75c22543-90e3-42a4-9b0b-12076faa3702 Version: $LATEST
RequestId: 75c22543-90e3-42a4-9b0b-12076faa3702 Error: Runtime exited with error: exit status 1Runtime.ExitError
REPORT RequestId: 75c22543-90e3-42a4-9b0b-12076faa3702	Duration: 351.94 ms	Billed Duration: 352 ms	Memory Size: 1024 MB	Max Memory Used: 39 MB
```

</details>

### Additional information

It is possible to redeploy existing versions on previews to reproduce the bug if needed
