### ISSUE TITLE
Wrong AWS_COMMIT_ID for webhook-triggered builds

### ISSUE THREAD

**Issue by shivennn** [aws-amplify/amplify-hosting#3447]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

NA

### AWS Region

us-east-1

### Amplify Hosting feature

Webhooks

### Describe the bug

- When we deploy Amplify application by triggering build through web hook its displays "HEAD" as  "Commit ID".
- AWS_COMMIT_ID = Commit ID = HEAD
- You may refer the attached screen-shot files.
<img width="1440" alt="amplify-app-webhook-test-1" src="https://user-images.githubusercontent.com/101250727/235168719-6f729319-bfbc-466e-a2e6-fd224d1dc20f.png">
<img width="1425" alt="amplify-app-webhook-test-2" src="https://user-images.githubusercontent.com/101250727/235168736-ece86999-fa48-4e5a-bcc1-f2ad36daf9ab.png">
<img width="1440" alt="amplify-app-webhook-test-3" src="https://user-images.githubusercontent.com/101250727/235168742-c829458e-5246-483f-8a29-cbc4fc1c8592.png">

### Expected behavior

AWS_COMMIT_ID = Commit ID = GitHub Commit Hash

### Reproduction steps

1. create sample React App
2. create private repository in GitHub and host all files, directories of React application.
3. deploy Amplify app using GitHub CI/CD and by triggering build through web hook.
4. check and verify "AWS_COMMIT_ID" for GitHub CI/CD and web hook triggered builds. 

### Build Settings

```yaml
version: 1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - echo $AWS_COMMIT_ID
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - echo $AWS_COMMIT_ID
        - npm ci
    build:
      commands:
        - echo $AWS_COMMIT_ID
        - npm run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

### Log output

<details>

```
# Put your logs below this line


```

</details>
