### ISSUE TITLE
AWS Amplify suddenly started falling | [ERROR]: !!! Node version not available: 18

### ISSUE THREAD

**Issue by rahul799** [aws-amplify/amplify-hosting#3454]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d1471mgzqes2gt

### AWS Region

us-east-1

### Amplify Hosting feature

Deployments

### Describe the bug

The PR preview deployments started falling abruptly with below error
`2023-05-02T23:04:15.482Z [WARNING]: !Failed to set up process.env.secrets
2023-05-02T23:04:15.490Z [ERROR]: !!! Node version not available: 18`

### Expected behavior

Node Version 18 must be available

### Reproduction steps

1. Use VERSION_NODE=18.3.0

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by espenbye** [comment]
We experienced the same issue today. This seemed to solve it for us:
- Remove node version from "Live package updates" under Build settings
- Update `amplify.yml` to specify node version (nvm use 18):
```
backend:
    phases:
        build:
            commands:
                - nvm use 18
                - npm install
                - '# Execute Amplify CLI with the helper script'
                - amplifyPush --simple
```
