### ISSUE TITLE
Very slow Amplify hosting performance

### ISSUE THREAD

**Issue by afern247** [aws-amplify/amplify-hosting#3462]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d3fooq4aiahxc0

### AWS Region

us-east-1

### Amplify Hosting feature

Performance mode

### Describe the bug

I have a very basic landing page at `road2crypto.com` and it's crazy the time it takes to load the page when it's the first time the user visits it (no cache). There is a significant delay from amplify, I do have performance mode enabled, what else can I do to improve performance and response time for first time visitors?

For context, this is a React/Next.js web app

Thanks

### Expected behavior

Load within 2 seconds

### Reproduction steps

Visit the page with incognito, no cache for the first time

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
        - npx next telemetry disable
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
      - '.next/cache/**/*'
```
