### ISSUE TITLE
Starting today, the site deployed with amplify is showing an internal server error

### ISSUE THREAD

**Issue by jangmang** [aws-amplify/amplify-hosting#3468]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

.....

### AWS Region

us-east-1

### Amplify Hosting feature

Deployments

### Describe the bug

Starting today, the site deployed with amplify is showing an internal server error

### Expected behavior

Show browser is Internal Server Error

### Reproduction steps

After amplify build

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - if [ "${AWS_BRANCH}" = "test" ]; then cp .env.test .env; fi
        - if [ "${AWS_BRANCH}" = "dev" ]; then cp .env.dev .env; fi
        - if [ "${AWS_BRANCH}" = "prod" ]; then cp .env.prod .env; fi
        - yarn run build
  artifacts:
    baseDirectory: .next
    files:
      - "**/*"
  cache:
    paths:
      - node_modules/**/*
```

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

ttttttttt
