### ISSUE TITLE
Custom headers disabled when switching access control settings.

### ISSUE THREAD

**Issue by olivierlemasle** [aws-amplify/amplify-hosting#3480]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d2iwjzo691jqyq

### AWS Region

eu-west-1

### Amplify Hosting feature

Access control, Custom headers

### Describe the bug

Custom headers specified in `customHttp.yml` are disabled when switching access control settings.

A new deployment is needed to add custom headers back.

### Expected behavior

Access control settings should not have any impact on custom headers.

### Reproduction steps

1. Deploy an Amplify app with `customHttp.yml`. The custom headers are sent correctly (verify with `curl -sI https://...`)
2. In _Access control_ settings, restrict access to the branch, with a password. The **custom headers are not sent anymore** (test with `curl -sI -u "user:password https://...`)
3. Redeploy the application. Custom headers are sent.
4. In _Access control_ settings, make the app "Publicly viewable". Again, custom headers are not sent until a new deployment is made.

### Build Settings

```yaml
In `customHttp.yml`:


customHeaders:
  - pattern: '**'
    headers:
      - key: 'Strict-Transport-Security'
        value: 'max-age=31536000; includeSubDomains'
      - key: 'X-Frame-Options'
        value: 'SAMEORIGIN'
      - key: 'X-XSS-Protection'
        value: '1; mode=block'
      - key: 'X-Content-Type-Options'
        value: 'nosniff'
      - key: 'Content-Security-Policy'
        value: "default-src 'self'"
```
