### ISSUE TITLE
NEXTAUTH_URL environment variable not picked up in runtime

### ISSUE THREAD

**Issue by olemaiwald** [aws-amplify/amplify-hosting#3483]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d3v2fml5415wm2

### AWS Region

eu-central-1

### Amplify Hosting feature

Frontend builds

### Describe the bug

When deploying my Next JS application, I want to set an environment variable NEXTAUTH_URL.
I have set the variable via the environment variables tab in the Amplify console.

This variable also gets picked up in the build step, as I have verified with an echo $NEXTAUTH_URL in the amplify.yml file.

However, when looking at the hosting compute logs, I find the following lines 

[next-auth][warn][NEXTAUTH_URL] 
https://next-auth.js.org/warnings#nextauth_url

indicating that there is no NEXTAUTH_URL present in the configuration and the app defaults to a localhost configuration.

When running the same application on localhost I can successfully set the environment variable and it gets picked up by the application.

### Expected behavior

Amplify should pick up the environment variable NEXTAUTH_URL.

### Reproduction steps

1. Set up a NextJS project with a NextAuth.js configuration file in pages/api/auth/[nextauth].js (https://next-auth.js.org/getting-started/example)
2. Set an environment variable called NEXTAUTH_URL with an arbitrary value
3. Deploy the project to Amplify
4. Check the build logs for the next log statements complaining about the missing URL

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
        - echo The NEXTAUTH_URL is $NEXTAUTH_URL

    build:
      commands:
        - yarn run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

### Log output

<details>

```
# Put your logs below this line
2023-05-12T15:48:36.592Z [INFO]: # Executing command: echo The NEXTAUTH_URL is $NEXTAUTH_URL
2023-05-12T15:48:36.592Z [INFO]: The NEXTAUTH_URL is https://myurl.com
                                 # Completed phase: preBuild
                                 # Starting phase: build
                                 # Executing command: yarn run build
2023-05-12T15:48:36.716Z [INFO]: yarn run v1.22.0
2023-05-12T15:48:36.742Z [INFO]: $ next build


```

</details>

**Comment by hloriii** [comment]
Hi @olemaiwald 👋🏽 thanks for raising this question. To access your environment variables at runtime, you'll need to echo them into your `.env` file. 

The Next.js server component doesn't have access to environment variables by default to protect any secrets stored as environment variables that are being accessed during the build phase.

You can update your amplify.yml to echo the desired environment variables into a `.env` file that your app will be able to access during runtime. 

Here is an example of how you can accomplish this:

```
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - env | grep -e DB_HOST -e DB_USER -e DB_PASS >> .env.production
        - env | grep -e NEXT_PUBLIC_ >> .env.production
        - npm run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
      - .next/cache/**/*
     ```

Please refer to our documentation for more information: [Making environment variables accessible to server-side runtimes](https://docs.aws.amazon.com/amplify/latest/userguide/ssr-environment-variables.html).
