### ISSUE TITLE
Vite SSR App Hosting

### ISSUE THREAD

**Issue by charlieforward9** [aws-amplify/amplify-hosting#3490]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d104w4v8nmd5no

### AWS Region

us-east-2

### Amplify Hosting feature

SSR

### Question

I would like to be able to access my site through the production link provided through Amplify Hosting. I am using Vite with [Vite SSR Plugin](https://github.com/brillout/vite-plugin-ssr) for frontend tooling. 

<section>
Build Settings
</section>
<details>

```yml
version: 1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
        - # Rename .js file to be properly called
        - mv src/aws-exports.js src/aws-exports.ts
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build #(calls vite build)
  artifacts:
    # IMPORTANT - Please verify your build output directory
    baseDirectory: dist/client
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

</details>

Build Folder Architecture
![Screen Shot 2023-05-23 at 9 30 40 AM](https://github.com/aws-amplify/amplify-hosting/assets/62311337/0d7a384c-cd3f-4a6d-9653-3c8577e16702)

I read that [Amplify automatically detects when using SSR](https://docs.aws.amazon.com/amplify/latest/userguide/server-side-rendering-amplify.html), how could I configure my application to match this spec?

Currently, when I run a build. It succeeds but [my site](https://main.d104w4v8nmd5no.amplifyapp.com/) fails to show content

(@Brillout)
