### ISSUE TITLE
Next js amplify 404 error in index.tsx file

### ISSUE THREAD

**Issue by sachila** [aws-amplify/amplify-hosting#3512]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

NEW_APP

### AWS Region

ap-southeast-1

### Amplify Hosting feature

Deployments, Redirects

### Describe the bug

I've managed to deploy the nextjs app in Amplify. 

But for the landing page (index.tsx) and child pages ended with index.tsx,  I get the 404 error. 

But for routes with any other name works fine.

working

- pages/search.tsx
- pages/review/review.tsx

not working

-   pages/index.tsx
-   pages/business/index.tsx

versions
    "next": "^13.0.4",

### Expected behavior

The landing page needs to render index.tsx content

### Reproduction steps

yarn build
yarn start

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - rm -rf node_modules -rf yarn.lock && yarn install --frozen-lockfile
    build:
      commands:
        - yarn build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

### Log output

<details>

```
# Put your logs below this line


```

</details>
