### ISSUE TITLE
migration from web-dynamic to web-compute (next 12) cause cached deploy

### ISSUE THREAD

**Issue by multivoltage** [aws-amplify/amplify-hosting#3516]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d2skhgz4a0rx0t

### AWS Region

eu-west-1

### Amplify Hosting feature

Deployments, Frontend builds

### Describe the bug

I migrated my app from WEB-DYNAMIC (next 11) to COMPUTE (12.x), with node 16
After that I saw build green.
But my site has old code (and old next version).

I had similar issue 5 months ago (and other people). Now the scenario is the same but after a Migration.
Looking at step "build" I noticed that now there are not info about s3, cloudfront etc. These info were visible yesterday when all deploy was good

### Expected behavior

A deploy cause a cache invalidation and the site host jew version.

### Reproduction steps

1. setup a next 11 web dynamic
2. migrate to next 12 and compute.

### Build Settings

```yaml
version: 0.1
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
      - .next/cache/**/*
```

### Log output

<details>

```
# Put your logs below this line
2023-06-07T15:44:30 [INFO]: Beginning deployment for application d2skhgz4a0rx0t, branch:feature/251--node-16-nextjs12, buildId 0000000002
2023-06-07T15:44:53 [INFO]: Deployment complete

```

</details>
