### ISSUE TITLE
Github check never completes

### ISSUE THREAD

**Issue by blsz** [aws-amplify/amplify-hosting#3524]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d1r644r8c33agt

### AWS Region

us-east-1

### Amplify Hosting feature

Web previews

### Describe the bug

I have the same issue as https://github.com/aws-amplify/amplify-hosting/issues/2598.

Amplify Github check never reports complete despite the build building successfully. Instead, we see that the build is in "In Progress" after several hours despite the build finishing successfully in several minutes.

### Expected behavior

Amplify Github check should always report the actual status of the build or have some mechanism to restart the check besides pushing another commit.

### Reproduction steps

1. Create a PR against a branch you have previews enabled for

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - rvm install 2.7.1
        - ruby -v
        - gem install bundler:2.3.11
        - bundle install
    # IMPORTANT - Please verify your build commands
    build:
      commands:
        - if [ "${AWS_BRANCH}" = "main" ]; then JEKYLL_ENV=production bundle exec jekyll build; fi
        - if [ "${AWS_BRANCH}" != "main" ]; then JEKYLL_ENV=development bundle exec jekyll build; fi
  artifacts:
    # IMPORTANT - Please verify your build output directory
    baseDirectory: _site
    files:
      - '**/*'
  cache:
    paths: []
```

### Log output

<details>
"Build successfully completed"

"No tests have been configured for this app, check our walkthrough to get started!"
```
2023-06-09T02:06:33 [INFO]: Beginning deployment for application d1r644r8c33agt, branch:pr-242, buildId 0000000001
2023-06-09T02:06:34 [INFO]: Got archive: 36631051 bytes
2023-06-09T02:06:36 [INFO]: Deployment complete

```

</details>
