### ISSUE TITLE
VERSION_AMPLIFY stuck at 6.3.1

### ISSUE THREAD

**Issue by CGarces** [aws-amplify/amplify-hosting#3539]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d2y6lpj9x9jk05

### AWS Region

eu-west-1

### Amplify Hosting feature

Build settings

### Describe the bug

I'm trying to update the amplify version used to build the application with de CI/CD

In the provision status I always see 

ENV VERSION_AMPLIFY=6.3.1

I have manually set the build image settings to 

Amplify CLI latest 
But nothing happens

### Expected behavior

CI/CD is always build with the latest amplify CLI version.

### Reproduction steps

1. Change the Build image settings section with Amplify CLI latest 
2. review the logs at "provision" stage

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci --legacy-peer-deps
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: dist/awsdirectory
    files:
      - "**/*"
  cache:
    paths:
      - node_modules/**/*

backend:
  phases:
    build:
      commands:
        - ln -fs /usr/local/bin/pip3.8 /usr/bin/pip3
        - ln -fs /usr/local/bin/python3.8 /usr/bin/python3
        - pip3 install --user pipenv
        - amplifyPush --simple
```

### Log output

<details>

```
# Framework Versions
ENV VERSION_NODE_8=8.12.0
ENV VERSION_NODE_10=10.16.0
ENV VERSION_NODE_12=12
ENV VERSION_NODE_14=14
ENV VERSION_NODE_16=16
ENV VERSION_NODE_17=17
ENV VERSION_NODE_DEFAULT=$VERSION_NODE_14
ENV VERSION_RUBY_2_4=2.4.6
ENV VERSION_RUBY_2_6=2.6.3
ENV VERSION_BUNDLER=2.0.1
ENV VERSION_RUBY_DEFAULT=$VERSION_RUBY_2_4
ENV VERSION_HUGO=0.75.1
ENV VERSION_YARN=1.22.0
ENV VERSION_AMPLIFY=6.3.1

```

</details>

### Additional information

What is the correct way to ensure that the amplify CLI is updated?

**Comment by Jay2113** [comment]
Hi @CGarces 👋 , thanks for reaching out to us!

When you set the `Amplify CLI` package version to `latest` using [live package updates](https://docs.aws.amazon.com/amplify/latest/userguide/custom-build-image.html#configuring-live-updates) in the build settings, the package is patched at build time and you can review the logs for it as follows:
```
1. For a particular build, navigate to the Build step of the CI/CD pipeline
2. Under the Cloning repository section, it should print the following:

2023-06-17T10:48:19.262Z [INFO]: # Patching NPM package '@aws-amplify/cli' from 10.5.2 to 12.1.1...
2023-06-17T10:48:35.212Z [INFO]: # Done patching NPM package '@aws-amplify/cli' to version 12.1.1
```

Additionally, you can also verify the Amplify CLI version that is being used for your app using the `amplify --version` in your build settings:
```
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - amplify --version
        - npm ci --legacy-peer-deps
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: dist/awsdirectory
    files:
      - "**/*"
  cache:
    paths:
      - node_modules/**/*

backend:
  phases:
    build:
      commands:
        - ln -fs /usr/local/bin/pip3.8 /usr/bin/pip3
        - ln -fs /usr/local/bin/python3.8 /usr/bin/python3
        - pip3 install --user pipenv
        - amplifyPush --simple
```

The version will be printed in the backend build logs as follows: `2023-06-19T16:36:33.688Z [INFO]: 12.1.1`.
