### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by artrit10** [aws-amplify/amplify-hosting#3548]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d1uwrttf1z973l

### AWS Region

eu-west-1

### Amplify Hosting feature

Frontend builds

### Frontend framework

React

### Next.js version

N/A

### Next.js router

N/A

### Describe the bug

[WARNING]: "GoThreeBars" is not exported by "node_modules/react-icons/go/index.esm.js", imported by "node_modules/flowbite-react/lib/esm/components/Navbar/NavbarToggle.js".
                                    file: /codebuild/output/src688378717/src/maxx-hire-react/node_modules/flowbite-react/lib/esm/components/Navbar/NavbarToggle.js:3:9
                                    1: import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
                                    2: import classNames from 'classnames';
                                    3: import { GoThreeBars } from 'react-icons/go';
                                    ^
                                    4: import { mergeDeep } from '../../helpers/mergeDeep';
                                    5: import { useTheme } from '../Flowbite/ThemeContext';

### Expected behavior

Build done

### Reproduction steps

AWS Amplify Build

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - yarn
    build:
      commands:
        - yarn build
  artifacts:
    # IMPORTANT - Please verify your build output directory
    baseDirectory: dist
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

### Log output

<details>

```
# Put your logs below this line


```

</details>
