### ISSUE TITLE
React Native Expo Build Error 'expo/config'

### ISSUE THREAD

**Issue by osmanelsoz** [aws-amplify/amplify-hosting#3550]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d34tmkt9f8wd27

### AWS Region

eu-north-1

### Amplify Hosting feature

Frontend builds

### Frontend framework

React

### Next.js version

not relevant

### Next.js router

App Router

### Describe the bug

My builds started to fail with error 'Cannot find module 'expo/config'

# Completed phase: preBuild
# Starting phase: build
This command is being executed with the global Expo CLI. Learn more: https://blog.expo.dev/the-new-expo-cli-f4250d8e3421
                                    To use the local CLI instead (recommended in SDK 46 and higher), run:
› npx expo export:web
Cannot find module 'expo/config'
Require stack:
                                    - /root/.nvm/versions/node/v14.21.3/lib/node_modules/expo-cli/node_modules/@expo/webpack-config/webpack/env/paths.js
                                    - /root/.nvm/versions/node/v14.21.3/lib/node_modules/expo-cli/node_modules/@expo/webpack-config/webpack/env/validate.js
                                    - /root/.nvm/versions/node/v14.21.3/lib/node_modules/expo-cli/node_modules/@expo/webpack-config/webpack/env/index.js
                                    - /root/.nvm/versions/node/v14.21.3/lib/node_modules/expo-cli/node_modules/@expo/webpack-config/webpack/index.js
                                    - /root/.nvm/versions/node/v14.21.3/lib/node_modules/expo-cli/node_modules/@expo/webpack-config/webpack.config.js
                                    - /root/.nvm/versions/node/v14.21.3/lib/node_modules/expo-cli/node_modules/xdl/build/Webpack.js
                                    - /root/.nvm/versions/node/v14.21.3/lib/node_modules/expo-cli/node_modules/xdl/build/internal.js
                                    - /root/.nvm/versions/node/v14.21.3/lib/node_modules/expo-cli/node_modules/xdl/build/index.js
                                    - /root/.nvm/versions/node/v14.21.3/lib/node_modules/expo-cli/build/exp.js
                                    - /root/.nvm/versions/node/v14.21.3/lib/node_modules/expo-cli/bin/expo.js

### Expected behavior

I was able smoothly complete builds 4 weeks ago, I started on the project and only change some visuals with no new package added.

### Reproduction steps

It is a basic app

### Build Settings

```yaml
version: 1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
        - nvm use 14
        - npm install --silent --global expo-cli
        - |-
          if [ -f yarn.lock ]; then
           yarn
          elif [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then
           npm ci
          else
           npm install
          fi
    build:
      commands:
        - 'expo build:web'
  artifacts:
    baseDirectory: web-build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
      - $(npm root --global)/**/*
```

### Log output

<details>

```
# Put your logs below this line

[log (15).txt](https://github.com/aws-amplify/amplify-hosting/files/11848110/log.15.txt)

```

</details>
