### ISSUE TITLE
UNCOMPRESSED_CODE_SIZE_EXCEEDED (frequent issue) 

### ISSUE THREAD

**Issue by kantorcodes** [aws-amplify/amplify-hosting#3556]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d1nra4pyobb96k

### AWS Region

us-east-1

### Amplify Hosting feature

Frontend builds

### Frontend framework

Next.js

### Next.js version

13.4.7

### Next.js router

Pages Router

### Describe the bug

Frequently builds fail to deploy because they exceed the 120 MB limit. Getting under this limit with few dependencies is virtually impossible. Is it possible to somehow increase this arbitrary storage limit? 

We've also tried a few of the suggestions to compress the file size, to no avail. 

### Expected behavior

Builds should deploy 

### Reproduction steps

1. Deploy an application that goes slightly over the 120mb limit
2. The build fails to deploy

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - yarn install --frozen-lockfile
        #   - yarn install
    build:
      commands:
        - npm run build
        # - rm -rf .next/standalone/node_modules/@buidlerlabs/hashgraph-venin-js/node_modules/solc
        - du -h .next/standalone
        #- allfiles=$(ls -al ./.next/standalone/**/*.js)
        #- npx esbuild $allfiles --minify --outdir=.next/standalone --platform=node --target=node16 --format=cjs --allow-overwrite
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

### Log output

<details>

```
# Put your logs below this line


```

</details>
