### ISSUE TITLE
Build failed to complete successfully. Reason: Build container ran out of memory [vite build]

### ISSUE THREAD

**Issue by parkournick00110010** [aws-amplify/amplify-hosting#3575]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d5wnfx63di45l

### AWS Region

us-east-1

### Amplify Hosting feature

Build settings

### Question

I saw that there are issues similar to mine but the solution for them:

"NODE_OPTIONS=--max-old-space-size=4096 "

doesn't work for me, the instance still runs out of memory and I can't figure out why, the only things I run is `pnpm install` and `vite build`

My amplify.yml settings:

```yml
version: 1
applications:
  - frontend:
      phases:
        preBuild:
          commands:
            - npm install -g pnpm
            - cd apps/client-app && pnpm install --no-frozen-lockfile
        build:
          commands:
            - pnpm build
      artifacts:
        baseDirectory: apps/client-app/dist
        files:
          - '**/*'
      cache:
        paths:
          - node_modules/**/*
      buildPath: /
    appRoot: apps/client-app
```
