### ISSUE TITLE
SSL not showing up in production (after not touching app)

### ISSUE THREAD

**Issue by behaviary** [aws-amplify/amplify-hosting#3580]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d3hp54chnllm3g

### AWS Region

us-east-1

### Amplify Hosting feature

Custom domain

### Frontend framework

React

### Next.js version

^12.3.1

### Next.js router

App Router

### Describe the bug

Production SSL is not working. No changes have been made to the app or console since last time it was. I suspect the cert is not refreshing? 
<img width="367" alt="Screenshot 2023-07-10 at 9 39 58 AM" src="https://github.com/aws-amplify/amplify-hosting/assets/6679554/e4fef71b-c8fe-4668-8608-b4871ad7cb42">
<img width="748" alt="Screenshot 2023-07-10 at 9 30 01 AM" src="https://github.com/aws-amplify/amplify-hosting/assets/6679554/22eb8f48-f040-4df8-b56c-89f9e0ccec18">

### Expected behavior

That the cert doesn't expire at all.

### Reproduction steps

1. Do nothing
2. See that your production environment is not able to use HTTPS

### Build Settings

```yaml
version: 1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

### Log output

<details>

```
# Put your logs below this line
n/a

```

</details>

### Additional information

NA
