### ISSUE TITLE
Deleted subpage still show up to client after new built / deployment

### ISSUE THREAD

**Issue by yungt** [aws-amplify/amplify-hosting#3588]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d36scflfxvj7fq

### AWS Region

us-east-1

### Amplify Hosting feature

Frontend builds

### Frontend framework

Next.js

### Next.js version

13.1.6

### Next.js router

App Router

### Describe the bug

One of my app's static subpages was built without cache-control header settings setup, so it was defaulted to amplify cloudfront value with the following 

s-maxage=31536000, stale-while-revalidate

This page is then supposed to be removed and show a 404.

However, when clients who already previously visited the page visits the page again, they're still able to see the page normally, since amplify cloudfront returns a 304. Is there a way to configure / request amplify to invalidate client cache on new build / deployment?

(clients who visit the page for the first time see the correct behavior - 404)

### Expected behavior

Clients to see 404

### Reproduction steps

1. Build a ssg page (default cache-control: s-maxage=31536000, stale-while-revalidate)
2. Delete page in source code
3. Deploy new build
4. Visit page again and still see page

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

### Log output

<details>

```
# Put your logs below this line


```

</details>
