### ISSUE TITLE
Server-Sent Events - Text Streaming

### ISSUE THREAD

**Issue by kyleroberts-ai** [aws-amplify/amplify-hosting#3592]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

dn3cwt575mcce

### AWS Region

eu-west-2

### Amplify Hosting feature

SSR

### Frontend framework

Next.js

### Next.js version

18

### Next.js router

Pages Router

### Describe the bug

Hi,

I've built a AI Chatbot application similar to that of the chat GPT.

My application supports message streaming, meaning sending a message will stream the response to the user in real-time.

Unfortunately, for some reason, this feature doesn't seem to work on AWS Amplify. I have tried other hosting platforms like Vercel and it works perfectly on there. 

### Expected behavior

When a user types an input, the chatbot should stream the response back to the user. Like Chat GPT.

### Reproduction steps

N/A

### Build Settings

```yaml
version: 1
backend:
  phases:
    build:
      commands:
        - nvm use 18
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
       commands:
        - env | grep -e OPENAI_API_KEY >> .env.production
        - npm run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

https://vercel.com/blog/an-introduction-to-streaming-on-the-web
