### ISSUE TITLE
421 ERROR - Instability accessing application.

### ISSUE THREAD

**Issue by itsMeBruno** [aws-amplify/amplify-hosting#3595]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

https://us-east-1.console.aws.amazon.com/amplify/home?region=us-east-1#/d643zn3exdmsl

### AWS Region

us-east-1

### Amplify Hosting feature

Redirects

### Frontend framework

React

### Next.js version

N/A

### Next.js router

N/A

### Describe the bug

We were facing an instability accesing application. "421 ERROR the request could not be satisfied". The error description was about two things.

1 -  Too much trafic, bug we didn´t see anything unusual on Monitoring tab.
2 - Distribution does not match the right certificate.

about 10 minutes later application was back.

### Expected behavior

It should render us home page.

### Reproduction steps

N/A. It´s back.

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```
