### ISSUE TITLE
The css and js files with `_next` folder path is returning 404 Suddenly

### ISSUE THREAD

**Issue by mohanhari** [aws-amplify/amplify-hosting#3597]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

dar7mdxkfsfki

### AWS Region

us-east-2

### Amplify Hosting feature

Deployments

### Frontend framework

Next.js

### Next.js version

12.0.9

### Next.js router

Pages Router

### Describe the bug

I have set up the amplify for our app long back. But when i deployed my recent changes today suddenly the css and js files started throwing `404` errora 

### Expected behavior

It should not throw 404 errora error

### Reproduction steps

Its working in local, only in amplify its not workingIt's

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

### Log output

<details>

```
# Put your logs below this line


```

</details>
