### ISSUE TITLE
About Amplify Nextjs build bundle size limitation

### ISSUE THREAD

**Issue by hunganhAtWhill** [aws-amplify/amplify-hosting#3601]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d3qp8myddx9t1e

### AWS Region

us-east-1

### Amplify Hosting feature

SSR

### Question

Regarding 200MB limitation mentioned in this documentation
https://docs.aws.amazon.com/amplify/latest/userguide/troubleshooting-ssr-deployment.html

It says that the current limit for "build output size" is 200MB, but I wonder when and how the calculation for the "build output size" happen. I have a build settings yml file as following. As you can see after I build the project, I sync to S3 and remove it from supposed build artifact folder. My question is, even with this build setup would amplify build pipeline fail when I have total "build output size" > 200MB ? I cannot provide evidence, but I am very certain that at the beginning of the project when we had many unoptimized assets being bundled, the "build output size" was more than 200MB and even with the following build settings, the build pipeline failed with "The size of the build output is too large" error. Please, help me clarfify. Thank you!
```
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
        - aws s3 sync .next/static s3://{static_bucket}/_next/static
        - aws s3 sync public/videos s3://{static_bucket}/videos
        - aws s3 sync public/images s3://{static_bucket}/images
        - rm -rf .next/static && rm -rf public/videos && rm -rf public/images
        - aws cloudfront create-invalidation --distribution-id cdnId --paths "/videos/*" "/images/*" "/_next/*"

  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*

```
