### ISSUE TITLE
Amplify App url returns 404 even after successful deployment phase

### ISSUE THREAD

**Issue by Raajesh-M** [aws-amplify/amplify-hosting#3602]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

ap-south-1#/dx0suz5gm966j

### AWS Region

ap-south-1

### Amplify Hosting feature

Deployments

### Question

Out of the 3 connected branches, `staging` is the newer branch. Deployment is successful, but the website is not served in `amplifyapp.com` url itself. No custom domains involved. 

<img width="514" alt="image" src="https://github.com/aws-amplify/amplify-hosting/assets/104615791/1d96b582-7c09-4d00-9855-ba38091bc45a">

<br />

Build phase created a valid archive successfully. Local isolated testing proved successful hosting via `dist/index.html`.

<img width="548" alt="image" src="https://github.com/aws-amplify/amplify-hosting/assets/104615791/7d78f7fa-c09a-459a-a85f-695d0ca5ba10">

```
# amplify.yml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm i
        - rm -rf .parcel-cache
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: dist
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

Deployments in rest of the branches work fine, but not in `staging`. Also deleted staging branch from app settings and created anew, still issue persists
