### ISSUE TITLE
getting a 404 while deploy says successful

### ISSUE THREAD

**Issue by mnkcoder** [aws-amplify/amplify-hosting#3614]
### Before opening, please confirm:

- [x] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d1phzufzqbipnt

### AWS Region

us-west-1

### Amplify Hosting feature

Build settings

### Frontend framework

React

### Next.js version

N/A

### Next.js router

N/A

### Describe the bug

I am trying to deploy this app https://github.com/mnkcoder/vite-express-project and receiving a 404

While the deploy status is green I'm receiving a 404 with below XML

```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>VARQ9ACVWPHGK65G</RequestId>
<HostId>QMMEbKSRMq+9bmZkf0HSS1vfuXo8mxWE3J7b9ZufpAVTC+Mz1f0c/6vsKgUhYeQ/Bm7bBhRph2k=</HostId>
</Error>
```

Here is the deployed url https://main.d1phzufzqbipnt.amplifyapp.com/

Also, wondering where or can one download the zipped/unzipped deployed files associated with a build? and where would Amplify fetch the start command to run after build step in the yml?

### Expected behavior

Should not receive a 404 and render the home route.

### Reproduction steps

visit https://main.d1phzufzqbipnt.amplifyapp.com/ to receive the 404 error

### Build Settings

```yaml
version: 1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    # IMPORTANT - Please verify your build output directory
    baseDirectory: /build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by ferdingler** [comment]
The `baseDirectory` on your amplify.yml needs to be a relative path. Relative to your project's root. In your example, you have specified an absolute path `/build`. So try changing your buildspec to this: 

```yml
artifacts:
    baseDirectory: build
    files:
      - '**/*'
```

Feel free to reopen if you are still facing issues.
