### ISSUE TITLE
Next.js rewrite feature suddenly not working for static files under /_next, return 404

### ISSUE THREAD

**Issue by shaunxu-grab** [aws-amplify/amplify-hosting#3619]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d3kdy9m8ryb39u

### AWS Region

ap-southeast-1

### Amplify Hosting feature

Deployments

### Frontend framework

Next.js

### Next.js version

13.2.4

### Next.js router

App Router

### Describe the bug

I have configure a `assetPrefix: '/experiment'` in next.config.js to ensure my static has a `/experiment` prefix (used for distinguish with other path so it will redirect to amplify). And I add a middleware.ts to apply a rewrite rule to remove `/experiment` to ensure css and js able to load.

```javascript
import { NextRequest, NextResponse } from 'next/server'

export function middleware(req: NextRequest): NextResponse {
  const urlPathname = req.nextUrl.pathname

  if (urlPathname.startsWith('/experiment')) {
    const newPathname = urlPathname.replace('/experiment', '')

    // Rewrite url
    req.nextUrl.pathname = newPathname
    return NextResponse.rewrite(req.nextUrl)
  }

  return NextResponse.next()
}

```

The logic works in local. And it also works about two weeks ago. However recent deployment make the css and js resouce return 404.

Suspect there is some logic prevent rewrite apply to css and js.

Page:
https://staging.d3kdy9m8ryb39u.amplifyapp.com/exp0623/ph

Resources example.
https://staging.d3kdy9m8ryb39u.amplifyapp.com/experiment/_next/static/chunks/7fd0f9f1-84000337c4f35b63.js 404
https://staging.d3kdy9m8ryb39u.amplifyapp.com/_next/static/chunks/7fd0f9f1-84000337c4f35b63.js loads properly

The rewrite logic is working for html as https://staging.d3kdy9m8ryb39u.amplifyapp.com/expriment/exp0623/ph can load 

### Expected behavior

The resource does not return 404

### Reproduction steps

1.  Open https://staging.d3kdy9m8ryb39u.amplifyapp.com/exp0623/ph, observer all the css and js file under /experiment/_next/static/ all show 404

### Build Settings

```yaml
version: 1
applications:
  - frontend:
      phases:
        preBuild:
          commands:
            - export GITLAB_NPM_TOKEN={process.env.NPM_TOKEN}
            - npm install
        build:
          commands:
            - npm run build --workspace=packages/ui-lib
            - npm run build --workspace=packages/experiments
      artifacts:
        baseDirectory: packages/experiments/.next
        files:
          - '**/*'
      cache:
        key:
          files:
            - package-lock.json
        paths:
          - node_modules/**/*
      buildPath: /
    appRoot: packages/experiments
```

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

<img width="412" alt="image" src="https://github.com/aws-amplify/amplify-hosting/assets/140607570/4eeb9d2a-4841-48d9-96e6-0a0555316ff5">
