### ISSUE TITLE
Nx Next.js amplify deployment returns 404

### ISSUE THREAD

**Issue by GeorgePasquali** [aws-amplify/amplify-hosting#3630]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d1cz9isa8tel3v

### AWS Region

eu-south-1

### Amplify Hosting feature

Monorepo

### Question

Prequel: A am already using NX and Next.JS on amplify, but with a ton of workarounds as there wasn't a clear support for monorepos when I was creating my older deployments. However, I recently noticed that you have added support for monorepos and you support NX now, which made me very happy and I created a branch where I'm testing that.

The monorepo's frontend is not the repository's root, so I set the `buildPath` property to the NX workspace ROOT.
The build settings look like this
```
version: 1
applications:
  - frontend:
      phases:
        preBuild:
          commands:
            - npm install
        build:
          commands:
            - npx nx build <proj-name>
      artifacts:
        baseDirectory: dist/apps/<proj-name>/.next
        files:
          - '**/*'
      cache:
        paths:
          - node_modules/**/*
      buildPath: enter21-fe
    appRoot: enter21-fe/apps/<proj-name>
```

To my immense surprise, the build passed the first time, but when I visit the provided temp domain I get a 404 - page can’t be found error. 

I tried to check the access the logs and all requests fail with `404` while also ending with the following content
```
https,515,1.884,-,TLSv1.3,TLS_AES_128_GCM_SHA256,Error,HTTP/2.0,-,-,17771,1.884,Error,-,0,-,-
```

I am sorry to be posting here, but does anyone know what I'm doing wrong? I think I followed the provided documentation.

### Next.js version
13.4.12

### @nx/next version
16.5.5
