### ISSUE TITLE
Next.JS deployment not working after build completed

### ISSUE THREAD

**Issue by questionableservices** [aws-amplify/amplify-hosting#3631]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d1nkrztuk7xgun

### AWS Region

eu-central-1

### Amplify Hosting feature

Frontend builds, SSR

### Frontend framework

Next.js

### Next.js version

13.1.6

### Next.js router

Pages Router

### Describe the bug

In the last few days, deployments simply do not work. The app I am trying to deploy is an initial version of one that was easily deploy two weeks ago. Now I just keep getting this error:

`2023-07-31T18:52:16.797Z [INFO]: # Completed phase: build
2023-07-31T18:52:16.800Z [INFO]: ## Build completed successfully
2023-07-31T18:52:16.801Z [INFO]: # Starting caching...
2023-07-31T18:52:16.811Z [INFO]: # Creating cache artifact...
2023-07-31T18:52:25.048Z [INFO]: # Created cache artifact
2023-07-31T18:52:25.165Z [INFO]: # Uploading cache artifact...
2023-07-31T18:52:28.547Z [INFO]: # Uploaded cache artifact
2023-07-31T18:52:28.618Z [INFO]: # Caching completed
2023-07-31T18:52:28.620Z [INFO]: Setting NEXT_PRIVATE_STANDALONE=true to produce .next/standalone directory
2023-07-31T18:52:28.621Z [INFO]: # No custom headers found.
2023-07-31T18:52:29.494Z [ERROR]: !!! CustomerError: Required dependency file not found: /codebuild/output/src2725073759/src/webcv/amplify.sh`

I've read in several places ( like this [one](https://github.com/aws-amplify/amplify-hosting/issues/3615#issuecomment-1650590891) ) that there has been a change.

### Expected behavior

Build and deploy running smoothly like in the last few deploys done before the update on Amplify hosting

### Reproduction steps

1. Connect repo
2. Start a deploy

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm install
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

### Log output

<details>

```
# Put your logs below this line


```

</details>
