### ISSUE TITLE
deployed scuccesfully but gives 404 error while open the  master branch URL 

### ISSUE THREAD

**Issue by xkeshav** [aws-amplify/amplify-hosting#3636]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

https://us-east-1.console.aws.amazon.com/amplify/home?region=us-east-1#/d1v0nmn943cmur

### AWS Region

us-east-1

### Amplify Hosting feature

Frontend builds

### Frontend framework

JavaScript

### Next.js version

N/A

### Next.js router

N/A

### Describe the bug

I have build javacsript project and build with webpack. build completed succesfully but the master branch URl does not open

https://master.d1v0nmn943cmur.amplifyapp.com   <-- gives 404 error

```txt
This master.d1v0nmn943cmur.amplifyapp.com page can’t be foundNo webpage was found for the web address: https://master.d1v0nmn943cmur.amplifyapp.com/
HTTP ERROR 404
```

and in console it gives error

> crbug/1173575, non-JS module files deprecated.

what cound be the possible issue?

### Expected behavior

it should run and display the data

### Reproduction steps

open application :
https://master.d1v0nmn943cmur.amplifyapp.com/

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    # IMPORTANT - Please verify your build commands
    build:
      commands: 
        - npm run build
  artifacts:
    # IMPORTANT - Please verify your build output directory
    baseDirectory: /dist
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*

backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
```

### Log output

N/A

### Additional information

N/A
