### ISSUE TITLE
Intermittent CORS error in Amplify-hosted Angular app when loading static assets

### ISSUE THREAD

**Issue by ludobegins** [aws-amplify/amplify-hosting#3669]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d1gbfndkwawfxf

### AWS Region

sa-east-1

### Amplify Hosting feature

Access control, Custom headers, Monorepo

### Question

Sometimes, some users of our Angular app hosted on Amplify encounter a CORS error when loading static assets (like png or svg icons):
```
Access to fetch at 'https://www.myUrl.com/assets/icons/telephone.svg' (redirected from 'https://myUrl.com/assets/icons/telephone.svg') from origin 'https://myUrl.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```
I've configured custom headers in Amplify (followed instructions for monorepo), but some users are still reporting issues.

Our `customHttp.yml` is like this:
```
applications:
  - appRoot: webapp
    customHeaders:
      - pattern: '**'
        headers:
          - key: 'Access-Control-Allow-Origin'
            value: '*'
          - key: 'Vary'
            value: 'Origin, Access-Control-Request-Headers, Access-Control-Request-Method'
```
App is located in `webapp` directory which is at the root of the repository.

I'm trying to match all files with '**' and allow all origins with '*'. The Vary header was tried based on [this](https://stackoverflow.com/questions/44800431/caching-effect-on-cors-no-access-control-allow-origin-header-is-present-on-th) stack overflow question/answer.

What could be causing this CORS error ?

I don't understand why it happens only for some users and intermittently, and wonder if there is any related setting I'm missing or a way to refine troubleshooting.
