### ISSUE TITLE
Build faild : Please check the supported SSR features to find if your build failure

### ISSUE THREAD

**Issue by proton0210** [aws-amplify/amplify-hosting#3678]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d2sqsuoc325ve4

### AWS Region

ap-south-1

### Amplify Hosting feature

Frontend builds, SSR

### Question

I'm trying to host Nextjs 13.4 application 

here is my .yml file 

```
version: 1
applications:
  - frontend:
      phases:
        preBuild:
          commands:
            - npm install --package-lock-only
            - npm ci
        build:
          commands:
            - env | grep -e NEXT_PUBLIC_ >> .env.production
            - npm run build
      artifacts:
        baseDirectory: .next
        files:
          - '**/*'
      cache:
        paths:
          - node_modules/**/*
    appRoot: frontend


```
it so happens the app hosted 2 weeks before works just fine the appId of working app : d3m5kt17r5818r 👍 
When I try to deploy same app again with same settings i'm getting error
Error app id : d2sqsuoc325ve4 👎 

Code Repo: https://github.com/proton0210/Cognito

kindly help me
