### ISSUE TITLE
Frontend deployment step failing with error apparently swallowed

### ISSUE THREAD

**Issue by brauliolledo** [aws-amplify/amplify-hosting#3679]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d2kjezisb4vcsj

### AWS Region

us-east-1

### Amplify Hosting feature

Frontend builds

### Frontend framework

Next.js

### Next.js version

12.1.6

### Next.js router

App Router

### Describe the bug

The frontend deployment pipeline for one of our environments is failing without any clear errors, showing only `Terminating logging...`

We do have some warnings from ESLint and AWS Pinpoint, but we've had those for a while, and they do not cause the build to fail on any other environment.

The problem occurs a while after the `[INFO]: Starting SSR Build...` step.

I'm opening this issue as it is stated on a similar issue [here](https://github.com/aws-amplify/amplify-hosting/issues/1960#issuecomment-862917675) that Amplify might be swallowing some errors. So hopefully someone from the Amplify team can provide more details on this.

I have included the App ID and region for context.

### Expected behavior

The pipeline to succeed if no errors have happened, or to display some actionable error output 

### Reproduction steps

1. Trigger an Amplify Hosting deployment that contains a Frontend step with a Next.js app
2. Wait for the pipeline to work on the Frontend build and start on the `Starting SSR Build...` step

### Build Settings

```yaml
This would be our latest `amplify.yml` for that branch. As you can see, I've attempted changing the Node version from what we use on other pipelines, and increase the memory limit.

: 1
backend:
  phases:
    build:
      commands:
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - nvm install 14.18.1
        - nvm use 14.18.1
        - npm ci
    build:
      commands:
        - export NODE_OPTIONS="--max-old-space-size=5120"
        - echo $NODE_OPTIONS
        - node -v
        - npm run build:export
  artifacts:
    baseDirectory: out
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

### Log output

```
2023-08-30T13:14:16.809Z [INFO]: Starting SSR Build...
2023-08-30T13:15:42.377Z [ERROR]: ./src/pages/_app.tsx
[... SOME ESLINT WARNINGS HERE]
 info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
Terminating logging...
```
