### ISSUE TITLE
Wrong host (default domain URL) in Next JS application

### ISSUE THREAD

**Issue by santafoo-aarini** [aws-amplify/amplify-hosting#3686]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d3jc37kz92edxo

### AWS Region

eu-west-3

### Amplify Hosting feature

Deployments, Frontend builds

### Frontend framework

Next.js

### Next.js version

13.4.19

### Next.js router

App Router

### Describe the bug

The Next JS application displays the following url as the app base url: 
https://prod.eu-west-3.gateway.amplify.aws.dev

Instead, the correct value should be:
https://dev.d3jc37kz92edxo.amplifyapp.com/

### Expected behavior

The correct value of the Next JS application base URL should be:
https://dev.d3jc37kz92edxo.amplifyapp.com/

### Reproduction steps

1. Clone https://github.com/saleor/saleor-app-payment-stripe
2. Add the amplify.yml with the following code: 
```
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm install -g pnpm
        - pnpm install
    build:
      commands:
        - env | grep -e SECRET_KEY >> .env.production
        - env | grep -e APP_DEBUG >> .env.production
        - npm run build
  artifacts:
    baseDirectory: .next
    files:
      - "**/*"
  # cache:
  #   paths:
  #     - node_modules/**/*
  #     - .next/cache/**/*
```

3. Deploy the app with Amplify
4. Go to the app's default domain URL navigate to the path /api/manifest, (e.g. https://branch.app_id.amplifyapp.com/api/manifest)
5. Check the property "appUrl" ... it should read the default app url, instead it reads https://prod.eu-west-3.gateway.amplify.aws.dev

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm install -g pnpm
        - pnpm install
    build:
      commands:
        - env | grep -e SECRET_KEY >> .env.production
        - env | grep -e APP_DEBUG >> .env.production
        - npm run build
  artifacts:
    baseDirectory: .next
    files:
      - "**/*"
  # cache:
  #   paths:
  #     - node_modules/**/*
  #     - .next/cache/**/*
```

### Log output

<details>

```
# Put your logs below this line


```

</details>
