### ISSUE TITLE
Using AmplifyPush --simple in Amplify CI does not update backend

### ISSUE THREAD

**Issue by krosiek** [aws-amplify/amplify-hosting#3698]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d3t3w0sqy49ffv

### AWS Region

eu-central-1

### Amplify Hosting feature

Backend builds, Deployments

### Question

I am trying to run `amplifyPush --simple` to build backend on github trigger according to https://docs.aws.amazon.com/amplify/latest/userguide/build-settings.html
The build succeeds but the backend is not updated.
amplify.yml:
```
version: 1
frontend:
  phases:
    build:
      commands: []
  artifacts:
    baseDirectory: /
    files:
      - '**/*'
  cache:
    paths: []
backend:
  phases:
    build:
      commands:
        - amplifyPush --simple
  artifacts:
    baseDirectory: /
    files:
      - '**/*'
  cache:
    paths: []

```
1. I modify schema.graphql.
2. Push go the github
3. CI Trigger is called and build is happening for latest commit.
4. No backend schema is updated.

Is it enough to run `amplifyPush --simple` to deploy backend? I tried to add `amplify push --yes` after amplifyPush, but `amplify status` shows no changes to be pushed.
In environment variables i have set up: AMPLIFY_GOOGLE_CLIENT_ID, AMPLIFY_GOOGLE_CLIENT_SECRET, _LIVE_UPDATES, USER_BRANCH. Maybe I should configure something more?
