### ISSUE TITLE
Amplify with next.js 500 Internal Server Error.

### ISSUE THREAD

**Issue by Vhnce** [aws-amplify/amplify-hosting#3703]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d34jkzchqkdcby

### AWS Region

eu-west-2

### Amplify Hosting feature

SSR

### Frontend framework

Next.js

### Next.js version

13.2.4

### Next.js router

App Router

### Describe the bug

Error 500 | Internal server 

Error is displayed after deployment of amplify web hosting with next.js

This code base works with vercel without issue.

### Expected behavior

page should display from url generated after deployment

### Reproduction steps

open link in browser or from url via amplify console

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
    - node_modules/**/*
```

### Log output

<details>

```
# Put your logs below this line


```

</details>
