### ISSUE TITLE
Node 18.0, Not Authorized to access when Lambda's are pushed to different environment

### ISSUE THREAD

**Issue by balareddy-ec** [aws-amplify/amplify-hosting#3715]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d2xbhp02wbpvci

### AWS Region

us-east-1

### Amplify Hosting feature

Backend environments, Environment variables

### Frontend framework

Vue

### Next.js version

N/A

### Next.js router

N/A

### Describe the bug

Created NodeJS function using `amplify add function`.
Provided `api` permissions(Query, Mutation).
Nodejs: 18.0
Amplify CLI: 12.4.0

Functions created as expected, including AppSync environment variables.
Fetched the data using AppSync working as expected.

Now merged the newly created functions to different existing environment.
AppSync environment variables not populated correctly.
Getting Not Authorized to access for AppSync queries.

1. Environment variables in the environment populated as below:

```
API_ECAUTHCONNECTEDAPP_GRAPHQLAPIENDPOINTOUTPUT = apiecauthconnectedappGraphQLAPIEndpointOutput
API_ECAUTHCONNECTEDAPP_GRAPHQLAPIIDOUTPUT  = apiecauthconnectedappGraphQLAPIIdOutput
API_ECAUTHCONNECTEDAPP_GRAPHQLAPIKEYOUTPUT = apiecauthconnectedappGraphQLAPIKeyOutput
```

2. Verified the permissions for the function, available as expected.
 

### Expected behavior

1. Environment variables should be displayed based on environment.
2. AppSync calls should happen without any error.(**Not Authorized to access**)

### Reproduction steps

1. Created NodeJS function using `amplify add function`.
2. Provided `api` permissions(Query, Mutation).
3. Nodejs: 18.0
4. Amplify CLI: 12.4.0
5. Functions created as expected, including AppSync environment variables.
6. Fetched the data using AppSync working as expected.
7. Now merged the newly created functions to different existing environment.
8. AppSync environment variables not populated correctly.
9. Getting Not Authorized to access for AppSync queries.

### Build Settings

```yaml
version: 1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - envCache --set stackInfo "" # Clear cache
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: dist
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

### Log output

<details>

```
# Put your logs below this line
{\"statusCode\":400,\"content\":{\"data\":{\"XXX\":null},\"errors\":[{\"path\":[\"XXX\"],\"data\":null,\"errorType\":\"Unauthorized\",\"errorInfo\":null,\"locations\":[{\"line\":3,\"column\":5,\"sourceName\":null}],\"message\":\"Not Authorized to access XXX on type Query\"}]}}

```

</details>
