### ISSUE TITLE
Missing access key in Next.js 13 route handlers

### ISSUE THREAD

**Issue by agazibaric** [aws-amplify/amplify-hosting#3732]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [x] I have removed any sensitive information from my code snippets and submission.

### App Id

d1e9ukt9805kdz

### AWS Region

us-west-1

### Amplify Hosting feature

Environment variables, Service role

### Question

I am facing an issue when attempting to access `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` within a Next.js 13.4.12 with App Router. I'm trying to perform a server-side call to AWS SES inside of Route Handlers. Here's the sample code:

```ts
// src/app/api/route.ts

Amplify.configure({ ...awsmobile, ssr: true });

const ses = new aws.SES({
  credentials: {
    accessKeyId: process.env.AWS_ACCESS_KEY_ID,
    secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
  },
});

export async function POST(request: Request) {
// send email via ses
}
```

Both `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` are undefined. I have attached the right SES permissions to the service role of the aws amplify app.

I expect that the Route Handlers assume the role of the service which will provide those credentials inside of env.

How can I obtain those credentials without setting them manually in the build step?

**Comment by Jay2113** [comment]
Hi @agazibaric 👋 , thanks for raising this!

Have you made the `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` environment variables accessible to the server-side compute runtime: https://docs.aws.amazon.com/amplify/latest/userguide/ssr-environment-variables.html?

Your build specification file `amplify.yml` should look something like:
```
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - env | grep -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY >> .env.production
        - npm run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
      - .next/cache/**/*
```

**Comment by agazibaric** [comment]
Hi @Jay2113 , thank you for the answer!

I've tried adding those variables to the build step as you described, but unfortunately, they don't seem to be present there. I've cat the .env.production file and the secrets are missing.

As a potential workaround I could generate access keys and add them to the AWS Amplify Environment as `ACCESS_KEY_ID`  and `SECRET_ACCESS_KEY` (without the `AWS_` prefix, as it's reserved by Amplify).
By exposing these keys in the build step, I can retrieve them on the server side using the following configuration:
```
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - env | grep -e ACCESS_KEY_ID -e SECRET_ACCESS_KEY >> .env.production
        - npm run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
      - .next/cache/**/*
```

However, my goal is to find a solution that doesn't require manual setup of these secrets.
