### ISSUE TITLE
Nextjs Server Actions fail

### ISSUE THREAD

**Issue by Zeedinstein** [aws-amplify/amplify-hosting#3758]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d2ke7czr1ze2b2

### AWS Region

eu-west-1

### Amplify Hosting feature

SSR

### Frontend framework

Next.js

### Next.js version

18.18.1

### Next.js router

App Router

### Describe the bug

Server Actions fail when hosting with Amplify. 

I'm using NextJS 13.5.4

### Expected behavior

Expect the server action to run successfully. 

### Reproduction steps

1. Create a NextJS app with version 13.5.4
2. Create a server action for a page
3. Execute the action to call the server action
4. Receive a 500 error from the request

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - env | grep -e API >> .env.production
        - npm run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

### Log output

<details>

```
# Put your logs below this line


TypeError: Cannot read properties of undefined (reading 'workers')
--
at /var/task/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.prod.js:117:5940
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async t2 (/var/task/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.prod.js:117:4679)
at async H (/var/task/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.prod.js:117:29657)
at async doRender (/var/task/node_modules/next/dist/server/base-server.js:1294:26)
at async cacheEntry.responseCache.get.incrementalCache.incrementalCache (/var/task/node_modules/next/dist/server/base-server.js:1446:28)
at async /var/task/node_modules/next/dist/server/response-cache/index.js:102:36



```

</details>
