### ISSUE TITLE
Trouble Migrating Next.js 13 Project from Vercel to AWS Amplify: "target" Property Error During Build

### ISSUE THREAD

**Issue by Phobarp** [aws-amplify/amplify-hosting#3777]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d3oljxqm6ok5q4

### AWS Region

us-east-2

### Amplify Hosting feature

Build settings

### Frontend framework

Next.js

### Next.js version

13

### Next.js router

Pages Router

### Describe the bug

I am currently migrating my Next.js project from Vercel to AWS Amplify and have run into an issue during the build process. The build fails with an error stating "The 'target' property is no longer supported in next.config.js."

Additional Details:
Node.js Version: v16.20.2

### Expected behavior

The project should build and deploy without any errors related to the target property in next.config.js.

### Reproduction steps

1) Migrate Next.js 13 project from Vercel to AWS Amplify.
2) Configure AWS Amplify build settings.
3) Trigger a build.

### Build Settings

```yaml
version: 1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - nvm install 16
        - nvm use 16
        - npm install
    build:
      commands:
        - npx next build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
      - $(npm root --global)/**/*
```

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

I am specifically migrating from Vercel to AWS Amplify, and the project was working fine on Vercel. I have not been able to deploy the project successfully on AWS Amplify due to this issue.
