### ISSUE TITLE
Hosting Next.js web in Yarn Workspace Monorepo was Failed.

### ISSUE THREAD

**Issue by jiyaaany** [aws-amplify/amplify-hosting#3797]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d1c90c3mxyn376

### AWS Region

ap-northeast-2

### Amplify Hosting feature

Monorepo, SSR

### Frontend framework

Next.js

### Next.js version

13

### Next.js router

Pages Router

### Describe the bug

First, My project architecture like below

```
project-root
  packages
    nextjs-web
      .next // build output
    ...apps
```

I set up deploying next.js web through Amplify but it failed at second step (provisioning > **build**)

### Expected behavior

Build Success

### Reproduction steps

![스크린샷 2023-11-10 오후 5 16 07](https://github.com/aws-amplify/amplify-hosting/assets/43168524/dcabb32d-aa71-4470-a142-36e72336678c)

### Build Settings

```yaml
version: 1
applications:
  - frontend:
      phases:
        preBuild:
          commands:
            - yarn install
        build:
          commands:
            - yarn web build # web is alias of nextjs-web package
      artifacts:
        baseDirectory: packages/nextjs-web/.next
        files:
          - '**/*'
      cache:
        paths:
          - .yarn/**/*
      buildPath: /
    appRoot: packages/nextjs-web
    customHeaders:
    - pattern: /
    headers:
      - key: Cache-Control
        value: s-maxage=10
```

### Log output

<details>

```
# Put your logs below this line
2023-11-10T08:05:40.632Z [INFO]: Found customHttp.yml, applying custom headers...
2023-11-10T08:05:40.710Z [ERROR]: !!! CustomerError: Cannot find package: next. Please ensure the dependency is installed correctly
```

</details>

### Additional information

I think It looks like it's all over by build. But I don't know what makes it fail after the build.
