### ISSUE TITLE
Switching build image causes a different app ID to be used for GitHub app check

### ISSUE THREAD

**Issue by terrymun** [aws-amplify/amplify-hosting#3809]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d179m7yexeqiqu

### AWS Region

eu-west-1

### Amplify Hosting feature

Webhooks

### Frontend framework

Next.js

### Next.js version

14.0.3

### Next.js router

App Router

### Describe the bug

As part of the process to upgrade to `next@14`, we are switching the build image from Amazon Linux:2 to Amazing Linux:2023 as recommended, as it has `node@18.18` installed.

However it seems that the AWS Amplify Console Web Preview check that runs when a PR is created will use an incorrect app ID. Our app has an ID of `d179m7yexeqiqu`, but if the latest build image is used, the app ID switches to `dbrvsu6zabdup` in the check, which causes it to falsely report that the Preview deployment has failed as the app does not exist. The link shown at the bottom of the check indicates that an incorrect and unrelated app ID is used: https://console.aws.amazon.com/amplify/home?region=eu-west-1#/dbrvsu6zabdup/pr-880/1

The correct links should be https://console.aws.amazon.com/amplify/home?region=eu-west-1#/d179m7yexeqiqu/pr-880/1

### Expected behavior

The link generated by AWS Amplify Console Web Preview uses an incorrect app ID, and the check will fail as the app does not exist.

### Reproduction steps

1. Switch the build image to something other than the default, e.g. to "Amazon Linux:2023"
2. Create a PR
3. Verify that "AWS Amplify Console Web Preview" check is running, and wait
4. The check will fail and falsely report deployment has failed, as it uses an incorrect app ID to perform the check

### Build Settings

```yaml
version: '1.0'
frontend:
  phases:
    preBuild:
      commands:
        - yarn config set cacheFolder .yarn-cache
        - PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 yarn install --immutable
    build:
      commands:
        - export NODE_OPTIONS=--max-old-space-size=4096
        - yarn nx run site:build:production --skip-nx-cache

  artifacts:
    baseDirectory: dist/packages/site/.next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
      - .yarn-cache/**/*
```

### Log output

No error messages are produced, and the error is coming from the GitHub check from the Amplify app.
