### ISSUE TITLE
Having trouble deploying 

### ISSUE THREAD

**Issue by akbarkhawaja1** [aws-amplify/amplify-hosting#3821]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d38bupngobwmay

### AWS Region

us-west-1

### Amplify Hosting feature

Frontend builds

### Frontend framework

React

### Next.js version

N/A

### Next.js router

N/A

### Describe the bug

So after my repository has been cloned and my backend build as complete the deployment moves on to the frontend build and it says successful but remains pending and doesn't move on to the phase for deployment. 

### Expected behavior

i would like for my repo to build successfully test and then deploy 

### Reproduction steps

the issue is reproduce everytime i try to deploy the app again 

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci --legacy-peer-deps
    build:
      commands:
        - npm run build 
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

<img width="1461" alt="Screenshot 2023-11-20 at 4 20 45 PM" src="https://github.com/aws-amplify/amplify-hosting/assets/124652951/0d0c8570-7e90-4156-93b2-1701d9a90e9e">
