### ISSUE TITLE
Amplify hangs at Build phase with no errors for subfolders package installation

### ISSUE THREAD

**Issue by clukhei** [aws-amplify/amplify-hosting#3830]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d1fusmcnk5bd8d

### AWS Region

us-east-1

### Amplify Hosting feature

Frontend builds

### Frontend framework

Jekyll

### Next.js version

N/A

### Next.js router

N/A

### Describe the bug

I rearranged my project into folders where each folder runs its own package installation and build. However at Build step, amplify console hangs after npm installation (and sometimes during jekyll bundle install) with no errors. 

I read that amplify's example to cd into a project folder and also tried monorepo 

Project directory : 
<img width="269" alt="Screenshot 2023-11-28 at 10 28 30 AM" src="https://github.com/aws-amplify/amplify-hosting/assets/55618945/17c3e717-b6ce-4a1c-90b1-5b6e6bb48f14">

Context: 
My project requires to setup `lib` folder with `npm ci` and `npm run build ` and subsequently `portal` folder should run `npm ci` , `bundle install` and `npm run build`. `portal` folder outputs a jekyll static site in `portal/_site` folder which are the artifacts. `lib` folder is a webpack project and its build will output a css file into `portal` folder. 

I have also tried monorepo but it always fails at certain npm installation or bundle installation with no errors until build timed out at 30 min mark.  All the commands that I've written in amplify is tested in local and works. 

This is the amplify file which I have tried , also commented out and run simple cd lib and npm ci but it still hanged 
Amplify file: 
```
version: 1.0
frontend:
  phases:
    preBuild:
      commands:
        # - rvm get stable && rvm install 3.0.0
        # - rvm use 3.0.0
        # - gem install bundler -v '=2.3.13'
        - cd lib && npm ci
        # - cd ../portal
        # - pwd
        # - npm ci
    build:
      commands:
        # - cd ../lib && npm run build
        # - cd ../portal
        # - bundle update --bundler
        # - bundle install
        # - ls -a
        # - pwd
        - |
          if [ "${AWS_BRANCH}" = "v2" ]
          then 
            JEKYLL_ENV=production npm run build
          else
            npm run build
          fi
        - ls -a

  artifacts:
    baseDirectory: portal/_site
    files:
      - '**/*'
  cache:
    paths: [] 
```

Amplify Console screenshot: 
<img width="1573" alt="Screenshot 2023-11-28 at 10 36 06 AM" src="https://github.com/aws-amplify/amplify-hosting/assets/55618945/e14ff87e-17f0-45bc-bd32-8c6cf473b9d1">

**Monorepo settings**
I also tried monorepo although im not sure if the project is considered a monorepo as `lib` folder is more of a dependency than it is an app. I only need to serve static files from portal folder , but `portal` folder relies on `lib` folder. But regardless, I couldnt get pass the installation phase. 

Amplify file: 
```
version: 1
applications:
  - appRoot: lib
    frontend:
      buildPath: /
      phases:
        preBuild:
          commands:
            - npm ci 
        build:
          commands:
            - npm run build
      artifacts:
        files:
            - '**/*'
        baseDirectory: /
      cache:
        paths: []

  - appRoot: portal
    frontend:
      buildPath: /
      phases:
        preBuild:
          commands:
            - rvm get stable && rvm install 3.0.0
            - rvm use 3.0.0
            - gem install bundler -v '=2.3.13'
            - bundle update --bundler
            - bundle install
            - npm ci
        build:
          commands:
            - |
              if [ "${AWS_BRANCH}" = "v2" ]
              then 
                JEKYLL_ENV=production npm run build
              else
                npm run build 
              fi
              
      artifacts:
        files:
            - '**/*'
        baseDirectory: /
      cache:
        paths: []
```

Amplify console :
hangs here
<img width="1669" alt="Screenshot 2023-11-28 at 10 51 38 AM" src="https://github.com/aws-amplify/amplify-hosting/assets/55618945/906693f8-0063-40de-9ff2-792ebf3f4855">

Previously, amplify was working for me when everything was in root folder. I am wondering if there is something buggy about subfolders package installation for amplify? 

### Expected behavior

I expect that the console should output an error instead of hanging indefinitely till build time out. 

### Reproduction steps

see description 

### Build Settings

```yaml
see description
```

### Log output

see description
