### ISSUE TITLE
The latest NextJS release - 14.0.4 - does not work on Amplify Hosting

### ISSUE THREAD

**Issue by jmcpeak** [aws-amplify/amplify-hosting#3847]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d1jfsikkc5nu2t

### AWS Region

us-east-1

### Amplify Hosting feature

Build settings, CloudFormation, Custom build image, Custom domain, Deployments, E2E Cypress tests, Environment variables, Frontend builds, Git providers

### Frontend framework

React

### Next.js version

14.0.4

### Next.js router

App Router

### Describe the bug

Build succeeds but when I attempt to access the site I get my loading.tsx page and then this error:

Error: Minified React error #306; visit [https://reactjs.org/docs/error-decoder.html?invariant=306&args[]=undefined&args[]=](https://reactjs.org/docs/error-decoder.html?invariant=306&args%5b%5d=undefined&args%5b%5d=) for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at iU (fd9d1056-75d948c468d93b51.js:1:116917)
    at o2 (fd9d1056-75d948c468d93b51.js:1:94371)
    at fd9d1056-75d948c468d93b51.js:1:94193
    at o1 (fd9d1056-75d948c468d93b51.js:1:94200)
    at oV (fd9d1056-75d948c468d93b51.js:1:91687)
    at n1 (fd9d1056-75d948c468d93b51.js:1:37344)
    at n3 (fd9d1056-75d948c468d93b51.js:1:38078)
    at fd9d1056-75d948c468d93b51.js:1:39112

if I follow the link, this is the error: Element type is invalid. Received a promise that resolves to: undefined. Lazy element type must resolve to a class or function.

### Expected behavior

Exact same branch works fine on 14.0.3.

### Reproduction steps

Access site - boom error

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preTest:
      commands:
        - npm ci # make sure to use the package-lock.json file
        - npm run lint
        - if [ $AWS_BRANCH == 'develop' ] ; then npm run build-typescript; fi
    test:
      commands:
        - npm run test
    build:
      commands:
        - npm run build
        #- if [ $AWS_BRANCH == 'develop' ] ; then npm run deploy-storybook; fi
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/* # Cache `node_modules` for faster `yarn` or `npm i`
test:
  phases:
    test:
      commands:
        - npm run cypress-run
  artifacts:
    baseDirectory: cypress
    files:
      - '**/*.png'
      - '**/*.mp4'
```

### Log output

<details>

```
# Put your logs below this line
Error: Minified React error #306; visit [https://reactjs.org/docs/error-decoder.html?invariant=306&args[]=undefined&args[]=](https://reactjs.org/docs/error-decoder.html?invariant=306&args%5b%5d=undefined&args%5b%5d=) for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at iU (fd9d1056-75d948c468d93b51.js:1:116917)
    at o2 (fd9d1056-75d948c468d93b51.js:1:94371)
    at fd9d1056-75d948c468d93b51.js:1:94193
    at o1 (fd9d1056-75d948c468d93b51.js:1:94200)
    at oV (fd9d1056-75d948c468d93b51.js:1:91687)
    at n1 (fd9d1056-75d948c468d93b51.js:1:37344)
    at n3 (fd9d1056-75d948c468d93b51.js:1:38078)
    at fd9d1056-75d948c468d93b51.js:1:39112
Element type is invalid. Received a promise that resolves to: undefined. Lazy element type must resolve to a class or function.

```

</details>
