### ISSUE TITLE
Houston, there's a problem Failed to create app. You have reached the maximum number of apps in this account.

### ISSUE THREAD

**Issue by recursivezero** [aws-amplify/amplify-hosting#3858]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

NEW_APP

### AWS Region

us-east-1

### Amplify Hosting feature

Deployments

### Frontend framework

Other

### Next.js version

N/A

### Next.js router

N/A

### Describe the bug

I have Astro based githib project and tried to connect githiub repo and deploy like always but it says

Houston, there's a problem
Failed to create app. You have reached the maximum number of apps in this account.

### Expected behavior

it should build and deploy

### Reproduction steps

Just try

### Build Settings

```yaml
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: dist
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

this is based on Atro
