### ISSUE TITLE
BUG CICD is not deploying changes to the back-end

### ISSUE THREAD

**Issue by OperationalFallacy** [aws-amplify/amplify-hosting#3898]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have removed any sensitive information from my code snippets and submission.

### Amplify Hosting feature

Backend builds

### Is your feature request related to a problem? Please describe:

I've made some changes to the backend/function, added custom policy.

Local amplify shows the changes pending. Pushed it to the env branch, build runs - and... nothing

Local amplify still shows pending changes to the functions.

```
version: 1
applications:
  - appRoot: xxx-website
    backend:
      phases:
        install:
          commands:
            - pwd
            - cd ../xxx-api
            - node --version
            - nvm use 18
            - nvm use 18.17.0 || true
            - node --version
            - yarn global add tsc-alias typescript tsc
        build:
          commands:
            - yarn install --production
            - amplify --version
            - cat $(which amplifyPush) || true
            - amplifyPush --simple
```

Builds logs show changes to the resources

```
UPDATE_IN_PROGRESS                  functionXxx AWS::CloudFormation::Stack Fri Jan 12 2024 14:04:46 GMT+0000 (Coordinated Universal Time)
```

Build configured with Linux2023 image.

### Describe how you'd like this feature to work

After the build, local amplify should not have any changes pending, right?!
