### ISSUE TITLE
Adding caching options to amplify.yml causes "Build container ran out of memory"

### ISSUE THREAD

**Issue by armenr** [aws-amplify/amplify-hosting#3925]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have removed any sensitive information from my code snippets and submission.

### Amplify Hosting feature

Deployments

### Is your feature request related to a problem? Please describe:

When I add the following to my `amplify.yaml`, my builds begin to fail with the error message: `Build container ran out of memory`

```
  cache:
    paths:
      - node_modules/**/*
      - $(pnpm store path)

```

I can confirm that the build logs show our code builds successfully, all the way to the end of our build steps...and the failure happens _after_ our frontend is already built and ready to be deployed.

Removing the cache settings returns our build pipelines to a working condition.

We're using pnpm version 9 with workspaces and the following .npmrc settings:

```
shamefully-hoist=true
package-import-method=copy
link-workspace-packages=false
```

Based on information I've found in other issues, I even do the following in our pipeline, in an attempt to side-step memory-related limitations for my builds:

```
      commands:
        - |
          # Set up swap space
          echo "Setting up swap space..."
          sudo fallocate -l 32G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          sudo swapon -s
          echo "Done setting up swap space!"
```

### Describe how you'd like this feature to work

We'd like to benefit from using the cache for faster builds.

**Comment by CGarces** [comment]
Can you please try just

```yaml
  cache:
    paths:
      - "$(pnpm store path)"
```

I think that node_modules is just soft links over pnpm cache so you are storing information twice.

**Comment by shrivastavshubham34** [comment]
**Confirming this behavior on Amazon Linux 2023 with Next.js 16 + pnpm.**

I spent 3 days debugging "Build container ran out of memory" crashes on an **Amplify Gen 1** app (`Platform: WEB_COMPUTE`). I initially suspected a memory leak in my application code, but have isolated the root cause to the interaction between Amplify's caching mechanism and `pnpm`.

### 🌍 Environment

* **Platform:** AWS Amplify Gen 1 (Web Compute)
* **OS:** Amazon Linux 2023
* **Framework:** Next.js 16.0.2 (Turbopack)
* **Node Version:** v22.x
* **Package Manager:** `pnpm`

### 🐛 The Issue

When the `cache` section is enabled in `amplify.yml`, the build container runs out of memory (OOM) specifically during the **"Collecting Page Data"** phase of the Next.js build.

It appears that restoring the cache (specifically with `pnpm`'s store + `node_modules`) consumes so much memory buffer/overhead that the container enters the build phase with significantly reduced available RAM. The build starts with a "high memory floor," so when the application hits its peak memory usage during static generation, it crashes.

**Steps I took to debug (all failed while cache was enabled):**

1. Upgraded to **Large Instance (16GB RAM)** -> Still crashed (just later in the process).
2. Added 4GB Swap File via `preBuild` -> Inconsistent results, still frequent crashes.
3. Limited CPU concurrency (`cpus: 1`) -> Did not prevent OOM.

### ✅ The Fix

**Completely removing/disabling the `cache` section in `amplify.yml`.**

Once I disabled the cache and cleared the existing "ghost" cache from the AWS Console, I was able to:

1. **Downgrade** back to a **Standard (7GB RAM) Instance**.
2. Pass the build consistently.
3. Achieve faster build times (**~2m 15s**) than I ever did with caching enabled.

### 📝 Configuration Comparison

**❌ Failing Configuration (OOM Crash on 7GB & 16GB)**

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm install -g pnpm
        - pnpm config set store-dir .pnpm-store
        - pnpm install --frozen-lockfile
    build:
      commands:
        - pnpm run build
  # This section causes the OOM
  cache:
    paths:
      - .next/cache/**/*
      - .pnpm-store/**/*

```

**✅ Working Configuration (Success on 7GB Instance)**

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm install -g pnpm
        - pnpm config set store-dir .pnpm-store
        - pnpm install --frozen-lockfile
    build:
      commands:
        - pnpm run build
  # Cache is completely disabled
  # cache:
  #   paths:
  #     - .next/cache/**/*
  #     - .pnpm-store/**/*

```

### 📉 Conclusion

For `pnpm` users on AL2023, the overhead of restoring the duplicated cache (`node_modules` + `store`) seems to outweigh the performance benefits. Running a "clean build" every time is currently the only stable path for Next.js applications on standard instances.
