### ISSUE TITLE
Amplify not recognizing React app build directory code: MissingBuildArtifacts

### ISSUE THREAD

**Issue by samgates3** [aws-amplify/amplify-hosting#3936]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have removed any sensitive information from my code snippets and submission.

### Amplify Hosting feature

Build settings, Deployments

### Is your feature request related to a problem? Please describe:

For a React 18 app

Build fails at the deploy phase, giving the Build artifacts not found error. I had not made any changes to build settings before this issue and have since tried a number of variations I have seen others use from other issues for the baseDirectory path including: 

build
/build
./build
/app-name/build
./app-name/build

all give the same error.

<img width="1059" alt="Screenshot 2024-05-31 at 11 53 51 AM" src="https://github.com/aws-amplify/amplify-hosting/assets/69642365/e5f68cec-83dd-42c9-897a-cef96aa92d17">

Here are my build settings:

Default build image

```
version: 1
backend:
  phases:
    build:
      commands:
        - npm i -S graphql-ttl-transformer
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

I have also used ` - ls ` command after the build to confirm the build directory is created and all the files are there

### Describe how you'd like this feature to work

I'd like to see what changes I can  make to get this issue resolved.
