### ISSUE TITLE
Secrets usage is not documented properly and incredibly confusing

### ISSUE THREAD

**Issue by taraspos** [aws-amplify/amplify-hosting#3966]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have removed any sensitive information from my code snippets and submission.

### Amplify Hosting feature

Build settings, Deployments, Environment variables, SSR

### Is your feature request related to a problem? Please describe:

AWS Amplify Gen2 console has secrets section and following documentation page about how to use them:
- https://docs.amplify.aws/react/deploy-and-host/fullstack-branching/secrets-and-vars/

However, it's way more confusing that it might look from the first glance.

#### Frontend build time secrets

1.   Documentation says that secrets created through AWS Amplify Gen2 console are stored under the `/amplify/<app-id>/<branch-name>/<secret-name>`:
    <img width="512" alt="Screenshot 2024-11-18 at 19 10 13" src="https://github.com/user-attachments/assets/8127ad20-9aae-472c-a38f-efe039c9b1f1">

      -  But in reality they are stored under the under the path like `/amplify/<app-id>/<branch-name>-branch-<some-unknown-id>/<secret-name>`, so amplify is failing to load them in Build Time::

          ```
          2024-11-08T18:50:07.430Z [INFO]: ---- Setting Up SSM Secrets ----
          2024-11-08T18:50:07.430Z [INFO]: SSM params {"Path":"/amplify/<app_id>/main/","WithDecryption":true}
          ```

      - Secrets configured as "for all branches" are created under the documented location `/amplify/shared/<app_id>/`, but they are not being picked up during the build.

2. Amplify Application needs IAM service role assigned permissions to do `ssm: GetParametersByPath` for the `arn:<partition>:ssm:<region>:<account_id>:parameter/amplify/<app_id>/`. Otherwise you will also see warning like `[WARNING]: !Failed to set up process.env.secrets` [^0]

[^0]: https://github.com/aws-amplify/amplify-hosting/issues/3348

4. None of this is explained in the documentation:
    - https://docs.amplify.aws/react/deploy-and-host/fullstack-branching/secrets-and-vars/ - this documentation page says that it should be accessed via `import { defineAuth, secret } from '@aws-amplify/backend';` but it doesn't explain that this works only for backend applications[^1]
    [^1]: https://github.com/aws-amplify/amplify-backend/issues/1052#issuecomment-1957733738
    - Instead you need to follow [Gen1 documentation](https://docs.aws.amazon.com/amplify/latest/userguide/environment-secrets.html#set-environment-secrets), which is counter-intuitive, because we're using Gen2 app, right?

See this comment for additional details:
- https://github.com/aws-amplify/amplify-hosting/issues/3348#issuecomment-1476044689

#### Fronted run time secrets

All above also applies to the Frontend runtime secrets, but frontend runtime doesn't support env variables and seems you need to write them to the .env file instead[^2], however that would expose plaintext secret values in downloaded build artifact. And seems there are no other workarounds as of yet:
[^2]: https://docs.aws.amazon.com/amplify/latest/userguide/ssr-environment-variables.html

- ~~There is no way to pass IAM role to server side~~:
  - https://github.com/aws-amplify/amplify-hosting/issues/3205
- `import { defineAuth, secret } from '@aws-amplify/backend';` can't be used from Server Side code[^1]

### Describe how you'd like this feature to work

1. Secrets created through AWS Amplify Gen2 console should be possible to use in build time
2. Create proper documentation page explaining how to:
    - Access secrets in build time
    - Access secrets in SSR Runtime
    - Access secrets for backend

**Comment by taraspos** [comment]
Related issues:
- https://github.com/aws-amplify/docs/issues/7556
- https://github.com/aws-amplify/amplify-hosting/issues/4044

**Comment by dnellis74** [comment]
"And seems there are no other workarounds as of yet". How are people working around this?

**Comment by taraspos** [comment]
> "And seems there are no other workarounds as of yet". How are people working around this?

- https://github.com/aws-amplify/amplify-hosting/issues/3205

This got released the other day. Potentially what you can do now is to assign IAM role to your application and than implement calls to AWS Secrets Manager or SSM Parameter Store from your application code in runtime.

**Comment by dnellis74** [comment]
I am new enough to this platform, that it was only yesterday I learned there is Gen1 and Gen2, and I was following old blog post for Gen1.  It seems the "right" answer is that I need a back end, rather than having a UI directly consume AWS services.  We didn't account for that for another sprint in a few months, so it's just some shuffling of features.

**Comment by dnellis74** [comment]
> This got released the other day. Potentially what you can do now is to assign IAM role to your application and than implement calls to AWS Secrets Manager or SSM Parameter Store from your application code in runtime.

I am new enough to this platform, that it was only yesterday I learned there is Gen1 and Gen2, and I was following old blog post for Gen1. It seems the "right" answer is that I need a backend, rather than having a UI directly consume AWS services. We didn't account for that for another sprint in a few months, so it's just some shuffling of features.

For the demo today I simply put the access token straight into the build script, and I'll get a new one after the demo.

**Comment by ssijak** [comment]
Why cant we just have a toggle somewhere in the UI that says "expose all secrets as environment variables in the container running the app"?? Its a common feature every hosting provider does. Why all this juggling with using 100MB libs to fetch a secret? And are also not documented well as stated above.

**Comment by dnellis74** [comment]
Because some security nanny decided that devs and devops can't be trusted
to snoop around in the data, even though for decades 99% of us never did
this once.  A couple folks did this, and now we can't have nice things.

**Comment by Dark-Hippo** [comment]
Has anyone actually managed to get secrets to work with an Amplify build? I've tried everything I can find online, various ways of exporting the variables or echoing them to a .env file, declaring them in a env: secrets: section of the yml, granting the service role permissions to read the secrets through IAM... nothing.

**Comment by lukereative** [comment]
> Has anyone actually managed to get secrets to work with an Amplify build? I've tried everything I can find online, various ways of exporting the variables or echoing them to a .env file, declaring them in a env: secrets: section of the yml, granting the service role permissions to read the secrets through IAM... nothing.

This was the only way I could get it to work to be able to read them in the nuxt config from `process.env`, this works for secrets set up in the 'Amplify > Hosting > Secrets' panel

Edit your 'Build settings' to include the command for loading the secrets
```
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - echo "Fetching secrets from SSM..."
        - |
          for secret in $(aws ssm get-parameters-by-path \
            --path /amplify/shared/<your-app-id>/ \
            --with-decryption \
            --region <your-region> \
            --query "Parameters[*].{Name:Name}" \
            --output text); do

              key=$(basename "$secret")
              value=$(aws ssm get-parameter \
                --name "$secret" \
                --with-decryption \
                --region <your-region> \
                --query "Parameter.Value" \
                --output text)

              echo "$key=$value" >> .env
              export "$key=$value"
          done
        - corepack enable
        - pnpm install
    build:
      commands:
        - pnpm run build
  artifacts:
    baseDirectory: .amplify-hosting
    files:
      - '**/*'
```

**Comment by Dark-Hippo** [comment]
> > Has anyone actually managed to get secrets to work with an Amplify build? I've tried everything I can find online, various ways of exporting the variables or echoing them to a .env file, declaring them in a env: secrets: section of the yml, granting the service role permissions to read the secrets through IAM... nothing.
> 
> This was the only way I could get it to work to be able to read them in the nuxt config from `process.env`, this works for secrets set up in the 'Amplify > Hosting > Secrets' panel
> 
> Edit your 'Build settings' to include the command for loading the secrets
> 
> ```
> version: 1
> frontend:
>   phases:
>     preBuild:
>       commands:
>         - echo "Fetching secrets from SSM..."
>         - |
>           for secret in $(aws ssm get-parameters-by-path \
>             --path /amplify/shared/<your-app-id>/ \
>             --with-decryption \
>             --region <your-region> \
>             --query "Parameters[*].{Name:Name}" \
>             --output text); do
> 
>               key=$(basename "$secret")
>               value=$(aws ssm get-parameter \
>                 --name "$secret" \
>                 --with-decryption \
>                 --region <your-region> \
>                 --query "Parameter.Value" \
>                 --output text)
> 
>               echo "$key=$value" >> .env
>               export "$key=$value"
>           done
>         - corepack enable
>         - pnpm install
>     build:
>       commands:
>         - pnpm run build
>   artifacts:
>     baseDirectory: .amplify-hosting
>     files:
>       - '**/*'
> ```

Fantastic! That worked! This really needs to be added to the documentation (along with explanations as to how and why it works).

**Comment by l3xcaliburr** [comment]
# AWS Amplify Secrets Solution - Forum Response

**Yes, I just solved this after extensive testing! The issue is that Amplify's secret injection works differently than documented.**

## 🔍 **The Discovery**

Amplify **does** automatically fetch SSM secrets, but with two critical caveats:

1. **It only looks for parameters at the exact path** `/amplify/{app-id}/{branch}/` (NOT the branch hash suffix path)
2. **It provides them as a single JSON environment variable** called `secrets` instead of individual variables

### **What Works vs What Doesn't**

❌ **Amplify Console Secrets**: Creates parameters with branch hash like `/amplify/app-id/develop-branch-abc123/SECRET_NAME` - Amplify's auto-injection **ignores these**

✅ **Manual SSM Parameters**: Create at exact path `/amplify/app-id/develop/SECRET_NAME` - Amplify auto-injection **works**

When you check your build logs, you'll see:

```
---- Setting Up SSM Secrets ----
SSM params {"Path":"/amplify/{YOUR_APP_ID}/develop/","WithDecryption":true}
```

And in your environment:

```
secrets={"SQUARE_ACCESS_TOKEN":"YOUR_TOKEN_HERE...","SQUARE_WEBHOOK_SIGNATURE_KEY":"YOUR_WEBHOOK_KEY..."}
```

## 🛠 **The Working Solution**

Add this to your `amplify.yml` build commands:

```yaml
build:
  commands:
    # Parse Amplify's secrets JSON and export individual variables
    - 'if [ -n "$secrets" ]; then export SQUARE_ACCESS_TOKEN=$(echo "$secrets" | sed -n "s/.*\"SQUARE_ACCESS_TOKEN\":\"\\([^\"]*\\)\".*/\\1/p"); export SQUARE_WEBHOOK_SIGNATURE_KEY=$(echo "$secrets" | sed -n "s/.*\"SQUARE_WEBHOOK_SIGNATURE_KEY\":\"\\([^\"]*\\)\".*/\\1/p"); fi'

    # Write to .env.production for SSR runtime access
    - 'echo "SQUARE_ACCESS_TOKEN=$SQUARE_ACCESS_TOKEN" >> .env.production'
    - 'echo "SQUARE_WEBHOOK_SIGNATURE_KEY=$SQUARE_WEBHOOK_SIGNATURE_KEY" >> .env.production'

    - npm run build
```

## 📋 **Setup Steps**

1. **Create SSM parameters manually** at the exact path Amplify expects:

   ```bash
   aws ssm put-parameter \
     --name "/amplify/{YOUR_APP_ID}/{BRANCH}/SQUARE_ACCESS_TOKEN" \
     --value "your-token-here" \
     --type "SecureString"

   aws ssm put-parameter \
     --name "/amplify/{YOUR_APP_ID}/{BRANCH}/SQUARE_WEBHOOK_SIGNATURE_KEY" \
     --value "your-webhook-key-here" \
     --type "SecureString"
   ```

2. **Amplify automatically fetches these** and provides them in `secrets` JSON
3. **Use the parsing solution above** in your `amplify.yml`

## ❌ **Why Other Methods Fail**

- **Amplify Console Secrets**: Creates parameters with branch hash suffixes (`/develop-branch-abc123/`) that Amplify's auto-injection ignores
- **Wrong SSM paths**: Must be exact path `/amplify/{app-id}/{branch}/` - no hash suffix
- **Direct environment variables**: Amplify only provides the JSON `secrets` variable
- **Standard `env` declarations**: These don't work with Amplify's automatic SSM injection

## 🎯 **Key Insight**

Don't try to fight Amplify's system - work with it! The `secrets` JSON variable is actually reliable once you know how to parse it.

This approach:

- ✅ Works with Amplify's actual SSM injection behavior
- ✅ Uses exact paths Amplify expects (no branch hash)
- ✅ Makes secrets available at SSR runtime
- ✅ Leverages automatic JSON parsing

## 🔧 **Complete Example amplify.yml**

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        # Check if Amplify provided secrets JSON
        - 'echo "secrets env var present: $([ -n "$secrets" ] && echo "YES" || echo "NO")"'

        # Parse secrets JSON and export individual variables
        - 'if [ -n "$secrets" ]; then echo "Found secrets JSON, parsing..."; export SQUARE_ACCESS_TOKEN=$(echo "$secrets" | sed -n "s/.*\"SQUARE_ACCESS_TOKEN\":\"\\([^\"]*\\)\".*/\\1/p"); export SQUARE_WEBHOOK_SIGNATURE_KEY=$(echo "$secrets" | sed -n "s/.*\"SQUARE_WEBHOOK_SIGNATURE_KEY\":\"\\([^\"]*\\)\".*/\\1/p"); echo "Parsed ACCESS_TOKEN length: ${#SQUARE_ACCESS_TOKEN}, WEBHOOK_KEY length: ${#SQUARE_WEBHOOK_SIGNATURE_KEY}"; fi'

        # Write to .env.production for SSR runtime access
        - 'echo "SQUARE_ACCESS_TOKEN=$SQUARE_ACCESS_TOKEN" >> .env.production'
        - 'echo "SQUARE_WEBHOOK_SIGNATURE_KEY=$SQUARE_WEBHOOK_SIGNATURE_KEY" >> .env.production'

        - npm run build
  artifacts:
    baseDirectory: .next
    files:
      - "**/*"
```

## 🚨 **Important Notes**

- **Critical**: Create SSM parameters at `/amplify/{app-id}/{branch}/SECRET_NAME` - NOT with branch hash suffix
- Replace `{YOUR_APP_ID}` and `{BRANCH}` with your actual values (find app ID in build logs)
- The `sed` command uses escaped quotes to handle JSON parsing
- This works for Next.js SSR - adjust the `.env.production` path for other frameworks
- Make sure your service role has SSM read permissions
- **Don't use Amplify Console Secrets** - they create parameters at wrong paths

## 🧪 **Testing Process**

I discovered this through systematic testing:

1. **Amplify Console Secrets alone**: ❌ Build failed (wrong SSM paths)
2. **Manual SSM parameters alone**: ✅ Build succeeded (correct paths)
3. **Both together**: ✅ Build succeeded (manual parameters used)

The logs clearly show Amplify looks for `/amplify/{YOUR_APP_ID}/develop/` - no branch hash!

Hope this saves others the debugging time I went through!

---

## 🔗 **Related Issues**

This solution addresses common problems like:

- "Amplify Console secrets not working"
- "SSM parameters not found"
- "Environment variables empty in SSR"
- "Branch hash suffix breaks parameter paths"
- "Manual SSM parameters don't work"

The key is understanding that Amplify **does** work, but only with manually created SSM parameters at exact paths - NOT the Amplify Console secrets with branch hash suffixes!

**Comment by bbodien** [comment]
> build:
>   commands:
>     # Parse Amplify's secrets JSON and export individual variables
>     - 'if [ -n "$secrets" ]; then export SQUARE_ACCESS_TOKEN=$(echo "$secrets" | sed -n "s/.*\"SQUARE_ACCESS_TOKEN\":\"\\([^\"]*\\)\".*/\\1/p"); export SQUARE_WEBHOOK_SIGNATURE_KEY=$(echo "$secrets" | sed -n "s/.*\"SQUARE_WEBHOOK_SIGNATURE_KEY\":\"\\([^\"]*\\)\".*/\\1/p"); fi'
> 
>     # Write to .env.production for SSR runtime access
>     - 'echo "SQUARE_ACCESS_TOKEN=$SQUARE_ACCESS_TOKEN" >> .env.production'
>     - 'echo "SQUARE_WEBHOOK_SIGNATURE_KEY=$SQUARE_WEBHOOK_SIGNATURE_KEY" >> .env.production'

Isn't this approach just going to expose all your secrets in your build logs?

**Comment by taraspos** [comment]
> Isn't this approach just going to expose all your secrets in your build logs?

It shouldn't be visible in build logs, but plain text `.env.production` file will be available in build artifacts (for SSR apps).
And everyone who has access to build logs can also download build artifacts, as both are returned by the same [GetJob](https://docs.aws.amazon.com/amplify/latest/APIReference/API_GetJob.html) API call

**Comment by dinbtechit** [comment]
@l3xcaliburr  - Thank you for the awesome information.  I am using a regular React app here (no SSR), where one of the secrets needs to be set in the environment variable for the build to pick it up. However, for some reason, the secret is not getting picked up during `yarn build` despite being present in the env (I can see that by `cat`ing the `.env` file). Strangely, when I set the same variable `REACT_APP_CLIENT_KEY` in the regular env variables everything seems to be working fine. Any thoughts?

```yaml
    build:
      commands:
        # Check if Amplify provided secrets JSON
        - 'echo "secrets env var present: $([ -n "$secrets" ] && echo "YES" || echo "NO")"'
        # Parse secrets JSON and export individual variables
        - 'if [ -n "$secrets" ]; then echo "Found secrets JSON, parsing..."; export REACT_APP_CLIENT_KEY=$(echo "$secrets" | sed -n "s/.*\"REACT_APP_CLIENT_KEY\":\"\\([^\"]*\\)\".*/\\1/p"); fi'
        # Write to .env for SSR runtime access
        - 'echo "REACT_APP_CLIENT_KEY=$REACT_APP_CLIENT_KEY" >> .env'
        - yarn build

```

**Comment by l3xcaliburr** [comment]
**@dinbtechit** - Looking at your build commands, I think I see the issue. The problem is likely with **when** React reads environment variables vs when you're writing them to the `.env` file.

React's build process reads environment variables at the very start of the build, but you're writing to the `.env` file and then immediately running `yarn build` in the same command sequence. By that point, React has already initialized and won't pick up the newly written `.env` file.

Here are two potential solutions:

## Option 1: Export directly to shell environment (recommended)

Instead of just writing to `.env`, export the variable directly to the shell environment where `yarn build` will inherit it:

```yaml
build:
  commands:
    # Check if Amplify provided secrets JSON
    - 'echo "secrets env var present: $([ -n "$secrets" ] && echo "YES" || echo "NO")"'
    # Parse secrets JSON and export individual variables
    - 'if [ -n "$secrets" ]; then echo "Found secrets JSON, parsing..."; export REACT_APP_CLIENT_KEY=$(echo "$secrets" | sed -n "s/.*\"REACT_APP_CLIENT_KEY\":\"\\([^\"]*\\)\".*/\\1/p"); fi'
    # Write to .env for SSR runtime access
    - 'echo "REACT_APP_CLIENT_KEY=$REACT_APP_CLIENT_KEY" >> .env'
    # Verify the variable is exported
    - 'echo "REACT_APP_CLIENT_KEY length: ${#REACT_APP_CLIENT_KEY}"'
    - yarn build
```

## Option 2: Use dotenv in your React app

If you need the `.env` file approach, make sure your React app is configured to read from `.env` files during build. Install `dotenv` and configure it in your build process or use a tool like `cross-env`.

## Quick Debug Steps:

1. Add this before `yarn build`: `- 'echo "REACT_APP_CLIENT_KEY in environment: $REACT_APP_CLIENT_KEY"'`
2. Check if the variable shows up in the environment vs just in the file

## Key Insight

The key difference from my solution is that I was creating SSM parameters at the exact paths Amplify expects (`/amplify/{app-id}/{branch}/`), but you might have a different SSM setup. The core principle is the same though - **parse the `secrets` JSON and export to the shell environment, not just write to a file**.

Let me know if the direct export approach works for you!
