### ISSUE TITLE
Turborepo fails when its nested two levels down. CustomerError: The 'node_modules' folder is missing the 'next' dependency. 

### ISSUE THREAD

**Issue by a3har** [aws-amplify/amplify-hosting#4036]
### Environment information

```plain text
N/A
```

### Describe the bug

A monorepo that has turborepo managing only a subsection of the monorepo fails to deploy NextJS code. If the entire repo is a turborepo then Amplify seems to have no issues with deployment. 

Eg: https://github.com/vercel/turborepo/tree/main/examples/basic

The above example deploys without issues. 

However when you nest the turborepo under folders like apps/product-frontend like in the example below, it fails to detect the build artifacts as expected

Eg: https://github.com/a3har/turbo-test

It throws the error below. 

`
[ERROR]: !!! CustomerError: The 'node_modules' folder is missing the 'next' dependency. This is required at runtime to run your application. If you are using a monorepo framework, you may need to do additionalsetup to ensure the necessary runtime dependencies are included in the build output directory Read more: https://github.com/aws-amplify/amplify-hosting/blob/main/FAQ.md#using-a-monorepo-framework
`

### Reproduction steps

Clone the public repo https://github.com/a3har/turbo-test and use the below build settings to deploy. 

Env Variables:
- `AMPLIFY_MONOREPO_APP_ROOT=apps/product-frontend/apps/docs`
- `AMPLIFY_DIFF_DEPLOY=false`

```
version: 1
applications:
  - frontend:
      buildPath: apps/product-frontend
      phases:
        preBuild:
          commands:
            - npm ci --cache .npm --prefer-offline
        build:
          commands:
            - npx turbo build --filter=docs...
      artifacts:
        baseDirectory: apps/docs/.next
        files:
          - "**/*"
      cache:
        paths:
          - node_modules/**/*
    appRoot: apps/product-frontend/apps/docs
```

**Comment by Jay2113** [comment]
Hi @a3har 👋 , thanks for reaching out. I was able to reproduce this behavior and will mark it as a bug. I'll report back here with any potential workarounds.

**Comment by manasi-m** [comment]
Hi @Jay2113 @a3har, any updates on this? I'm facing the same issue with a monorepo where turborepo manages a subdirectory of the repo.

**Comment by rahul799** [comment]
We are also facing the same issue 😔

**Comment by nikhil-pandey** [comment]
Running into the same issue

**Comment by ericsigner** [comment]
Running into the same issue

**Comment by vvk-srf-neu-ikigai** [comment]
@Jay2113 is this being looked into ?

**Comment by TomBell95** [comment]
@Jay2113 any update ??

**Comment by TomBell95** [comment]
@a3har @vvk-srf-neu-ikigai @ericsigner @nikhil-pandey @rahul799 @manasi-m - has anyone found a workaround for this? 

Currently using turborepo and deploying via AWS CDK

```typescript
import { BuildSpec } from 'aws-cdk-lib/aws-codebuild'

const appRoot = 'apps/my-app'

export const generateBuildSpecs = () => {
  const buildSpec = BuildSpec.fromObjectToYaml({
    version: '1.0',
    applications: [
      {
        appRoot,
        frontend: {
          buildPath: '/',
          phases: {
            preBuild: {
              commands: [
                `echo "MY_SECRET_TOKEN=$(aws secretsmanager get-secret-value --secret-id my-app-amplify-\${ENV}-secret --output text --query SecretString --region xxx)" >> ${appRoot}/.env`,
                `source ${appRoot}/.env`,
                'nvm install 20.0.0',
                'nvm use 20.0.0',
                'npm install -g pnpm',
                'pnpm install',
              ],
            },
            build: {
              commands: [
                 // This dynamically changes the NEXTAUTH_URL to the preview URL
                `if [ -z "\${AWS_PULL_REQUEST_ID}" ]; then echo "NEXTAUTH_URL=$NEXTAUTH_URL" >> ${appRoot}/.env; else echo "NEXTAUTH_URL=https://pr-\${AWS_PULL_REQUEST_ID}.\${AWS_APP_ID}.amplifyapp.com" >> ${appRoot}/.env; fi`,
                'pnpm build --filter=my-app',
              ],
            },
          },
          artifacts: {
            baseDirectory: `${appRoot}/.next`,
            files: ['**/*'],
          },
          cache: {
            paths: [`${appRoot}/node_modules/**/*`],
            // paths: ['node_modules/**/*'], // <--- this causing error "out of memory"
          },
        },
      },
    ],
  })

  return buildSpec
}
```

**Comment by luismmadeirac** [comment]
Got the same error "!!! CustomerError: The 'node_modules' folder is missing the 'next' dependency...."

If you using pnpm don't forget to add the `.npmrc` file  with `node-linker=hoisted`. 

Check the Amplify FAQ Docs here - https://github.com/aws-amplify/amplify-hosting/blob/main/FAQ.md#support-for-monorepo-framework

**Comment by TomBell95** [comment]
Update: fixed my problem above by removing the `.npmrc` file and then adding it in the `preBuild` command in `buildSpec`

```typescript
    preBuild: {
        'echo "node-linker=hoisted" > .npmrc',
        ...
    },
```

**Comment by a3har** [comment]
Update: I ended up adding turborepo to the root of the monorepo to fix this but @TomBell95 's solution seems to be better.

**Comment by ant1m4tt3r** [comment]
facing the same issue, but @TomBell95 solution didn't work either.

**Comment by ant1m4tt3r** [comment]
I have even add a `ls node_modules` to check for myself in the postBuild command and next is there!

**Comment by ipakhomov** [comment]
The issue still persists. 
The workaround that helped: after installing dependencies in the `preBuild` step, re-install `next` to the root of your monorepo:

```yaml
        preBuild:
          commands:
            - npm install -g pnpm
            - echo "node-linker=hoisted" > .npmrc
            - pnpm install --frozen-lockfile
            # The line below is the workaround:
            - pnpm --filter web remove next && pnpm add next -w
````
