### ISSUE TITLE
Unsure of Usage of amplifyPush Script

### ISSUE THREAD

**Issue by jhoffmcd** [aws-amplify/amplify-hosting#524]
** Please describe which feature you have a question about? **

For normal environments from branches that I connect in the Amplify Console via the web GUI, we have `amplifyPush --simple` at the beginning of our `amplify.yml`. That's all good.

Now, we have an environment that we need to programmatically create using the AWS CLI `create-branch` and `start-job` commands. In this scenario, `amplifyPush --simple` fails with this output:

```
usage: amplify-push <--environment|-e <name>> <--simple|-s>
--environment  The name of the Amplify environment to use
--simple  Optional simple flag auto-includes stack info from env cache
```

** Provide additional details**

I can see from the [source code](https://github.com/aws-amplify/amplify-console/blob/master/scripts/amplifyPush.sh#L80) that this happens when the `$ENV` variable is not valid. We already have an existing backend that we would like to use with this env called **stg**.

I tried some other approaches, thinking maybe I need to explicitly state which backend I want this build to use: `amplifyPush --environment stg --simple` but I am still getting the same output.

Is there anyone on the team that can tell me what this roadblock that I am hitting means? Why is the script failing when we use the AWS CLI to "provision" the branch and job? Is what I am trying to do impossible with the current offering that Amplify provides?

For reference, I am also setting the backend ARN for **stg** in the `create-branch` step to make sure I associate this branch with the correct backend.

**Comment by Athena96** [comment]
Hi @jhoffmcd can you please share your amplify.yml file.

**Comment by jhoffmcd** [comment]
Sure, in the below example, you can see I commented out the amplifyPush command that did not work:

`amplifyPush -e stg -s`

```yml
version: 0.1

backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        # - if [[ ! "${AWS_BRANCH}" =~ ^release\/.* ]]; then amplifyPush -e stg -s; else amplifyPush -s; fi
        - amplifyPush -s;

frontend:
  phases:
    preBuild:
      commands:
        - echo Entered the pre-build phase...
        - nvm use $VERSION_NODE_12
        - yarn install
        - echo Linting code...
        - yarn lint
        - echo Starting test run...
        - yarn test --ci
        - echo pre-build phase complete.
    build:
      commands:
        - echo Entered the build phase...
        - yarn run build
        - echo build phase complete.
    postBuild:
      # Note: If we see a need to add tagging we can do it in post build, however we will need a way to push the tag
      commands:
        - echo Entered the post-build phase...
        # Run post build script for staging env (checks if it's in a release branch context)
        - bash ci-build-scripts/post-build-staging.sh
        - echo post-build phase complete.
  artifacts:
    baseDirectory: public
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*

```
